// Generated by make contracts from packages/contracts/events. Do not edit.

/**
 * The engine evaluated one rule version against one business profile version. Producer: applicability-engine. Consumers: obligation.
 */
export interface ApplicabilityDecided {
  /**
   * The stored decision.
   */
  decision_id: string;
  /**
   * The business evaluated.
   */
  business_id: string;
  /**
   * The rule version evaluated.
   */
  rule_version_id: string;
  /**
   * Three-valued outcome.
   */
  result: "applies" | "not_applicable" | "unsure";
  /**
   * Confidence in [0, 1]; 1 for fully deterministic evaluations.
   */
  confidence: number;
  /**
   * Profile version the decision was computed from.
   */
  profile_version: number;
  /**
   * When the decision was made.
   */
  decided_at: string;
  /**
   * True when the result is unsure or the confidence is below the review threshold.
   */
  needs_review: boolean;
  /**
   * What caused the evaluation.
   */
  trigger: "rule_published" | "profile_updated" | "manual";
}
