// Generated by make contracts from packages/contracts/events. Do not edit.

/**
 * The crawler fetched a document it had not seen at this source and stored the raw file. Producer: pipeline (source crawler). Consumers: pipeline (change detector).
 */
export interface DocumentDiscovered {
  /**
   * The source the document was listed at.
   */
  source_id: string;
  /**
   * The stored document.
   */
  document_id: string;
  /**
   * Regulator the source belongs to, such as cbic or fssai.
   */
  regulator: string;
  /**
   * Where the document was fetched from.
   */
  url: string;
  /**
   * The source's own reference, such as a notification number; empty when the listing had none.
   */
  external_ref?: string;
  /**
   * Title as listed at the source; empty when unknown.
   */
  title?: string;
  /**
   * Publication date as listed at the source; null when unknown.
   */
  published_at?: string | null;
  /**
   * Digest of the raw bytes.
   */
  sha256: string;
  /**
   * Media type of the raw file.
   */
  media_type: string;
  /**
   * When the fetch completed.
   */
  fetched_at: string;
  /**
   * Where the raw file is stored (object store URI).
   */
  raw_uri: string;
}
