// Generated by make contracts from packages/contracts/events. Do not edit.

/**
 * The pipeline parsed a stored document into clauses with stable references, the first time or with another parser. Clause text is not carried here: read it from the rulebook once the document is registered (GET /v1/rulebook/documents/{document_id}). Producer: pipeline (the ingest's parse). Consumers: none yet; the rulebook once registration moves to events (ADR-018).
 */
export interface DocumentParsed {
  /**
   * The parsed document.
   */
  document_id: string;
  /**
   * The source it came from.
   */
  source_id: string;
  /**
   * Document type: the source's, or the one the uploader gave. A statute (an Act or the Rules under it) is registered and embedded but nothing is extracted from it.
   */
  doc_type: "notification" | "circular" | "press_release" | "act_amendment" | "statute";
  /**
   * Title of the document.
   */
  title: string;
  /**
   * Primary language of the text, as a BCP 47 tag such as en or hi.
   */
  language: string;
  /**
   * Publication date; null when unknown.
   */
  published_at?: string | null;
  /**
   * Number of clauses produced.
   */
  clause_count: number;
  /**
   * Stable clause references, in document order.
   *
   * @minItems 1
   */
  clause_refs: [string, ...string[]];
  /**
   * The parser that produced the clauses, as name@version: pdf@1, pdf-tables@1, html@1, html-tables@1, or manual@1 for an analyst's transcript.
   */
  parser_version: string;
}
