// Generated by make contracts from packages/contracts/events. Do not edit.

export type { ApplicabilityDecided } from "./applicability.decided.v1";
export type { DocumentClassified } from "./document.classified.v1";
export type { DocumentDiscovered } from "./document.discovered.v1";
export type { DocumentParsed } from "./document.parsed.v1";
export type { EventEnvelope } from "./envelope.v1";
export type { EvalRunCompleted } from "./eval.run.completed.v1";
export type { NotificationFailed } from "./notification.failed.v1";
export type { NotificationSent } from "./notification.sent.v1";
export type { ObligationClosed } from "./obligation.closed.v1";
export type { ObligationCreated } from "./obligation.created.v1";
export type { ObligationDueSoon } from "./obligation.due_soon.v1";
export type { ObligationRescheduled } from "./obligation.rescheduled.v1";
export type { ProfileUpdated } from "./profile.updated.v1";
export type { RuleCandidateCreated } from "./rule.candidate.created.v1";
export type { RuleDeadlineChanged } from "./rule.deadline_changed.v1";
export type { RulePublished } from "./rule.published.v1";
export type { RuleSuperseded } from "./rule.superseded.v1";
export type { RuleWithdrawn } from "./rule.withdrawn.v1";
export type { TenantCreated } from "./tenant.created.v1";
export type { TenantDeletionRequested } from "./tenant.deletion.requested.v1";
export type { UserRoleChanged } from "./user.role.changed.v1";

export const ENVELOPE_VERSION = "1.0.0";

export const EVENT_TOPICS = {
  "applicability.decided": { version: "1.1.0", tenantScoped: true },
  "document.classified": { version: "1.0.0", tenantScoped: false },
  "document.discovered": { version: "1.0.0", tenantScoped: false },
  "document.parsed": { version: "1.1.0", tenantScoped: false },
  "eval.run.completed": { version: "1.0.0", tenantScoped: false },
  "notification.failed": { version: "1.0.1", tenantScoped: true },
  "notification.sent": { version: "1.0.1", tenantScoped: true },
  "obligation.closed": { version: "1.0.0", tenantScoped: true },
  "obligation.created": { version: "1.0.0", tenantScoped: true },
  "obligation.due_soon": { version: "1.0.0", tenantScoped: true },
  "obligation.rescheduled": { version: "1.0.0", tenantScoped: true },
  "profile.updated": { version: "1.0.0", tenantScoped: true },
  "rule.candidate.created": { version: "1.1.0", tenantScoped: false },
  "rule.deadline_changed": { version: "1.0.0", tenantScoped: false },
  "rule.published": { version: "1.0.0", tenantScoped: false },
  "rule.superseded": { version: "1.0.0", tenantScoped: false },
  "rule.withdrawn": { version: "1.0.0", tenantScoped: false },
  "tenant.created": { version: "1.0.0", tenantScoped: true },
  "tenant.deletion.requested": { version: "1.0.0", tenantScoped: true },
  "user.role.changed": { version: "1.0.0", tenantScoped: true },
} as const;

export type EventTopic = keyof typeof EVENT_TOPICS;
