// Generated by make contracts from packages/contracts/events. Do not edit.

/**
 * A channel refused or failed to deliver a notification; will_retry says whether another attempt or channel follows. Producer: notification. Consumers: obligation (audit).
 */
export interface NotificationFailed {
  /**
   * The notification.
   */
  notification_id: string;
  /**
   * The obligation it is about.
   */
  obligation_id: string;
  /**
   * The business it was sent for.
   */
  business_id: string;
  /**
   * Delivery channel that failed.
   */
  channel: "whatsapp" | "email";
  /**
   * Idempotency key of the occasion: one change card per rule version, business, recipient and channel; one reminder per obligation, reminder number, recipient and channel; one closure per obligation, recipient and channel; one reschedule per obligation, new due date, recipient and channel; one manual send per obligation, business, channel and template; one fallback per notification and fallback channel.
   */
  dedupe_key: string;
  /**
   * What the channel reported.
   */
  error: string;
  /**
   * Attempts made on this channel so far.
   */
  attempts: number;
  /**
   * True when another attempt or the fallback channel is scheduled.
   */
  will_retry: boolean;
  /**
   * When the failure was recorded.
   */
  failed_at: string;
}
