// Generated by make contracts from packages/contracts/events. Do not edit.

/**
 * A channel accepted a notification for delivery. Producer: notification. Consumers: obligation (audit), eval.
 */
export interface NotificationSent {
  /**
   * The notification.
   */
  notification_id: string;
  /**
   * The obligation it is about.
   */
  obligation_id: string;
  /**
   * The business it was sent for.
   */
  business_id: string;
  /**
   * Delivery channel.
   */
  channel: "whatsapp" | "email";
  /**
   * Idempotency key over rule version, business and channel.
   */
  dedupe_key: string;
  /**
   * The provider's id for the message; empty when it gives none.
   */
  provider_message_id?: string;
  /**
   * When the channel accepted it.
   */
  sent_at: string;
  /**
   * Language the message was rendered in.
   */
  language: string;
}
