// Generated by make contracts from packages/contracts/events. Do not edit.

/**
 * An open obligation's due date changed, usually because the regulator extended or corrected a deadline. Producer: obligation. Consumers: notification.
 */
export interface ObligationRescheduled {
  /**
   * The obligation.
   */
  obligation_id: string;
  /**
   * The business it belongs to.
   */
  business_id: string;
  /**
   * The rule version it comes from.
   */
  rule_version_id: string;
  /**
   * Due date before the change.
   */
  previous_due_at: string;
  /**
   * Due date after the change.
   */
  new_due_at: string;
  /**
   * Why the date moved.
   */
  reason: "deadline_extended" | "corrected" | "manual";
  /**
   * The rule version that changed the deadline; null for a manual change.
   */
  caused_by_rule_version_id?: string | null;
}
