// Generated by make contracts from packages/contracts/events. Do not edit.

/**
 * An open obligation's due date is near and a reminder is warranted. Producer: obligation (reminder scheduler). Consumers: notification.
 */
export interface ObligationDueSoon {
  /**
   * The obligation.
   */
  obligation_id: string;
  /**
   * The business it belongs to.
   */
  business_id: string;
  /**
   * The rule version it comes from.
   */
  rule_version_id: string;
  /**
   * What the business has to do.
   */
  title: string;
  /**
   * When it is due.
   */
  due_at: string;
  /**
   * Whole days between now and the due date.
   */
  days_left: number;
  /**
   * 1 for the first reminder, 2 for the second, and so on.
   */
  reminder_index: number;
}
