// Generated by make contracts from packages/contracts/events. Do not edit.

/**
 * The extractor produced a rule candidate from a parsed document; the candidate itself is read from the store. Producer: pipeline (rule extractor). Consumers: pipeline (review).
 */
export interface RuleCandidateCreated {
  /**
   * The candidate.
   */
  candidate_id: string;
  /**
   * The document it was extracted from.
   */
  document_id: string;
  /**
   * Regulator the document belongs to.
   */
  regulator: string;
  /**
   * Model that produced the candidate.
   */
  model: string;
  /**
   * Prompt reference as name@version.
   */
  prompt_version: string;
  /**
   * Extractor confidence in [0, 1].
   */
  confidence: number;
  /**
   * Citations that verified against the clause text.
   */
  citation_count: number;
  /**
   * True when the confidence is below the review threshold or a check failed.
   */
  needs_review: boolean;
}
