// Generated by make contracts from packages/contracts/events. Do not edit.

/**
 * An analyst rejected a rule candidate the pipeline extracted: before drafting it, or after drafting it into a rule version that their review then refused. No rule changes: the candidate is closed with the reason, and a draft made from it stays a draft. Producer: rulebook (the decision on a candidate's review task, in the same transaction). Consumers: none yet; the pipeline's operations and the golden export read rejections later.
 */
export interface RuleRejected {
  /**
   * The rejected candidate, as rule.candidate.created named it.
   */
  candidate_id: string;
  /**
   * The document it was extracted from.
   */
  document_id: string;
  /**
   * The regulator of the candidate's review queue, in lower case.
   */
  regulator: string;
  /**
   * Why: not_a_rule, the document states no rule; wrong_extraction, the model read it wrongly; duplicate, another candidate or rule already holds it; out_of_scope, a rule the product does not cover; unparseable, the extraction gave no candidate to draft from.
   */
  reason: "not_a_rule" | "wrong_extraction" | "duplicate" | "out_of_scope" | "unparseable";
  /**
   * The prompt the candidate was extracted with, as name@version.
   */
  prompt_version: string;
  /**
   * The model that produced the candidate.
   */
  model: string;
  /**
   * The draft the candidate became, when it was drafted before the rejection; null when it was rejected before drafting.
   */
  rule_version_id: string | null;
}
