// Generated by make contracts from packages/contracts/events. Do not edit.

/**
 * A published rule version was superseded because a newer version's effective_from passed. Producer: rulebook (scheduled when effective dates pass). Consumers: applicability-engine, obligation, qa.
 */
export interface RuleSuperseded {
  /**
   * The rule.
   */
  rule_id: string;
  /**
   * The version that is now superseded.
   */
  rule_version_id: string;
  /**
   * The version now in force.
   */
  superseded_by_rule_version_id: string;
  /**
   * The day the newer version took over.
   */
  effective_from: string;
}
