// Generated by make contracts from packages/contracts/events. Do not edit.

/**
 * A newer rule version moved the due date of a published version, for one period of a recurring rule or for a one-off rule. Producer: rulebook (when the causing version is published). Consumers: obligation.
 */
export interface RuleDeadlineChanged {
  /**
   * The rule of the version whose deadline changed.
   */
  rule_id: string;
  /**
   * The version whose deadline changed; its obligations are the ones to reschedule.
   */
  rule_version_id: string;
  /**
   * The newer version that changes the deadline.
   */
  caused_by_rule_version_id: string;
  /**
   * The period whose due date moved, as obligations carry it; null for a one-off rule.
   */
  period_label: string | null;
  /**
   * The due date after the change.
   */
  new_due_on: string;
  /**
   * Why the date moved.
   */
  reason: "deadline_extended" | "corrected";
  /**
   * The clause of the causing version's document that states the change.
   */
  evidence_clause_id: string;
}
