// Generated by make contracts from packages/contracts/events. Do not edit.

/**
 * A tenant was created with its first user: a business or a CA firm that signed up, or the internal tenant an operator set up. The first user's user.role.changed (reason created) follows in the same transaction. Producer: identity. Consumers: none yet.
 */
export interface TenantCreated {
  /**
   * What the tenant is: a business, a CA firm, or the internal tenant of the regulatory team.
   */
  kind: "business" | "ca_firm" | "internal";
  /**
   * Where the tenant's data is kept, as a lower-case country code; in (India) is the only region.
   */
  region: string;
  /**
   * The tenant's first user: the person who signed up, or the admin an operator named.
   */
  created_by: string;
  /**
   * When the tenant was created.
   */
  created_at: string;
}
