// Generated by make contracts from packages/contracts/events. Do not edit.

/**
 * A tenant asked for its data to be deleted; every service erases what it holds for the tenant before deadline_at, keeping audit records when retain_audit is true. Producer: identity. Consumers: profile, obligation, notification, qa, applicability-engine, llm-gateway.
 */
export interface TenantDeletionRequested {
  /**
   * User who made the request; null when it came through support.
   */
  requested_by?: string | null;
  /**
   * When the request was recorded.
   */
  requested_at: string;
  /**
   * When the deletion must be complete (30 days after the request).
   */
  deadline_at: string;
  /**
   * True when audit records stay under the documented exception.
   */
  retain_audit: boolean;
  /**
   * Free-text reason given with the request; empty when none.
   */
  reason?: string;
}
