// Generated by make contracts from packages/contracts/events. Do not edit.

/**
 * A role a user holds in their tenant.
 */
export type Role =
  | "owner"
  | "staff"
  | "ca_admin"
  | "ca_staff"
  | "compliance_lead"
  | "analyst"
  | "reviewer"
  | "admin";

/**
 * A user's roles in their tenant changed: the tenant's first user was created, a user was invited, an admin changed a user's roles, or a user was disabled. Each change after creation bumps the user's session version, so the identity service refuses sessions issued before it. Producer: identity. Consumers: none yet.
 */
export interface UserRoleChanged {
  /**
   * The user whose roles changed.
   */
  user_id: string;
  /**
   * The roles the user holds after the change, sorted; empty for a disabled user, who holds none.
   */
  roles: Role[];
  /**
   * The roles the user held before the change, sorted; empty for a user who was just created or invited.
   */
  previous_roles: Role[];
  /**
   * Why the roles changed: the first user of a new tenant, an invitation, an admin's change, or the user being disabled.
   */
  reason: "created" | "invited" | "roles_changed" | "disabled";
  /**
   * The user who made the change; null when no signed-in user made it, as when an operator set up the internal tenant.
   */
  changed_by?: string | null;
  /**
   * The user's session version after the change; the identity service refuses access tokens that carry an older one.
   */
  session_version: number;
}
