"""Generate the event client code from ``packages/contracts/events/schemas``.

Run through ``make contracts``. One ``datamodel-codegen`` call per schema writes a pydantic v2
module into ``clients/python/src/cw_contracts/events``, one ``json2ts`` call per schema writes a
TypeScript declaration into ``clients/typescript/events``, then this script writes the Python
registry and the TypeScript index, removes generated files whose schema is gone, and formats the
output with the repo's ruff and prettier so a regeneration is byte-for-byte stable.

Schemas are called ``<topic>.v<major>.json``; the topic is ``object.verb`` and the module name
replaces the dots with underscores. The envelope is ``envelope.v1.json``.
"""

import json
import re
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Any

REPO = Path(__file__).resolve().parents[3]
CONTRACTS = REPO / "packages" / "contracts"
SCHEMAS = CONTRACTS / "events" / "schemas"
PY_OUT = CONTRACTS / "clients" / "python" / "src" / "cw_contracts" / "events"
TS_OUT = CONTRACTS / "clients" / "typescript" / "events"
SCHEMA_NAME = re.compile(
    r"^(?P<topic>[a-z][a-z0-9_]*(?:\.[a-z][a-z0-9_]*)*)\.v(?P<major>[0-9]+)\.json$"
)
PY_HEADER = '"""Generated by make contracts from packages/contracts/events. Do not edit."""'
TS_HEADER = "// Generated by make contracts from packages/contracts/events. Do not edit."
PRESET = "standard-py312-20260909"
HAND_WRITTEN_PY = {"__init__.py"}


class Schema:
    """One schema file and the names derived from it."""

    def __init__(self, path: Path) -> None:
        match = SCHEMA_NAME.match(path.name)
        if match is None:
            raise SystemExit(f"{path.name}: schema files are called <topic>.v<major>.json")
        self.path = path
        self.topic = match.group("topic")
        self.major = int(match.group("major"))
        self.document: dict[str, Any] = json.loads(path.read_text(encoding="utf-8"))
        version = self.document.get("x-version")
        if not isinstance(version, str) or not re.fullmatch(r"[0-9]+\.[0-9]+\.[0-9]+", version):
            raise SystemExit(f"{path.name}: x-version must be a semver string")
        if int(version.split(".")[0]) != self.major:
            raise SystemExit(f"{path.name}: x-version {version} does not match the file's major")
        self.version = version
        self.is_envelope = self.topic == "envelope"
        tenant_scoped = self.document.get("x-tenant-scoped")
        if not self.is_envelope and not isinstance(tenant_scoped, bool):
            raise SystemExit(f"{path.name}: x-tenant-scoped must be true or false")
        self.tenant_scoped = bool(tenant_scoped)

    @property
    def module(self) -> str:
        return f"{self.topic.replace('.', '_')}_v{self.major}"

    @property
    def class_name(self) -> str:
        words = self.topic.replace(".", "_").split("_")
        base = "".join(word.capitalize() for word in words)
        if self.is_envelope:
            base = "EventEnvelope"
        return f"{base}V{self.major}"

    @property
    def ts_interface(self) -> str:
        """json2ts derives the interface name from the schema title."""
        title = str(self.document["title"])
        return "".join(part.capitalize() for part in re.split(r"[^A-Za-z0-9]+", title) if part)

    @property
    def ts_module(self) -> str:
        return f"{self.topic}.v{self.major}"


def run(*args: str, cwd: Path = REPO) -> None:
    result = subprocess.run(args, cwd=cwd, capture_output=True, text=True, check=False)
    if result.returncode != 0:
        sys.stderr.write(result.stdout + result.stderr)
        raise SystemExit(f"command failed: {' '.join(args)}")


def generate_python(schema: Schema) -> None:
    run(
        "datamodel-codegen",
        "--input",
        str(schema.path),
        "--input-file-type",
        "jsonschema",
        "--output",
        str(PY_OUT / f"{schema.module}.py"),
        "--class-name",
        schema.class_name,
        "--preset",
        PRESET,
        "--disable-timestamp",
        "--use-schema-description",
        "--use-double-quotes",
        "--custom-file-header",
        PY_HEADER,
    )


def generate_typescript(schema: Schema) -> None:
    run(
        "pnpm",
        "--filter",
        "@compliancewatch/contracts",
        "exec",
        "json2ts",
        "--input",
        str(schema.path),
        "--output",
        str(TS_OUT / f"{schema.ts_module}.d.ts"),
        "--bannerComment",
        TS_HEADER,
        "--no-format",
        "--additionalProperties",
        "false",
    )


def write_registry(schemas: list[Schema]) -> None:
    topics = [schema for schema in schemas if not schema.is_envelope]
    envelope = next(schema for schema in schemas if schema.is_envelope)
    lines = [
        PY_HEADER,
        "",
        "from collections.abc import Mapping",
        "from dataclasses import dataclass",
        "from types import MappingProxyType",
        "",
        "from pydantic import BaseModel",
        "",
    ]
    for schema in schemas:
        lines.append(f"from cw_contracts.events.{schema.module} import {schema.class_name}")
    lines += [
        "",
        f'ENVELOPE_VERSION = "{envelope.version}"',
        "",
        "",
        "@dataclass(frozen=True, slots=True)",
        "class TopicSpec:",
        '    """A topic, the payload schema version its model follows, and its tenant scoping."""',
        "",
        "    topic: str",
        "    version: str",
        "    model: type[BaseModel]",
        "    tenant_scoped: bool",
        "    schema_file: str",
        "",
        "",
        "TOPICS: Mapping[str, TopicSpec] = MappingProxyType(",
        "    {",
    ]
    for schema in topics:
        lines += [
            f'        "{schema.topic}": TopicSpec(',
            f'            topic="{schema.topic}",',
            f'            version="{schema.version}",',
            f"            model={schema.class_name},",
            f"            tenant_scoped={schema.tenant_scoped},",
            f'            schema_file="{schema.path.name}",',
            "        ),",
        ]
    lines += ["    }", ")", '"""Every topic with a schema, keyed by topic name."""', ""]
    (PY_OUT / "registry.py").write_text("\n".join(lines), encoding="utf-8")


def write_index(schemas: list[Schema]) -> None:
    topics = [schema for schema in schemas if not schema.is_envelope]
    envelope = next(schema for schema in schemas if schema.is_envelope)
    lines = [TS_HEADER, ""]
    for schema in schemas:
        lines.append(f'export type {{ {schema.ts_interface} }} from "./{schema.ts_module}";')
    lines += [
        "",
        f'export const ENVELOPE_VERSION = "{envelope.version}";',
        "",
        "export const EVENT_TOPICS = {",
    ]
    for schema in topics:
        scoped = "true" if schema.tenant_scoped else "false"
        lines.append(
            f'  "{schema.topic}": {{ version: "{schema.version}", tenantScoped: {scoped} }},'
        )
    lines += ["} as const;", "", "export type EventTopic = keyof typeof EVENT_TOPICS;", ""]
    (TS_OUT / "index.ts").write_text("\n".join(lines), encoding="utf-8")


def remove_stale(schemas: list[Schema]) -> None:
    keep_py = {f"{schema.module}.py" for schema in schemas} | {"registry.py"} | HAND_WRITTEN_PY
    for path in PY_OUT.glob("*.py"):
        if path.name not in keep_py:
            path.unlink()
    keep_ts = {f"{schema.ts_module}.d.ts" for schema in schemas} | {"index.ts"}
    for path in TS_OUT.glob("*.ts"):
        if path.name not in keep_ts:
            path.unlink()


def main() -> None:
    for tool in ("datamodel-codegen", "pnpm"):
        if shutil.which(tool) is None:
            raise SystemExit(f"{tool} is not on PATH; run through `make contracts`")
    schemas = sorted((Schema(path) for path in SCHEMAS.glob("*.json")), key=lambda s: s.topic)
    if not any(schema.is_envelope for schema in schemas):
        raise SystemExit("envelope.v1.json is missing")
    PY_OUT.mkdir(parents=True, exist_ok=True)
    TS_OUT.mkdir(parents=True, exist_ok=True)
    for schema in schemas:
        generate_python(schema)
        generate_typescript(schema)
    write_registry(schemas)
    write_index(schemas)
    remove_stale(schemas)
    run("ruff", "format", str(PY_OUT))
    run("ruff", "check", "--fix", str(PY_OUT))
    run("pnpm", "exec", "prettier", "--write", str(TS_OUT))
    py_out = PY_OUT.relative_to(REPO)
    ts_out = TS_OUT.relative_to(REPO)
    sys.stdout.write(f"generated {len(schemas)} schemas into {py_out} and {ts_out}\n")


if __name__ == "__main__":
    main()
