"""Generate the Python REST client models from the OpenAPI specs listed in ``openapi/clients.json``.

Run through ``make contracts`` (and ``make openapi-public``). The manifest is opt-in: its
``python`` list names the specs, as ``<name>`` for ``openapi/<name>.v1.json``, that get a module
of pydantic v2 models in ``clients/python/src/cw_contracts/rest/<name>_v1.py``, one model per
component schema of the spec. Today that is the public API spec alone. The TypeScript types are
not generated here: the web app generates them from every committed spec.

One ``datamodel-codegen --input-file-type openapi`` call per spec writes the module, whose
docstring names the spec and its ``info.version``. The script then removes generated modules
whose spec left the manifest and formats the output with the repo's ruff, so a regeneration is
byte-for-byte stable.
"""

import argparse
import json
import re
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Any

REPO = Path(__file__).resolve().parents[3]
CONTRACTS = REPO / "packages" / "contracts"
OPENAPI_DIR = CONTRACTS / "openapi"
MANIFEST = "clients.json"
PY_OUT = CONTRACTS / "clients" / "python" / "src" / "cw_contracts" / "rest"
NAME = re.compile(r"[a-z0-9][a-z0-9-]*")
PRESET = "standard-py312-20260909"
HAND_WRITTEN_PY = {"__init__.py"}


def run(*args: str, cwd: Path = REPO) -> None:
    result = subprocess.run(args, cwd=cwd, capture_output=True, text=True, check=False)
    if result.returncode != 0:
        sys.stderr.write(result.stdout + result.stderr)
        raise SystemExit(f"command failed: {' '.join(args)}")


def module_name(name: str) -> str:
    return f"{name.replace('-', '_')}_v1"


def python_specs(directory: Path) -> list[tuple[str, Path, str]]:
    """``(name, spec path, info.version)`` for each spec the manifest lists for Python."""
    path = directory / MANIFEST
    try:
        manifest: Any = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, ValueError) as error:
        raise SystemExit(f"{MANIFEST}: cannot be read: {error}") from error
    names = manifest.get("python") if isinstance(manifest, dict) else None
    if not isinstance(names, list) or not all(isinstance(name, str) for name in names):
        raise SystemExit(f'{MANIFEST}: expected {{"python": ["<spec name>", ...]}}')
    if len(set(names)) != len(names) or names != sorted(names):
        raise SystemExit(f"{MANIFEST}: list each spec once, sorted by name")
    specs: list[tuple[str, Path, str]] = []
    for name in names:
        spec = directory / f"{name}.v1.json"
        if not NAME.fullmatch(name) or not spec.is_file():
            raise SystemExit(f"{MANIFEST}: {name!r} names no spec in {directory.name}/")
        document = json.loads(spec.read_text(encoding="utf-8"))
        version = document.get("info", {}).get("version")
        if not isinstance(version, str):
            raise SystemExit(f"{spec.name}: info.version is missing")
        specs.append((name, spec, version))
    return specs


def generate(name: str, spec: Path, version: str) -> None:
    source = spec.relative_to(REPO) if spec.is_relative_to(REPO) else spec
    header = f'"""Generated by make contracts from {source} (version {version}). Do not edit."""'
    run(
        "datamodel-codegen",
        "--input",
        str(spec),
        "--input-file-type",
        "openapi",
        "--output",
        str(PY_OUT / f"{module_name(name)}.py"),
        "--preset",
        PRESET,
        "--disable-timestamp",
        "--use-schema-description",
        "--use-double-quotes",
        "--custom-file-header",
        header,
    )


def remove_stale(names: list[str]) -> None:
    keep = {f"{module_name(name)}.py" for name in names} | HAND_WRITTEN_PY
    for path in PY_OUT.glob("*.py"):
        if path.name not in keep:
            path.unlink()


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--openapi-dir", type=Path, default=OPENAPI_DIR)
    args = parser.parse_args(argv)
    specs = python_specs(args.openapi_dir)
    if shutil.which("datamodel-codegen") is None:
        raise SystemExit("datamodel-codegen is not on PATH; run through `make contracts`")
    PY_OUT.mkdir(parents=True, exist_ok=True)
    for name, spec, version in specs:
        generate(name, spec, version)
    remove_stale([name for name, _, _ in specs])
    run("ruff", "format", str(PY_OUT))
    run("ruff", "check", "--fix", str(PY_OUT))
    names = ", ".join(name for name, _, _ in specs) or "no specs"
    sys.stdout.write(f"generated the REST models of {names} into {PY_OUT.relative_to(REPO)}\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
