import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { format, resolveConfig } from "prettier";
import { ownerLabel } from "../src/entities/screen/mappers.ts";
import { ROLES } from "../src/shared/config/roles.ts";
import { SCREENS } from "../src/shared/config/screens.ts";
import type { AwaitedRoute, Screen, ScreenSection } from "../src/shared/config/screens.ts";
import { HTTP_METHODS, SERVICES_WITH_SPECS, routeKey } from "../src/shared/config/services.ts";
import type { RouteRef, ServiceName } from "../src/shared/config/services.ts";

/**
 * Renders docs/web/screens.md from the screen registry: one table per section, one row per
 * entry, and a role-by-screen matrix. Runs under plain Node (the registry uses explicit ".ts"
 * relative imports) and ends with prettier, so the committed file is what `prettier --write`
 * would leave. Modes:
 *
 *   node scripts/screens-doc.mts          write docs/web/screens.md
 *   node scripts/screens-doc.mts --check  exit 1 when the committed file differs
 *   node scripts/screens-doc.mts --audit  list awaited routes absent from the committed specs,
 *                                         then the ready entries
 *
 * src/test/screens-doc.test.ts performs the same comparison as --check, so `pnpm test` catches
 * drift without another CI step.
 */
const SCRIPT_DIR = dirname(fileURLToPath(import.meta.url));
export const REPO_ROOT = resolve(SCRIPT_DIR, "../../..");
export const OUTPUT_PATH = join(REPO_ROOT, "docs/web/screens.md");
export const SPEC_DIR = join(REPO_ROOT, "packages/contracts/openapi");

const SECTIONS: readonly { key: ScreenSection; heading: string }[] = [
  { key: "system", heading: "System" },
  { key: "owner", heading: "Owner and staff" },
  { key: "ca", heading: "CA firm" },
  { key: "account", heading: "Account" },
  { key: "admin", heading: "Internal tools" },
];

const cell = (text: string): string => text.replace(/\|/g, "\\|").replace(/\n/g, " ");
const code = (text: string): string => `\`${text}\``;

export function rolesCell(screen: Screen): string {
  const roles = screen.roles === "public" ? "public" : screen.roles.join(", ");
  return screen.flag === undefined ? roles : `${roles}; flag ${code(screen.flag)}`;
}

/** "services track, WP14", "KAG track, path unconfirmed", "not scheduled; indicative path". */
export function ownerCell(item: {
  owner: AwaitedRoute["owner"];
  ref?: string;
  unconfirmed?: true;
}): string {
  const parts = [ownerLabel(item.owner)];
  if (item.ref !== undefined) parts.push(item.ref);
  if (item.unconfirmed === true) parts.push("path unconfirmed");
  return parts.join(item.owner === "unplanned" ? "; " : ", ");
}

export function waitsForCell(screen: Screen): string {
  const routes = screen.awaits.map(
    (route) => `${code(`${route.method} ${route.path}`)} (${ownerCell(route)})`,
  );
  const files = (screen.awaitsFiles ?? []).map(
    (file) => `${code(`file ${file.path}`)} (${ownerCell(file)})`,
  );
  return [...routes, ...files].join("; ");
}

function countBy(screens: readonly Screen[], status: Screen["status"]): number {
  return screens.filter((screen) => screen.status === status).length;
}

function sectionTable(screens: readonly Screen[]): string[] {
  const lines = [
    "| Id | Route | Title | Kind | Roles | Status | Waits for | Guide |",
    "| --- | --- | --- | --- | --- | --- | --- | --- |",
  ];
  for (const screen of screens) {
    lines.push(
      `| ${[
        code(screen.id),
        code(screen.route),
        cell(screen.title),
        screen.kind,
        cell(rolesCell(screen)),
        screen.status,
        waitsForCell(screen),
        cell(screen.guideRef),
      ].join(" | ")} |`,
    );
  }
  return lines;
}

function roleMatrix(screens: readonly Screen[]): string[] {
  const header = ["Id", "Public", ...ROLES];
  const lines = [`| ${header.join(" | ")} |`, `| ${header.map(() => "---").join(" | ")} |`];
  for (const screen of screens) {
    const marks = ROLES.map((role) =>
      screen.roles !== "public" && screen.roles.includes(role) ? "x" : "",
    );
    const isPublic = screen.roles === "public" ? "x" : "";
    lines.push(`| ${[code(screen.id), isPublic, ...marks].join(" | ")} |`);
  }
  return lines;
}

/** The markdown before formatting. */
export function renderScreensDoc(screens: readonly Screen[] = SCREENS): string {
  const lines: string[] = [
    "# Screens",
    "",
    "Generated by `pnpm --filter web screens:gen` from `apps/web/src/shared/config/screens.ts`.",
    "Do not edit by hand: `pnpm --filter web screens:check` (also `make web-screens-check`, part",
    "of `make check`) and the vitest test `src/test/screens-doc.test.ts` fail when this file and",
    "the registry differ.",
    "",
    `${screens.length} entries: ${countBy(screens, "live")} live, ${countBy(screens, "ready")} ready, ${countBy(screens, "waiting")} waiting, ${countBy(screens, "planned")} planned.`,
    "",
    "A screen moves through the statuses in the order planned, waiting, ready, live.",
    "",
    "- **live**: the page or handler exists and every route it calls is in a committed OpenAPI",
    "  spec (`packages/contracts/openapi`).",
    "- **ready**: every awaited route and file is on `main` and each awaited route is also in",
    "  `uses`, but the screen is not built; the entry has no page file and the catch-all routes",
    '  render the "not available yet" notice saying the backend is on `main`.',
    "- **waiting**: at least one awaited route or file is absent; the entry has no page file and",
    '  the catch-all routes render the "not available yet" notice with what it waits for.',
    "- **planned**: nobody has scheduled the backend; the awaited paths are indicative.",
    "",
    "Kind: a `page` owns a route; a `handler` is a route handler; a `component` or `capability`",
    "is embedded in the page named by its route. Roles are the registry's role ids (see",
    "`shared/config/roles.ts`); `public` needs no session. A flag names the feature flag that",
    "hides the screen while it is off. Guide numbers refer to the Project Foundation guide.",
    "",
  ];
  for (const section of SECTIONS) {
    const entries = screens.filter((screen) => screen.section === section.key);
    if (entries.length === 0) continue;
    lines.push(`## ${section.heading}`, "", ...sectionTable(entries), "");
  }
  lines.push(
    "## Roles by screen",
    "",
    "An `x` marks a role that may open the screen; a public screen needs no session.",
    "",
    ...roleMatrix(screens),
    "",
  );
  return lines.join("\n");
}

/** The markdown as prettier formats it with the repository's configuration. */
export async function formatScreensDoc(markdown: string): Promise<string> {
  const options = (await resolveConfig(OUTPUT_PATH)) ?? {};
  return format(markdown, { ...options, parser: "markdown" });
}

interface OpenApiDocument {
  paths: Record<string, Record<string, unknown>>;
}

/** Every "service METHOD path" the committed specs offer; a service without a spec is absent. */
export function committedRoutes(specDir: string = SPEC_DIR): Set<string> {
  const keys = new Set<string>();
  for (const service of SERVICES_WITH_SPECS) {
    const file = join(specDir, `${service}.v1.json`);
    if (!existsSync(file)) continue;
    const spec = JSON.parse(readFileSync(file, "utf8")) as OpenApiDocument;
    for (const [path, operations] of Object.entries(spec.paths)) {
      for (const method of Object.keys(operations)) {
        const upper = method.toUpperCase();
        if ((HTTP_METHODS as readonly string[]).includes(upper)) {
          keys.add(routeKey({ service, method: upper as RouteRef["method"], path }));
        }
      }
    }
  }
  return keys;
}

export interface AuditRow {
  screenId: string;
  service: ServiceName;
  method: string;
  path: string;
  owner: string;
  unconfirmed: boolean;
  /** False when the service has no committed spec at all. */
  specExists: boolean;
}

/**
 * Awaited routes that are not in a committed spec. Those whose service has a spec are the
 * interesting ones: either the route has not landed, or it landed under a different path
 * (the KAG-track paths are unconfirmed until its specs are committed).
 */
export function auditAwaits(
  screens: readonly Screen[] = SCREENS,
  committed: Set<string> = committedRoutes(),
): AuditRow[] {
  const rows: AuditRow[] = [];
  for (const screen of screens) {
    for (const route of screen.awaits) {
      if (committed.has(routeKey(route))) continue;
      rows.push({
        screenId: screen.id,
        service: route.service,
        method: route.method,
        path: route.path,
        owner: ownerCell(route),
        unconfirmed: route.unconfirmed === true,
        specExists: SERVICES_WITH_SPECS.includes(route.service),
      });
    }
  }
  return rows.sort(
    (a, b) =>
      a.service.localeCompare(b.service) ||
      a.path.localeCompare(b.path) ||
      a.method.localeCompare(b.method),
  );
}

export interface ReadyRow {
  screenId: string;
  /** The awaited routes and files, all present, then the routes it only uses. */
  items: string[];
}

/** The ready entries: every awaited route and file is on main and the screen is not built. */
export function readyEntries(screens: readonly Screen[] = SCREENS): ReadyRow[] {
  return screens
    .filter((screen) => screen.status === "ready")
    .map((screen) => {
      const awaited = [
        ...screen.awaits.map((route) => `${route.method} ${route.path}`),
        ...(screen.awaitsFiles ?? []).map((file) => `file ${file.path}`),
      ];
      const used = screen.uses
        .map((route) => `${route.method} ${route.path}`)
        .filter((item) => !awaited.includes(item));
      return { screenId: screen.id, items: [...awaited, ...used] };
    })
    .sort((a, b) => a.screenId.localeCompare(b.screenId));
}

export function renderAudit(rows: readonly AuditRow[], ready: readonly ReadyRow[] = []): string {
  const lines: string[] = [];
  const withSpec = rows.filter((row) => row.specExists);
  const withoutSpec = rows.filter((row) => !row.specExists);
  lines.push(
    `${withSpec.length} awaited routes are absent from a committed spec of their service` +
      ` (${withSpec.filter((row) => row.unconfirmed).length} with an unconfirmed path):`,
  );
  for (const row of withSpec) {
    const mark = row.unconfirmed ? " [unconfirmed]" : "";
    lines.push(
      `  ${row.service} ${row.method} ${row.path} <- ${row.screenId} (${row.owner})${mark}`,
    );
  }
  const services = [...new Set(withoutSpec.map((row) => row.service))].sort();
  lines.push(
    `${withoutSpec.length} awaited routes belong to services without a committed spec` +
      (services.length === 0 ? "." : ` (${services.join(", ")}).`),
  );
  lines.push(
    `${ready.length} entries are ready: the backend is on main and the screen is not built` +
      (ready.length === 0 ? "." : ":"),
  );
  for (const row of ready) {
    lines.push(`  ${row.screenId} ready: ${row.items.join("; ")}`);
  }
  return lines.join("\n");
}

function relativeOutput(): string {
  return OUTPUT_PATH.slice(REPO_ROOT.length + 1);
}

export async function main(argv: readonly string[] = process.argv.slice(2)): Promise<number> {
  const mode = argv[0] ?? "--write";
  if (mode === "--audit") {
    console.log(renderAudit(auditAwaits(), readyEntries()));
    return 0;
  }
  const expected = await formatScreensDoc(renderScreensDoc());
  if (mode === "--check") {
    const actual = existsSync(OUTPUT_PATH) ? readFileSync(OUTPUT_PATH, "utf8") : null;
    if (actual === expected) {
      console.log(`${relativeOutput()} matches the screen registry`);
      return 0;
    }
    console.error(
      `${relativeOutput()} ${actual === null ? "is missing" : "differs from the screen registry"};` +
        " run: pnpm --filter web screens:gen",
    );
    return 1;
  }
  if (mode !== "--write") {
    console.error(`unknown option ${mode}; use --check, --audit or no option`);
    return 2;
  }
  mkdirSync(dirname(OUTPUT_PATH), { recursive: true });
  writeFileSync(OUTPUT_PATH, expected);
  console.log(`wrote ${relativeOutput()} (${SCREENS.length} entries)`);
  return 0;
}

const isMain =
  process.argv[1] !== undefined && resolve(process.argv[1]) === fileURLToPath(import.meta.url);

if (isMain) {
  main().then(
    (status) => {
      process.exitCode = status;
    },
    (error: unknown) => {
      console.error(error);
      process.exitCode = 1;
    },
  );
}
