"""The generated REST models match the public spec: one model per schema, the same fields and
required fields, tolerant responses and strict requests."""

import json
import subprocess
import sys
from enum import StrEnum
from pathlib import Path
from typing import Any
from uuid import uuid4

import pytest
from pydantic import BaseModel, RootModel, ValidationError

from cw_contracts.rest import public_v1

CONTRACTS = Path(__file__).resolve().parents[4]
SCRIPT = CONTRACTS / "scripts" / "generate_rest.py"
OPENAPI = CONTRACTS / "openapi"
PUBLIC = json.loads((OPENAPI / "public.v1.json").read_text(encoding="utf-8"))
META = json.loads((OPENAPI / "public.meta.json").read_text(encoding="utf-8"))
SCHEMAS: dict[str, dict[str, Any]] = PUBLIC["components"]["schemas"]
OBJECTS = sorted(name for name, schema in SCHEMAS.items() if "properties" in schema)


def generated(name: str) -> type:
    """The generated class of a schema: datamodel-codegen drops the underscores of a name."""
    found = getattr(public_v1, name.replace("_", ""))
    assert isinstance(found, type)
    return found


def model_for(name: str) -> type[BaseModel]:
    model = generated(name)
    assert issubclass(model, BaseModel)
    return model


def test_the_manifest_lists_the_public_spec() -> None:
    manifest = json.loads((OPENAPI / "clients.json").read_text(encoding="utf-8"))
    assert manifest == {"python": ["public"]}


def test_the_module_names_the_spec_version_it_was_generated_from() -> None:
    version = META["info"]["version"]
    assert public_v1.__doc__ == (
        "Generated by make contracts from packages/contracts/openapi/public.v1.json"
        f" (version {version}). Do not edit."
    )


@pytest.mark.parametrize("name", sorted(SCHEMAS))
def test_every_schema_has_a_model_or_an_enum(name: str) -> None:
    schema, found = SCHEMAS[name], generated(name)
    if "enum" in schema:
        assert issubclass(found, StrEnum)
        assert [member.value for member in found] == schema["enum"]
    else:
        assert issubclass(found, BaseModel)


@pytest.mark.parametrize("name", OBJECTS)
def test_each_model_has_the_fields_and_required_fields_of_its_schema(name: str) -> None:
    schema, model = SCHEMAS[name], model_for(name)
    assert set(model.model_fields) == set(schema["properties"])
    required = {field for field, info in model.model_fields.items() if info.is_required()}
    assert required == set(schema.get("required", []))


def request_bodies() -> set[str]:
    names = set()
    for item in PUBLIC["paths"].values():
        for operation in item.values():
            body = operation.get("requestBody", {}).get("content", {}).get("application/json")
            if body:
                names.add(body["schema"]["$ref"].rsplit("/", 1)[-1])
    return names


def test_request_models_refuse_unknown_fields_and_responses_ignore_them() -> None:
    assert request_bodies() == {
        "AskIn",
        "AssigneeIn",
        "BulkNotificationIn",
        "BusinessIn",
        "BusinessPatchIn",
        "CommentIn",
        "RegistrationAddIn",
        "StatusIn",
    }
    with pytest.raises(ValidationError):
        public_v1.BusinessPatchIn.model_validate({"name": "Acme", "added_later": True})
    with pytest.raises(ValidationError):
        public_v1.StatusIn.model_validate({"action": "start", "added_later": True})
    summary = public_v1.BusinessSummaryOut.model_validate(
        {
            "id": str(uuid4()),
            "name": "Acme",
            "pan": "ABCDE1234F",
            "gstins": [],
            "updated_at": "2026-09-29T10:00:00+05:30",
            "added_later": "ignored",
        }
    )
    assert "added_later" not in summary.model_dump()


def test_a_problem_parses_with_its_validation_issues() -> None:
    problem = public_v1.Problem.model_validate(
        {
            "type": "urn:compliancewatch:problem:request-validation",
            "title": "Request is invalid",
            "status": 422,
            "errors": [{"loc": ["body", "name"], "msg": "Field required", "type": "missing"}],
        }
    )
    assert problem.errors is not None
    assert problem.errors[0].loc == ["body", "name"]


def test_constrained_request_values_are_checked_on_the_client() -> None:
    with pytest.raises(ValidationError):
        public_v1.AnswerIn.model_validate({"key": "Not A Key", "value": 1})
    gstin = public_v1.Gstin("29ABCDE1234F1Z5")
    assert isinstance(gstin, RootModel)
    body = public_v1.BusinessIn(name="Acme", gstin=gstin)
    assert body.model_dump(mode="json", exclude_none=True) == {
        "name": "Acme",
        "gstin": "29ABCDE1234F1Z5",
        "registration_name": "",
    }


# ---- the generator's manifest ------------------------------------------------------------------


def generate(directory: Path) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        [sys.executable, str(SCRIPT), "--openapi-dir", str(directory)],
        capture_output=True,
        text=True,
        check=False,
    )


@pytest.mark.parametrize(
    ("manifest", "message"),
    [
        ('{"python": "public"}', 'expected {"python": ["<spec name>", ...]}'),
        ('{"python": ["public", "public"]}', "list each spec once, sorted by name"),
        ('{"python": ["zeta", "alpha"]}', "list each spec once, sorted by name"),
        ('{"python": ["missing"]}', "'missing' names no spec"),
        ("not json", "cannot be read"),
    ],
)
def test_a_bad_manifest_fails_before_anything_is_generated(
    tmp_path: Path, manifest: str, message: str
) -> None:
    (tmp_path / "clients.json").write_text(manifest)
    result = generate(tmp_path)
    assert result.returncode == 1
    assert message in result.stderr
