"""Generated by make contracts from packages/contracts/events. Do not edit."""

from __future__ import annotations

from enum import StrEnum
from typing import Annotated
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field


class Result(StrEnum):
    """
    Three-valued outcome.
    """

    applies = "applies"
    not_applicable = "not_applicable"
    unsure = "unsure"


class Trigger(StrEnum):
    """
    What caused the evaluation.
    """

    rule_published = "rule_published"
    profile_updated = "profile_updated"
    manual = "manual"


class ApplicabilityDecidedV1(BaseModel):
    """
    The engine evaluated one rule version against one business profile version. Producer: applicability-engine. Consumers: obligation.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    decision_id: Annotated[UUID, Field(description="The stored decision.")]
    business_id: Annotated[UUID, Field(description="The business evaluated.")]
    rule_version_id: Annotated[UUID, Field(description="The rule version evaluated.")]
    result: Annotated[Result, Field(description="Three-valued outcome.")]
    confidence: Annotated[
        float,
        Field(
            description="Confidence in [0, 1]; 1 for fully deterministic evaluations.",
            ge=0.0,
            le=1.0,
        ),
    ]
    profile_version: Annotated[
        int, Field(description="Profile version the decision was computed from.", ge=1)
    ]
    decided_at: Annotated[AwareDatetime, Field(description="When the decision was made.")]
    needs_review: Annotated[
        bool,
        Field(
            description="True when the result is unsure or the confidence is below the review threshold."
        ),
    ]
    trigger: Annotated[Trigger, Field(description="What caused the evaluation.")]
