"""Generated by make contracts from packages/contracts/events. Do not edit."""

from __future__ import annotations

from datetime import date
from enum import StrEnum
from typing import Annotated
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field, RootModel


class DocType(StrEnum):
    """
    Document type decided by the detector.
    """

    notification = "notification"
    circular = "circular"
    press_release = "press_release"
    act_amendment = "act_amendment"


class ClauseRef(RootModel[str]):
    root: Annotated[str, Field(min_length=1)]


class DocumentParsedV1(BaseModel):
    """
    The parser split a classified document into clauses with stable references; clause text is read from the store, not carried here. Producer: pipeline (document parser). Consumers: pipeline (rule extractor), rulebook.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    document_id: Annotated[UUID, Field(description="The parsed document.")]
    source_id: Annotated[UUID, Field(description="The source it came from.")]
    doc_type: Annotated[DocType, Field(description="Document type decided by the detector.")]
    title: Annotated[str, Field(description="Title of the document.", min_length=1)]
    language: Annotated[
        str,
        Field(
            description="Primary language of the text, as a BCP 47 tag such as en or hi.",
            min_length=1,
        ),
    ]
    published_at: Annotated[
        date | None, Field(description="Publication date; null when unknown.")
    ] = None
    clause_count: Annotated[int, Field(description="Number of clauses produced.", ge=1)]
    clause_refs: Annotated[
        list[ClauseRef],
        Field(description="Stable clause references, in document order.", min_length=1),
    ]
    parser_version: Annotated[
        str,
        Field(description="Version of the parser that produced the clauses.", min_length=1),
    ]
