"""Generated by make contracts from packages/contracts/events. Do not edit."""

from __future__ import annotations

from datetime import date
from enum import StrEnum
from typing import Annotated
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field, RootModel


class DocType(StrEnum):
    """
    Document type: the source's, or the one the uploader gave. A statute (an Act or the Rules under it) is registered and embedded but nothing is extracted from it.
    """

    notification = "notification"
    circular = "circular"
    press_release = "press_release"
    act_amendment = "act_amendment"
    statute = "statute"


class ClauseRef(RootModel[str]):
    root: Annotated[str, Field(min_length=1)]


class DocumentParsedV1(BaseModel):
    """
    The pipeline parsed a stored document into clauses with stable references, the first time or with another parser. Clause text is not carried here: read it from the rulebook once the document is registered (GET /v1/rulebook/documents/{document_id}). Producer: pipeline (the ingest's parse). Consumers: none yet; the rulebook once registration moves to events (ADR-018).
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    document_id: Annotated[UUID, Field(description="The parsed document.")]
    source_id: Annotated[UUID, Field(description="The source it came from.")]
    doc_type: Annotated[
        DocType,
        Field(
            description="Document type: the source's, or the one the uploader gave. A statute (an Act or the Rules under it) is registered and embedded but nothing is extracted from it."
        ),
    ]
    title: Annotated[str, Field(description="Title of the document.", min_length=1)]
    language: Annotated[
        str,
        Field(
            description="Primary language of the text, as a BCP 47 tag such as en or hi.",
            min_length=1,
        ),
    ]
    published_at: Annotated[
        date | None, Field(description="Publication date; null when unknown.")
    ] = None
    clause_count: Annotated[int, Field(description="Number of clauses produced.", ge=1)]
    clause_refs: Annotated[
        list[ClauseRef],
        Field(description="Stable clause references, in document order.", min_length=1),
    ]
    parser_version: Annotated[
        str,
        Field(
            description="The parser that produced the clauses, as name@version: pdf@1, pdf-tables@1, html@1, html-tables@1, or manual@1 for an analyst's transcript.",
            min_length=1,
        ),
    ]
