"""Generated by make contracts from packages/contracts/events. Do not edit."""

from __future__ import annotations

from enum import StrEnum
from typing import Annotated
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field


class Channel(StrEnum):
    """
    Delivery channel.
    """

    whatsapp = "whatsapp"
    email = "email"


class NotificationSentV1(BaseModel):
    """
    A channel accepted a notification for delivery. Producer: notification. Consumers: obligation (audit), eval.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    notification_id: Annotated[UUID, Field(description="The notification.")]
    obligation_id: Annotated[UUID, Field(description="The obligation it is about.")]
    business_id: Annotated[UUID, Field(description="The business it was sent for.")]
    channel: Annotated[Channel, Field(description="Delivery channel.")]
    dedupe_key: Annotated[
        str,
        Field(
            description="Idempotency key over rule version, business and channel.",
            pattern="^[0-9a-f]{64}$",
        ),
    ]
    provider_message_id: Annotated[
        str | None,
        Field(description="The provider's id for the message; empty when it gives none."),
    ] = None
    sent_at: Annotated[AwareDatetime, Field(description="When the channel accepted it.")]
    language: Annotated[
        str, Field(description="Language the message was rendered in.", min_length=1)
    ]
