"""Generated by make contracts from packages/contracts/events. Do not edit."""

from __future__ import annotations

from enum import StrEnum
from typing import Annotated
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field


class Channel(StrEnum):
    """
    Delivery channel that failed.
    """

    whatsapp = "whatsapp"
    email = "email"


class NotificationFailedV1(BaseModel):
    """
    A channel refused or failed to deliver a notification; will_retry says whether another attempt or channel follows. Producer: notification. Consumers: obligation (audit).
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    notification_id: Annotated[UUID, Field(description="The notification.")]
    obligation_id: Annotated[UUID, Field(description="The obligation it is about.")]
    business_id: Annotated[UUID, Field(description="The business it was sent for.")]
    channel: Annotated[Channel, Field(description="Delivery channel that failed.")]
    dedupe_key: Annotated[
        str,
        Field(
            description="Idempotency key over rule version, business and channel.",
            pattern="^[0-9a-f]{64}$",
        ),
    ]
    error: Annotated[str, Field(description="What the channel reported.", min_length=1)]
    attempts: Annotated[int, Field(description="Attempts made on this channel so far.", ge=1)]
    will_retry: Annotated[
        bool,
        Field(description="True when another attempt or the fallback channel is scheduled."),
    ]
    failed_at: Annotated[AwareDatetime, Field(description="When the failure was recorded.")]
