"""Generated by make contracts from packages/contracts/events. Do not edit."""

from __future__ import annotations

from enum import StrEnum
from typing import Annotated
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field


class Status(StrEnum):
    """
    Closing status.
    """

    done = "done"
    waived = "waived"
    closed_not_applicable = "closed_not_applicable"


class Reason(StrEnum):
    """
    Why it was closed.
    """

    profile_changed = "profile_changed"
    rule_withdrawn = "rule_withdrawn"
    rule_superseded = "rule_superseded"
    waived_by_user = "waived_by_user"
    completed = "completed"


class ObligationClosedV1(BaseModel):
    """
    An obligation reached a closed status, by the user or because it no longer applies. Producer: obligation. Consumers: notification.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    obligation_id: Annotated[UUID, Field(description="The obligation.")]
    business_id: Annotated[UUID, Field(description="The business it belongs to.")]
    rule_version_id: Annotated[UUID, Field(description="The rule version it comes from.")]
    status: Annotated[Status, Field(description="Closing status.")]
    reason: Annotated[Reason, Field(description="Why it was closed.")]
    closed_at: Annotated[AwareDatetime, Field(description="When it was closed.")]
    closed_by: Annotated[
        UUID | None, Field(description="User who closed it; null when the system did.")
    ] = None
