"""Generated by make contracts from packages/contracts/events. Do not edit."""

from __future__ import annotations

from typing import Annotated
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field


class ObligationDueSoonV1(BaseModel):
    """
    An open obligation's due date is near and a reminder is warranted. Producer: obligation (reminder scheduler). Consumers: notification.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    obligation_id: Annotated[UUID, Field(description="The obligation.")]
    business_id: Annotated[UUID, Field(description="The business it belongs to.")]
    rule_version_id: Annotated[UUID, Field(description="The rule version it comes from.")]
    title: Annotated[str, Field(description="What the business has to do.", min_length=1)]
    due_at: Annotated[AwareDatetime, Field(description="When it is due.")]
    days_left: Annotated[int, Field(description="Whole days between now and the due date.", ge=0)]
    reminder_index: Annotated[
        int,
        Field(description="1 for the first reminder, 2 for the second, and so on.", ge=1),
    ]
