"""Generated by make contracts from packages/contracts/events. Do not edit."""

from __future__ import annotations

from enum import StrEnum
from typing import Annotated
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field


class Reason(StrEnum):
    """
    Why the date moved.
    """

    deadline_extended = "deadline_extended"
    corrected = "corrected"
    manual = "manual"


class ObligationRescheduledV1(BaseModel):
    """
    An open obligation's due date changed, usually because the regulator extended or corrected a deadline. Producer: obligation. Consumers: notification.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    obligation_id: Annotated[UUID, Field(description="The obligation.")]
    business_id: Annotated[UUID, Field(description="The business it belongs to.")]
    rule_version_id: Annotated[UUID, Field(description="The rule version it comes from.")]
    previous_due_at: Annotated[AwareDatetime, Field(description="Due date before the change.")]
    new_due_at: Annotated[AwareDatetime, Field(description="Due date after the change.")]
    reason: Annotated[Reason, Field(description="Why the date moved.")]
    caused_by_rule_version_id: Annotated[
        UUID | None,
        Field(description="The rule version that changed the deadline; null for a manual change."),
    ] = None
