"""Generated by make contracts from packages/contracts/events. Do not edit."""

from __future__ import annotations

from datetime import date
from typing import Annotated
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field


class RuleWithdrawnV1(BaseModel):
    """
    A published rule version was withdrawn and stops being in force, either by an analyst or because a newer version that withdraws it took effect. Producer: rulebook (on withdrawal, or when the withdrawing version takes effect). Consumers: applicability-engine, obligation, qa.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    rule_id: Annotated[UUID, Field(description="The rule.")]
    rule_version_id: Annotated[UUID, Field(description="The version that is now withdrawn.")]
    withdrawn_by_rule_version_id: Annotated[
        UUID | None,
        Field(
            description="The version that withdraws it; null when an analyst withdrew it directly."
        ),
    ]
    effective_from: Annotated[date, Field(description="The day the withdrawal took effect.")]
