"""Generated by make contracts from packages/contracts/events. Do not edit."""

from __future__ import annotations

from datetime import date
from enum import StrEnum
from typing import Annotated
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field


class Reason(StrEnum):
    """
    Why the date moved.
    """

    deadline_extended = "deadline_extended"
    corrected = "corrected"


class RuleDeadlineChangedV1(BaseModel):
    """
    A newer rule version moved the due date of a published version, for one period of a recurring rule or for a one-off rule. Producer: rulebook (when the causing version is published). Consumers: obligation.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    rule_id: Annotated[UUID, Field(description="The rule of the version whose deadline changed.")]
    rule_version_id: Annotated[
        UUID,
        Field(
            description="The version whose deadline changed; its obligations are the ones to reschedule."
        ),
    ]
    caused_by_rule_version_id: Annotated[
        UUID, Field(description="The newer version that changes the deadline.")
    ]
    period_label: Annotated[
        str | None,
        Field(
            description="The period whose due date moved, as obligations carry it; null for a one-off rule.",
            min_length=1,
        ),
    ]
    new_due_on: Annotated[date, Field(description="The due date after the change.")]
    reason: Annotated[Reason, Field(description="Why the date moved.")]
    evidence_clause_id: Annotated[
        UUID,
        Field(description="The clause of the causing version's document that states the change."),
    ]
