"""Generated by make contracts from packages/contracts/events. Do not edit."""

from __future__ import annotations

from datetime import date
from typing import Annotated
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field


class RuleSupersededV1(BaseModel):
    """
    A published rule version was superseded because a newer version's effective_from passed. Producer: rulebook (scheduled when effective dates pass). Consumers: applicability-engine, obligation, qa.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    rule_id: Annotated[UUID, Field(description="The rule.")]
    rule_version_id: Annotated[UUID, Field(description="The version that is now superseded.")]
    superseded_by_rule_version_id: Annotated[UUID, Field(description="The version now in force.")]
    effective_from: Annotated[date, Field(description="The day the newer version took over.")]
