"""Generated by make contracts from packages/contracts/events. Do not edit."""

from __future__ import annotations

from typing import Annotated
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field


class RuleCandidateCreatedV1(BaseModel):
    """
    The extractor produced a rule candidate from a parsed document; the candidate itself is read from the store. Producer: pipeline (rule extractor). Consumers: pipeline (review).
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    candidate_id: Annotated[UUID, Field(description="The candidate.")]
    document_id: Annotated[UUID, Field(description="The document it was extracted from.")]
    regulator: Annotated[str, Field(description="Regulator the document belongs to.", min_length=1)]
    model: Annotated[str, Field(description="Model that produced the candidate.", min_length=1)]
    prompt_version: Annotated[
        str, Field(description="Prompt reference as name@version.", min_length=1)
    ]
    confidence: Annotated[
        float, Field(description="Extractor confidence in [0, 1].", ge=0.0, le=1.0)
    ]
    citation_count: Annotated[
        int, Field(description="Citations that verified against the clause text.", ge=0)
    ]
    needs_review: Annotated[
        bool,
        Field(
            description="True when the confidence is below the review threshold or a check failed."
        ),
    ]
