"""Generated by make contracts from packages/contracts/events. Do not edit."""

from __future__ import annotations

from enum import StrEnum
from typing import Annotated
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field


class Reason(StrEnum):
    """
    Why the roles changed: the first user of a new tenant, an invitation, an admin's change, or the user being disabled.
    """

    created = "created"
    invited = "invited"
    roles_changed = "roles_changed"
    disabled = "disabled"


class Role(StrEnum):
    """
    A role a user holds in their tenant.
    """

    owner = "owner"
    staff = "staff"
    ca_admin = "ca_admin"
    ca_staff = "ca_staff"
    compliance_lead = "compliance_lead"
    analyst = "analyst"
    reviewer = "reviewer"
    admin = "admin"


class UserRoleChangedV1(BaseModel):
    """
    A user's roles in their tenant changed: the tenant's first user was created, a user was invited, an admin changed a user's roles, or a user was disabled. Each change after creation bumps the user's session version, so the identity service refuses sessions issued before it. Producer: identity. Consumers: none yet.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    user_id: Annotated[UUID, Field(description="The user whose roles changed.")]
    roles: Annotated[
        list[Role],
        Field(
            description="The roles the user holds after the change, sorted; empty for a disabled user, who holds none."
        ),
    ]
    previous_roles: Annotated[
        list[Role],
        Field(
            description="The roles the user held before the change, sorted; empty for a user who was just created or invited."
        ),
    ]
    reason: Annotated[
        Reason,
        Field(
            description="Why the roles changed: the first user of a new tenant, an invitation, an admin's change, or the user being disabled."
        ),
    ]
    changed_by: Annotated[
        UUID | None,
        Field(
            description="The user who made the change; null when no signed-in user made it, as when an operator set up the internal tenant."
        ),
    ] = None
    session_version: Annotated[
        int,
        Field(
            description="The user's session version after the change; the identity service refuses access tokens that carry an older one.",
            ge=0,
        ),
    ]
