// The curated actions, the checks' words and every make target's words of panel_catalog.py
// (agent A's catalog), read statically for the mock, so it shows the same words as the helper.
// Regenerate it when the catalog changes; the real helper always serves panel_catalog.py itself.

export const SNAPSHOT = {
  groups: [
    ["everything", "Everything"],
    ["docker", "Docker and databases"],
    ["services", "Services and the web app"],
    ["product", "The product"],
    ["data", "Data"],
    ["checks", "Checks"],
    ["pipeline", "Pipeline and events"],
    ["flags", "Flags"],
    ["tools", "Tools and files"],
    ["make", "Every make target"],
  ],
  curated: [
    {
      id: "start-everything",
      title: "Start everything",
      summary:
        "Starts Docker, the databases, the ten services and the web app, then opens the web app.",
      what_happens: [
        "Starts Docker (Colima) if it is not running.",
        "Starts the databases and queues: Postgres, Redis, Redpanda and Temporal.",
        "Brings the database up to date (make migrate).",
        "Starts the ten services and waits until each one answers.",
        "Starts the web app and opens it in your browser.",
      ],
      duration: "2 to 4 minutes (longer the first time)",
      group: "everything",
      safety: "changes-data",
      button: "Start",
      confirm:
        "Everything starts. It runs make migrate, which applies this checkout's database changes (migrations) to the shared development database.",
      migrates: true,
    },
    {
      id: "stop-everything",
      title: "Stop everything",
      summary: "Stops the web app, the services, the product and Docker, to free memory.",
      what_happens: [
        "Stops the web app and the ten services.",
        "Stops the product's app, worker and web app.",
        "Stops the workers and relays this app started.",
        "Stops the databases and queues. Their data stays on disk.",
        "Shuts Docker (Colima) down. If it takes longer than 2 minutes, you can force it.",
      ],
      duration: "about 1 minute",
      group: "everything",
      safety: "stops-things",
      button: "Stop",
      confirm: "Everything this checkout runs stops, for every session that uses it.",
      takes: ["docker", "product"],
    },
    {
      id: "docker-start",
      title: "Start Docker",
      summary: "Starts Docker (Colima), the program that runs the databases.",
      what_happens: ["Starts Colima with 4 CPUs and 8 GB of memory, if it is not running already."],
      duration: "about 1 minute",
      group: "docker",
      safety: "safe",
      button: "Start",
    },
    {
      id: "docker-stop",
      title: "Stop Docker",
      summary: "Shuts Docker (Colima) down to free memory. Every container stops with it.",
      what_happens: [
        "Postgres, Redis, Redpanda and Temporal stop, for every session using them.",
        "The data stays in Docker's volumes; it is there again at the next start.",
      ],
      duration: "under 1 minute",
      group: "docker",
      safety: "stops-things",
      button: "Stop",
      confirm: "Docker stops, and every container with it.",
      takes: ["docker"],
    },
    {
      id: "force-stop-docker",
      title: "Force-stop Docker",
      summary:
        "Stops Colima at once when a normal stop hangs. Only use it after Stop Docker timed out.",
      what_happens: [
        "Colima's virtual machine stops immediately, without a clean shutdown.",
        "The databases get no time to close their files. Postgres repairs itself at the next start; anything being written at that moment is lost.",
      ],
      duration: "under 1 minute",
      group: "docker",
      safety: "destructive",
      button: "Force stop",
      confirm: "Colima stops at once, without letting the databases shut down cleanly.",
      takes: ["docker"],
    },
    {
      id: "databases-start",
      title: "Start the databases",
      summary:
        "Starts Postgres, Redis, Redpanda and Temporal in Docker and waits until they are healthy.",
      what_happens: [
        "Runs make dev: creates .env the first time, then starts the containers.",
        "Waits until every container reports healthy.",
      ],
      duration: "about 1 minute",
      group: "docker",
      safety: "safe",
      button: "Start",
      needs: ["docker"],
    },
    {
      id: "databases-stop",
      title: "Stop the databases",
      summary: "Stops the database and queue containers. Their data stays on disk.",
      what_happens: [
        "Runs make dev-down: every container of the dev stack stops; the volumes stay.",
      ],
      duration: "under 1 minute",
      group: "docker",
      safety: "stops-things",
      button: "Stop",
      confirm: "The databases and queues stop, for every session using them.",
      takes: ["docker"],
      needs: ["docker"],
    },
    {
      id: "dev-observability",
      title: "Start the monitoring tools",
      summary:
        "Adds Langfuse, the OpenTelemetry collector, Prometheus, Tempo and Grafana to the stack.",
      what_happens: [
        "Runs make dev-observability: starts the monitoring containers beside the databases.",
      ],
      duration: "1 to 2 minutes",
      group: "docker",
      safety: "safe",
      button: "Start",
      needs: ["docker"],
    },
    {
      id: "dev-llm",
      title: "Start the fake AI model",
      summary:
        "Builds and starts the LLM gateway with the fake provider, so nothing calls a paid model.",
      what_happens: ["Runs make dev-llm: builds the gateway image and starts its container."],
      duration: "1 to 3 minutes",
      group: "docker",
      safety: "safe",
      button: "Start",
      needs: ["docker"],
    },
    {
      id: "dev-flags",
      title: "Start Unleash (feature flags)",
      summary: "Starts Unleash, the feature-flag server, for when flags come from Unleash.",
      what_happens: [
        "Runs make dev-flags: starts Unleash and creates its database the first time.",
      ],
      duration: "about 1 minute",
      group: "docker",
      safety: "safe",
      button: "Start",
      needs: ["docker"],
    },
    {
      id: "dev-ps",
      title: "Show the containers",
      summary: "Lists every container of the dev stack with its state and health.",
      what_happens: ["Runs make dev-ps and shows what it prints. Nothing changes."],
      duration: "a few seconds",
      group: "docker",
      safety: "safe",
      kind: "read",
      button: "Show",
      needs: ["docker"],
    },
    {
      id: "container-logs",
      title: "A container's log",
      summary: "Shows the last 200 lines of one container's log.",
      what_happens: ["Reads the log with docker compose logs. Nothing changes."],
      duration: "a few seconds",
      group: "docker",
      safety: "safe",
      kind: "read",
      button: "Show",
      params: [
        {
          name: "service",
          label: "Container",
          kind: "choice",
          required: true,
          source: "containers",
          help: "Which container.",
        },
      ],
      needs: ["docker"],
    },
    {
      id: "ui-start",
      title: "Start the services",
      summary:
        "Starts the ten services on the shared Postgres, so the web app has an API to talk to.",
      what_happens: [
        "Runs make web-stack STORE=postgres: each service starts in the background.",
        "Waits until every service answers its health check.",
      ],
      duration: "about 1 minute",
      group: "services",
      safety: "safe",
      button: "Start",
      needs: ["docker"],
    },
    {
      id: "ui-stop",
      title: "Stop the services",
      summary:
        "Stops the ten services this checkout started (and the web app, if the stack started it).",
      what_happens: ["Runs make web-stack-down: stops only the processes its pid files name."],
      duration: "a few seconds",
      group: "services",
      safety: "stops-things",
      button: "Stop",
      confirm: "The ten services stop.",
    },
    {
      id: "ui-restart",
      title: "Restart the services",
      summary: "Stops and starts the ten services again, for example after you changed their code.",
      what_happens: [
        "Stops the services (make web-stack-down).",
        "Starts them again on Postgres and waits until each one answers.",
      ],
      duration: "about 1 minute",
      group: "services",
      safety: "stops-things",
      button: "Restart",
      confirm: "The ten services stop, then start again.",
      needs: ["docker"],
    },
    {
      id: "ui-wait",
      title: "Wait for the services",
      summary: "Waits until every service answers its health check.",
      what_happens: ["Runs make web-stack-wait. Nothing changes."],
      duration: "up to 1 minute",
      group: "services",
      safety: "safe",
      button: "Wait",
    },
    {
      id: "web-start",
      title: "Start the web app",
      summary: "Starts the ComplianceWatch web app on port 3000.",
      what_happens: ["Starts next dev in the background and waits until the page answers."],
      duration: "20 to 60 seconds",
      group: "services",
      safety: "safe",
      button: "Start",
    },
    {
      id: "web-stop",
      title: "Stop the web app",
      summary: "Stops the web app on port 3000.",
      what_happens: ["Stops exactly the web app processes the confirm names; nothing else."],
      duration: "a few seconds",
      group: "services",
      safety: "stops-things",
      button: "Stop",
      confirm: "The web app stops.",
    },
    {
      id: "worker-start",
      title: "Start a worker",
      summary: "Starts one service's worker: its event consumers, outbox relay and periodic jobs.",
      what_happens: [
        "Runs make worker SERVICE=<service> in the background, with crawling turned off.",
        "Its log goes to var/control-panel.",
      ],
      duration: "a few seconds",
      group: "services",
      safety: "safe",
      button: "Start",
      params: [
        {
          name: "service",
          label: "Service",
          kind: "choice",
          required: true,
          source: "workers",
          help: "A service that has a worker.",
        },
      ],
      needs: ["docker"],
    },
    {
      id: "worker-stop",
      title: "Stop a worker",
      summary: "Stops a worker this app started.",
      what_happens: [
        "Sends it a stop signal, and a forced stop if it is still running after 5 seconds.",
      ],
      duration: "a few seconds",
      group: "services",
      safety: "stops-things",
      button: "Stop",
      params: [
        {
          name: "service",
          label: "Service",
          kind: "choice",
          required: true,
          source: "workers",
          help: "A service that has a worker.",
        },
      ],
      confirm: "The worker stops.",
    },
    {
      id: "relay-start",
      title: "Start an outbox relay",
      summary: "Starts one service's outbox relay, which publishes its saved events to Redpanda.",
      what_happens: ["Runs make relay SERVICE=<service> in the background."],
      duration: "a few seconds",
      group: "services",
      safety: "safe",
      button: "Start",
      params: [
        {
          name: "service",
          label: "Service",
          kind: "choice",
          required: true,
          source: "relays",
          help: "A service that has an outbox relay.",
        },
      ],
      needs: ["docker"],
    },
    {
      id: "relay-stop",
      title: "Stop an outbox relay",
      summary: "Stops a relay this app started.",
      what_happens: [
        "Sends it a stop signal, and a forced stop if it is still running after 5 seconds.",
      ],
      duration: "a few seconds",
      group: "services",
      safety: "stops-things",
      button: "Stop",
      params: [
        {
          name: "service",
          label: "Service",
          kind: "choice",
          required: true,
          source: "relays",
          help: "A service that has an outbox relay.",
        },
      ],
      confirm: "The relay stops.",
    },
    {
      id: "product-start",
      title: "Start the product",
      summary:
        "Starts the whole product: the databases, the app, the worker and its web app on port 3400.",
      what_happens: [
        "Starts Docker and the databases if they are not running.",
        "Brings the database up to date (make migrate) and loads the rulebook's seed calendar.",
        "Starts the product's app, its worker and its web app.",
      ],
      duration: "2 to 5 minutes",
      group: "product",
      safety: "changes-data",
      button: "Start",
      confirm:
        "The product starts. It runs make migrate, which applies this checkout's database changes (migrations) to the shared development database.",
      migrates: true,
    },
    {
      id: "product-stop",
      title: "Stop the product",
      summary: "Stops the product's app, worker and web app. The databases keep running.",
      what_happens: ["Runs make product-down: stops only the processes the product recorded."],
      duration: "a few seconds",
      group: "product",
      safety: "stops-things",
      button: "Stop",
      confirm: "The product's app, worker and web app stop.",
      takes: ["product"],
    },
    {
      id: "product-wait",
      title: "Wait for the product",
      summary: "Waits until the product's app, worker and web app all answer.",
      what_happens: ["Runs make product-wait. Nothing changes."],
      duration: "up to 2 minutes",
      group: "product",
      safety: "safe",
      button: "Wait",
    },
    {
      id: "product-role",
      title: "Refresh the product's database role",
      summary: "Creates or refreshes the database login the product uses under row-level security.",
      what_happens: ["Runs make product-role on the running Postgres."],
      duration: "a few seconds",
      group: "product",
      safety: "changes-data",
      confirm: "The product's database role is created or refreshed.",
      needs: ["docker"],
    },
    {
      id: "product-seed",
      title: "Fill the product with sample data",
      summary:
        "Adds made-up businesses, a sample rule publication and first decisions to the running product.",
      what_happens: ["Runs make product-seed (cw-product seed) against the running product."],
      duration: "about 1 minute",
      group: "product",
      safety: "changes-data",
      button: "Fill",
      confirm: "Sample businesses and a sample publication are added to the product.",
      needs: ["product"],
    },
    {
      id: "product-check",
      title: "Check the product works",
      summary:
        "Proves the running product works, step by step: sign-up, rules, decisions, obligations, notifications.",
      what_happens: [
        "Runs make product-check (cw-product check). Each step says what it proved.",
        "It adds made-up test records to the product as it goes. It never runs the rollback step.",
      ],
      duration: "2 to 5 minutes",
      group: "product",
      safety: "changes-data",
      confirm: "The check adds made-up test records to the running product.",
      params: [
        {
          name: "step",
          label: "Step",
          kind: "choice",
          required: false,
          source: "check-steps",
          help: "Leave empty to run every step. The rollback step is never offered.",
        },
      ],
      needs: ["product"],
    },
    {
      id: "product-e2e",
      title: "Click through the product in a browser",
      summary:
        "Builds the web app and lets a robot browser click through the product's main journeys.",
      what_happens: [
        "Runs make product-e2e: builds the web app, then Playwright tests against the product.",
        "The robot signs up and clicks like a person would, adding test records.",
      ],
      duration: "5 to 10 minutes",
      group: "product",
      safety: "changes-data",
      confirm: "A robot browser clicks through the product, adding test records.",
      needs: ["product"],
    },
    {
      id: "product-logs",
      title: "The product's log",
      summary: "Shows the end of one product process's log.",
      what_happens: ["Runs make product-logs PROC=<process> FOLLOW=0. Nothing changes."],
      duration: "a few seconds",
      group: "product",
      safety: "safe",
      kind: "read",
      button: "Show",
      params: [
        {
          name: "proc",
          label: "Process",
          kind: "choice",
          required: true,
          source: "product-procs",
          default: "app",
          help: "Which part of the product.",
        },
      ],
    },
    {
      id: "mvp-image",
      title: "Build the product's image",
      summary: "Builds the product's Docker image, the one a server would run.",
      what_happens: ["Runs make mvp-image (docker build). Nothing running changes."],
      duration: "3 to 10 minutes",
      group: "product",
      safety: "safe",
      button: "Build",
      needs: ["docker"],
    },
    {
      id: "product-image",
      title: "Start the product from its image",
      summary:
        "Runs the product from its Docker image instead of from the code, like a server would.",
      what_happens: [
        "Builds the image unless it exists, then starts the release, app and worker containers.",
        "The release step brings the database up to date (migrations).",
      ],
      duration: "3 to 10 minutes",
      group: "product",
      safety: "changes-data",
      button: "Start",
      confirm:
        "The product's containers start. Their release step migrates the shared development database.",
      migrates: true,
      needs: ["docker"],
    },
    {
      id: "product-image-down",
      title: "Stop the product's image",
      summary: "Removes the image product's containers. The databases keep running.",
      what_happens: ["Runs make product-image-down."],
      duration: "a few seconds",
      group: "product",
      safety: "stops-things",
      button: "Stop",
      confirm: "The image product's containers are removed.",
      takes: ["product"],
      needs: ["docker"],
    },
    {
      id: "product-image-logs",
      title: "The image product's log",
      summary: "Shows the end of one image container's log.",
      what_happens: ["Runs make product-image-logs PROC=<container> FOLLOW=0. Nothing changes."],
      duration: "a few seconds",
      group: "product",
      safety: "safe",
      kind: "read",
      button: "Show",
      params: [
        {
          name: "proc",
          label: "Container",
          kind: "choice",
          required: true,
          source: "image-procs",
          default: "app",
          help: "Which container.",
        },
      ],
      needs: ["docker"],
    },
    {
      id: "load-demo-data",
      title: "Load demo data",
      summary:
        "Fills the services with a demo business and the rulebook's sample rules, so the web app has something to show.",
      what_happens: [
        "Loads the rulebook's seed calendar as draft rules (make seed SERVICE=rulebook).",
        "Adds the demo tenant and a recorded notification to the services (make web-seed).",
      ],
      duration: "about 1 minute",
      group: "data",
      safety: "changes-data",
      button: "Load",
      confirm: "Demo records are added to the shared development database and the services.",
      needs: ["docker"],
    },
    {
      id: "demo",
      title: "Run the demo story",
      summary:
        "Plays the demo tenant end to end in one process: consent, profile, rules, obligations and a reminder.",
      what_happens: ["Runs make demo. It uses no database and changes nothing."],
      duration: "under 1 minute",
      group: "data",
      safety: "safe",
      button: "Run",
    },
    {
      id: "migrate",
      title: "Update the database (migrate)",
      summary: "Brings the database tables up to date with this checkout's code.",
      what_happens: [
        "Runs make migrate for every service, or for the one you pick.",
        "Changes the shared development database's tables to this branch's version.",
      ],
      duration: "under 1 minute",
      group: "data",
      safety: "changes-data",
      confirm:
        "It runs make migrate, which applies this checkout's database changes (migrations) to the shared development database.",
      params: [
        {
          name: "service",
          label: "Service",
          kind: "choice",
          required: false,
          source: "services",
          help: "Leave empty for every service.",
        },
      ],
      migrates: true,
      needs: ["docker"],
    },
    {
      id: "migrations-check",
      title: "Check the migration files",
      summary: "Checks the database change files: one head per service, names, downgrades.",
      what_happens: ["Runs make migrations-check. It reads files only."],
      duration: "under 1 minute",
      group: "data",
      safety: "safe",
      button: "Check",
    },
    {
      id: "migrations-catalog",
      title: "Check row-level security",
      summary: "Checks that every tenant table in the database has row-level security switched on.",
      what_happens: ["Runs make migrations-catalog against the running database. It only reads."],
      duration: "under 1 minute",
      group: "data",
      safety: "safe",
      button: "Check",
      needs: ["docker"],
    },
    {
      id: "data-quality",
      title: "Check the rulebook's data",
      summary: "Runs the rulebook's data-quality checks on the local database.",
      what_happens: ["Runs make data-quality. It only reads."],
      duration: "under 1 minute",
      group: "data",
      safety: "safe",
      button: "Check",
      needs: ["docker"],
    },
    {
      id: "seed-check",
      title: "Check the seed calendar",
      summary: "Checks the rulebook's seed calendar without loading it.",
      what_happens: ["Runs make seed SERVICE=rulebook ARGS=--check. It only reads."],
      duration: "under 1 minute",
      group: "data",
      safety: "safe",
      button: "Check",
    },
    {
      id: "backup",
      title: "Back up the database",
      summary: "Saves a copy of the development database into var/backups.",
      what_happens: ["Runs make dev-backup (pg_dump). The database itself does not change."],
      duration: "under 1 minute",
      group: "data",
      safety: "safe",
      button: "Back up",
      needs: ["docker"],
    },
    {
      id: "restore",
      title: "Restore a backup",
      summary: "Replaces the development database with a backup you pick.",
      what_happens: [
        "Checks the backup can be read first.",
        "Drops the database (ending every open connection) and creates it again from the backup.",
        "Everything written since that backup was taken is lost.",
      ],
      duration: "1 to 3 minutes",
      group: "data",
      safety: "destructive",
      button: "Restore",
      confirm:
        "The development database is replaced by the backup. Everything written since it was taken is lost.",
      params: [
        {
          name: "dump",
          label: "Backup",
          kind: "choice",
          required: true,
          source: "backups",
          help: "Newest first, with size and age.",
        },
        {
          name: "backup_first",
          label: "Back up first",
          kind: "boolean",
          required: false,
          default: true,
          help: "Take a backup into var/backups before anything is deleted.",
        },
      ],
      takes: ["docker"],
      needs: ["docker"],
    },
    {
      id: "reset",
      title: "Start fresh (reset the database)",
      summary: "Deletes all local data and builds an empty database again, with the sample rules.",
      what_happens: [
        "Takes a backup first, unless you untick it.",
        "Stops the services, the product and this app's workers.",
        "Deletes the containers and every data volume (make dev-reset).",
        "Starts the databases again, migrates them and loads the seed calendar.",
      ],
      duration: "3 to 5 minutes",
      group: "data",
      safety: "destructive",
      button: "Reset",
      confirm: "All local data is deleted: the database, the queues and the monitoring data.",
      params: [
        {
          name: "backup_first",
          label: "Back up first",
          kind: "boolean",
          required: false,
          default: true,
          help: "Take a backup into var/backups before anything is deleted.",
        },
      ],
      migrates: true,
      takes: ["docker", "product"],
      needs: ["docker"],
    },
    {
      id: "psql",
      title: "Open the database prompt",
      summary: "Opens Terminal with a psql prompt on the development database.",
      what_happens: [
        "Opens Terminal and runs make dev-psql there. What you type there is up to you.",
      ],
      duration: "a few seconds",
      group: "data",
      safety: "safe",
      kind: "open",
      button: "Open",
      needs: ["docker"],
    },
    {
      id: "open-doc",
      title: "Open a document",
      summary: "Opens one of the project's guides or folders.",
      what_happens: ["Opens it in its usual app. Nothing changes."],
      duration: "instant",
      group: "tools",
      safety: "safe",
      kind: "open",
      button: "Open",
      params: [
        {
          name: "doc",
          label: "Document",
          kind: "choice",
          required: true,
          source: "docs",
        },
      ],
    },
    {
      id: "open-backups-folder",
      title: "Open the backups folder",
      summary: "Shows var/backups in Finder.",
      what_happens: ["Opens the folder. Nothing changes."],
      duration: "instant",
      group: "data",
      safety: "safe",
      kind: "open",
      button: "Open",
    },
    {
      id: "gates-in-order",
      title: "Run all checks (as CI does)",
      summary: "Runs every check CI runs, one after another, and shows which passed.",
      what_happens: [
        "Runs the checks of make check one by one, then the evals, the contract checks, the ops checks, the integration tests and the security scans.",
        "A failed check does not stop the next one; the summary lists each result.",
      ],
      duration: "20 to 40 minutes",
      group: "checks",
      safety: "safe",
      button: "Run all",
    },
    {
      id: "crawl-report",
      title: "Crawl report",
      summary: "Shows crawl runs, failures, gaps and detection delays per regulator source.",
      what_happens: ["Runs make crawl-report. It only reads; nothing is crawled."],
      duration: "under 1 minute",
      group: "pipeline",
      safety: "safe",
      kind: "read",
      button: "Show",
      needs: ["docker"],
    },
    {
      id: "extract-backlog-count",
      title: "Count documents waiting for extraction",
      summary:
        "Counts, per source, the classified documents still waiting for their rule extraction.",
      what_happens: [
        "Runs make extract-backlog ARGS=--dry-run. It only reads; nothing is extracted.",
        "Shows how many documents wait per source, and whether the extraction switch is on.",
      ],
      duration: "under 1 minute",
      group: "pipeline",
      safety: "safe",
      kind: "read",
      button: "Count",
      needs: ["docker"],
      target: "extract-backlog",
    },
    {
      id: "extract-backlog",
      title: "Extract the documents waiting",
      summary:
        "Starts the rule extraction for the documents the pipeline classified while the extraction was off.",
      what_happens: [
        "Starts extraction for documents already classified (make extract-backlog); the worker does it in the background.",
        "Each document asks the model through the gateway: the free fake model on this Mac, a paid model if one is configured.",
        "It runs only while the worker's extraction switch (CW_PIPELINE_EXTRACTION_ENABLED) is on; with it off, nothing is extracted.",
        "At most 1,000 documents in one run; run it again for the rest.",
      ],
      duration: "under 1 minute to start; the worker takes longer",
      group: "pipeline",
      safety: "changes-data",
      button: "Extract",
      confirm:
        "It starts the rule extraction for the documents waiting, at most 1,000, and each one is a call to the model through the gateway.",
      needs: ["docker"],
      target: "extract-backlog",
      calls_model: true,
    },
    {
      id: "flags-check",
      title: "Check the flag registry",
      summary: "Checks the feature-flag registry: owners, expiry dates, safe defaults.",
      what_happens: ["Runs make flags-check. It only reads."],
      duration: "a few seconds",
      group: "flags",
      safety: "safe",
      button: "Check",
    },
    {
      id: "open-env",
      title: "Open the .env file",
      summary: "Opens the checkout's .env settings file in your text editor.",
      what_happens: ["Opens the file. This app never changes it."],
      duration: "instant",
      group: "flags",
      safety: "safe",
      kind: "open",
      button: "Open",
    },
    {
      id: "doctor",
      title: "Which tools are installed",
      summary: "Lists the tools the project needs and whether each one is installed.",
      what_happens: ["Runs make doctor. Nothing changes."],
      duration: "a few seconds",
      group: "tools",
      safety: "safe",
      kind: "read",
      button: "Check",
    },
    {
      id: "open-logs-folder",
      title: "Open the logs folder",
      summary:
        "Shows var/web-stack, where the services and the web app write their logs, in Finder.",
      what_happens: ["Opens the folder. Nothing changes."],
      duration: "instant",
      group: "tools",
      safety: "safe",
      kind: "open",
      button: "Open",
    },
  ],
  gates: {
    check: ["Run make check", "Every check CI runs before the Docker tests.", "10 to 20 minutes"],
    lint: ["Check code style", "ruff, eslint and prettier on the whole repo.", "1 to 3 minutes"],
    typecheck: ["Check types", "mypy --strict and tsc on every package.", "2 to 5 minutes"],
    test: ["Run the unit tests", "pytest and vitest, with the coverage gate.", "5 to 10 minutes"],
    "py-test-integration": [
      "Run the integration tests",
      "Tests against real Postgres, Redpanda and Temporal containers.",
      "5 to 15 minutes",
    ],
    eval: ["Run the evals", "The eval harness, ci profile, with the fake model.", "2 to 5 min"],
    "eval-check": ["Check the golden set", "The eval golden set and world.", "under 1 minute"],
    "openapi-compat": [
      "Check API compatibility",
      "The committed API specs break no client of main.",
      "1 to 2 minutes",
    ],
    "contracts-check": [
      "Check the generated clients",
      "Regenerates the event and API clients, then checks nothing changed.",
      "1 to 3 minutes",
    ],
    "alerts-check": ["Check the alert rules", "promtool on the Prometheus alerts.", "under 1 min"],
    "flags-check": ["Check the flag registry", "The feature-flag registry.", "a few seconds"],
    "migrations-check": ["Check the migration files", "Static migration checks.", "under 1 min"],
    sast: ["Security scan (code)", "Semgrep on the code; needs the network.", "2 to 5 minutes"],
    "deps-scan": ["Security scan (dependencies)", "Trivy on the dependencies.", "2 to 5 minutes"],
    "web-screens-check": ["Check the screens list", "docs/web/screens.md is current.", "seconds"],
    "web-e2e": [
      "Click through the web app",
      "A robot browser clicks through every page of the web app on a separate, temporary copy of the services, then the copy stops. Your own data is never touched.",
      "10 to 15 minutes",
      [
        "First checks that the copy can start: its ports are free, no other browser tests run here, and there is a browser for the tests. If not, it stops there and says why.",
        "Starts a separate, temporary copy of the ten services with throwaway data, and fills it with made-up demo data.",
        "Builds the web app in a folder of its own, then a robot browser clicks through every page against the copy and checks each one for accessibility problems.",
        "The robot browser is Playwright's own Chromium when it is downloaded on this Mac; when it is not, the check uses your installed Google Chrome. With neither, it stops at the start and offers Download the test browser (about 150 MB), which asks first.",
        "Stops the copy at the end: after the tests pass or fail, and when you cancel. Its data goes with it.",
        "Your own data and running app are never touched: the copy uses none of your services, databases or ports, and the web app you have open keeps running while it builds.",
        "The copy listens on ports 9401 to 9410 and 3410. It writes only files git ignores: var/web-stack-check (the copy's logs and seed state), apps/web/.next/web-check (the build) and apps/web/test-results.",
      ],
    ],
    "ci-lint": ["Check the CI files", "actionlint and the pre-commit config.", "under 1 minute"],
  },
  make: {
    help: {
      title: "List the make targets",
      summary: "Prints every make target with its help.",
      what: ["Reads the Makefile."],
      duration: "instant",
      safety: "safe",
      kind: "read",
    },
    doctor: {
      title: "Which tools are installed",
      summary: "Prints which required tools are present.",
      what: ["Checks the PATH for each tool."],
      duration: "a few seconds",
      safety: "safe",
      kind: "read",
      covered_by: "doctor",
    },
    dev: {
      title: "Start the databases",
      summary: "Starts Postgres, Redis, Redpanda and Temporal and waits for them.",
      what: ["Starts the dev stack's containers in Docker."],
      duration: "about 1 minute",
      safety: "safe",
      covered_by: "databases-start",
      needs: ["docker"],
    },
    "dev-observability": {
      title: "Start the monitoring tools",
      summary: "Adds Langfuse, the collector, Prometheus, Tempo, Grafana.",
      what: ["Starts the monitoring containers."],
      duration: "1 to 2 minutes",
      safety: "safe",
      covered_by: "dev-observability",
      needs: ["docker"],
    },
    "dev-llm": {
      title: "Start the fake AI model",
      summary: "Builds and starts the LLM gateway with the fake provider.",
      what: ["Builds an image and starts a container."],
      duration: "1 to 3 minutes",
      safety: "safe",
      covered_by: "dev-llm",
      needs: ["docker"],
    },
    "dev-down": {
      title: "Stop the databases",
      summary: "Stops the dev stack's containers; the data stays.",
      what: ["Every container of the dev stack stops."],
      duration: "under 1 minute",
      safety: "stops-things",
      covered_by: "databases-stop",
      takes: ["docker"],
      needs: ["docker"],
    },
    "dev-reset": {
      title: "Delete the databases",
      summary: "Stops the stack and deletes every data volume.",
      what: ["Deletes all local data."],
      duration: "1 to 2 minutes",
      safety: "refused",
      refused: "It deletes all local data without a backup. Use Start fresh, which offers one.",
      covered_by: "reset",
    },
    "dev-logs": {
      title: "Follow the container logs",
      summary: "Tails the containers' logs until stopped.",
      what: ["Follows the logs."],
      duration: "until stopped",
      safety: "refused",
      refused: "It follows the logs until stopped. Use Logs, or A container's log.",
      covered_by: "container-logs",
    },
    "dev-ps": {
      title: "Show the containers",
      summary: "Container status and health.",
      what: ["Lists the containers."],
      duration: "a few seconds",
      safety: "safe",
      kind: "read",
      covered_by: "dev-ps",
      needs: ["docker"],
    },
    "dev-psql": {
      title: "Database prompt",
      summary: "psql into the application database.",
      what: ["Opens a prompt."],
      duration: "until closed",
      safety: "refused",
      refused: "It needs a terminal to type in. Use Open the database prompt, which opens one.",
      covered_by: "psql",
    },
    "dev-backup": {
      title: "Back up the database",
      summary: "pg_dump the dev database into var/backups.",
      what: ["Writes a backup file; the database does not change."],
      duration: "under 1 minute",
      safety: "safe",
      covered_by: "backup",
      needs: ["docker"],
    },
    "dev-restore": {
      title: "Restore a backup",
      summary: "Restores the dev database from a dump.",
      what: ["Replaces the database."],
      duration: "1 to 3 minutes",
      safety: "refused",
      refused:
        "It needs a backup file and replaces the database. Use Restore a backup, which checks the file and asks first.",
      covered_by: "restore",
    },
    "compose-config": {
      title: "Check docker-compose.yml",
      summary: "Validates docker-compose.yml without Docker running.",
      what: ["Reads the file."],
      duration: "a few seconds",
      safety: "safe",
      kind: "read",
    },
    "py-sync": {
      title: "Install the Python packages",
      summary: "Syncs the Python workspace into .venv.",
      what: ["Installs or updates the packages in .venv, which this app also runs from."],
      duration: "1 to 3 minutes",
      safety: "changes-data",
    },
    "lock-check": {
      title: "Check uv.lock",
      summary: "Fails if uv.lock is out of date with the pyproject files.",
      what: ["Reads the lock file."],
      duration: "a few seconds",
      safety: "safe",
    },
    "py-lint": {
      title: "Check Python style",
      summary: "ruff check and ruff format --check.",
      what: ["Reads the code."],
      duration: "under 1 minute",
      safety: "safe",
    },
    "py-format": {
      title: "Format the Python code",
      summary: "ruff format and ruff check --fix.",
      what: ["Rewrites Python files in the checkout."],
      duration: "under 1 minute",
      safety: "changes-data",
      rewrites: true,
    },
    "py-typecheck": {
      title: "Check Python types",
      summary: "mypy --strict per package.",
      what: ["Reads the code."],
      duration: "2 to 4 minutes",
      safety: "safe",
    },
    "py-test": {
      title: "Run the Python unit tests",
      summary: "pytest with the coverage gate; no Docker needed.",
      what: ["Runs the tests."],
      duration: "3 to 8 minutes",
      safety: "safe",
    },
    "py-test-integration": {
      title: "Run the integration tests",
      summary: "Tests against real containers (testcontainers).",
      what: ["Starts temporary containers, runs the tests, removes them."],
      duration: "5 to 15 minutes",
      safety: "safe",
      covered_by: "gate:py-test-integration",
      needs: ["docker"],
    },
    importlint: {
      title: "Check the import rules",
      summary: "No cross-service imports; the domain imports no I/O.",
      what: ["Reads the code."],
      duration: "under 1 minute",
      safety: "safe",
    },
    "ts-install": {
      title: "Install the JavaScript packages",
      summary: "pnpm install --frozen-lockfile.",
      what: ["Installs node_modules."],
      duration: "1 to 3 minutes",
      safety: "changes-data",
    },
    "ts-lint": {
      title: "Check JavaScript style",
      summary: "eslint per package and the prettier check.",
      what: ["Reads the code."],
      duration: "1 to 2 minutes",
      safety: "safe",
    },
    "ts-format": {
      title: "Format the JavaScript code",
      summary: "prettier --write.",
      what: ["Rewrites files in the checkout."],
      duration: "under 1 minute",
      safety: "changes-data",
      rewrites: true,
    },
    "ts-typecheck": {
      title: "Check TypeScript types",
      summary: "tsc --noEmit per package.",
      what: ["Reads the code."],
      duration: "1 to 2 minutes",
      safety: "safe",
    },
    "ts-test": {
      title: "Run the JavaScript tests",
      summary: "vitest with coverage per package.",
      what: ["Runs the tests."],
      duration: "2 to 5 minutes",
      safety: "safe",
    },
    "ts-build": {
      title: "Build the web app",
      summary: "next build and the TypeScript builds.",
      what: ["Writes build output (ignored by git)."],
      duration: "2 to 5 minutes",
      safety: "safe",
    },
    "ts-dev": {
      title: "Web and WhatsApp dev servers",
      summary: "next dev and the WhatsApp bot with reload.",
      what: ["Runs two dev servers."],
      duration: "until stopped",
      safety: "refused",
      refused:
        "It runs until it is stopped, in a terminal; this app cannot show it that way. Use Start the web app.",
      covered_by: "web-start",
    },
    install: {
      title: "Install everything",
      summary: "Installs both toolchains (Python and JavaScript).",
      what: ["Installs .venv and node_modules."],
      duration: "2 to 5 minutes",
      safety: "changes-data",
    },
    lint: {
      title: "Check code style",
      summary: "Lint both sides (CI step 1).",
      what: ["Reads the code."],
      duration: "1 to 3 minutes",
      safety: "safe",
      covered_by: "gate:lint",
    },
    format: {
      title: "Format all code",
      summary: "Auto-formats both sides.",
      what: ["Rewrites files in the checkout."],
      duration: "1 to 2 minutes",
      safety: "changes-data",
      rewrites: true,
    },
    typecheck: {
      title: "Check types",
      summary: "mypy --strict and tsc --strict.",
      what: ["Reads the code."],
      duration: "2 to 5 minutes",
      safety: "safe",
      covered_by: "gate:typecheck",
    },
    test: {
      title: "Run the unit tests",
      summary: "Unit and contract tests on both sides.",
      what: ["Runs the tests."],
      duration: "5 to 10 minutes",
      safety: "safe",
      covered_by: "gate:test",
    },
    check: {
      title: "Run make check",
      summary: "Everything CI runs before the integration tests.",
      what: ["Runs every gate."],
      duration: "10 to 20 minutes",
      safety: "safe",
      covered_by: "gate:check",
    },
    "runbooks-check": {
      title: "Check the runbooks",
      summary: "Every alert links an existing runbook.",
      what: ["Reads files."],
      duration: "a few seconds",
      safety: "safe",
    },
    eval: {
      title: "Run the evals",
      summary: "The eval harness against the golden set.",
      what: ["Runs the harness and writes a report."],
      duration: "2 to 5 minutes",
      safety: "safe",
      covered_by: "gate:eval",
    },
    "eval-check": {
      title: "Check the golden set",
      summary: "The KAG golden set and world are well formed.",
      what: ["Reads files."],
      duration: "under 1 minute",
      safety: "safe",
      covered_by: "gate:eval-check",
    },
    demo: {
      title: "Run the demo story",
      summary: "The demo tenant end to end in one process.",
      what: ["Runs in memory; nothing is stored."],
      duration: "under 1 minute",
      safety: "safe",
      covered_by: "demo",
    },
    label: {
      title: "Labelling tool",
      summary: "Builds and checks the extraction golden set.",
      what: ["Its index step reads the live regulator sites."],
      duration: "varies",
      safety: "refused",
      refused: "Its index step contacts the live regulator websites, which this app never does.",
    },
    migrate: {
      title: "Update the database (migrate)",
      summary: "alembic upgrade head for every service.",
      what: ["Changes the shared development database's tables."],
      duration: "under 1 minute",
      safety: "changes-data",
      covered_by: "migrate",
      migrates: true,
      needs: ["docker"],
    },
    run: {
      title: "Run one service",
      summary: "Runs one service with reload.",
      what: ["Runs a server."],
      duration: "until stopped",
      safety: "refused",
      refused:
        "It runs until it is stopped, in a terminal; this app cannot show it that way. Use Start the services.",
      covered_by: "ui-start",
    },
    seed: {
      title: "Load a seed",
      summary: "Loads the rulebook seed calendar as draft rules.",
      what: ["Writes draft rules into the database."],
      duration: "under 1 minute",
      safety: "refused",
      refused: "It needs a service name. Use Load demo data, or Check the seed calendar.",
      covered_by: "load-demo-data",
    },
    backfill: {
      title: "Backfill a regulator source",
      summary: "Fetches a regulator source's history into var/raw.",
      what: ["Downloads from a regulator's website."],
      duration: "varies",
      safety: "refused",
      refused: "It downloads from the live regulator websites, which this app never does.",
    },
    "crawl-report": {
      title: "Crawl report",
      summary: "Crawl runs, failures, gaps and delays per source.",
      what: ["Reads the store."],
      duration: "under 1 minute",
      safety: "safe",
      kind: "read",
      covered_by: "crawl-report",
      needs: ["docker"],
    },
    worker: {
      title: "Run a worker",
      summary: "Runs a service's worker in the foreground.",
      what: ["Runs a process."],
      duration: "until stopped",
      safety: "refused",
      refused:
        "It runs until it is stopped, in a terminal; this app cannot show it that way. Use Start a worker.",
      covered_by: "worker-start",
    },
    relay: {
      title: "Run an outbox relay",
      summary: "Runs one service's relay in the foreground.",
      what: ["Runs a process."],
      duration: "until stopped",
      safety: "refused",
      refused:
        "It runs until it is stopped, in a terminal; this app cannot show it that way. Use Start an outbox relay.",
      covered_by: "relay-start",
    },
    openapi: {
      title: "Export a service's API spec",
      summary: "Writes packages/contracts/openapi/<service>.v1.json.",
      what: ["Rewrites a spec file."],
      duration: "under 1 minute",
      safety: "refused",
      refused: "It needs a service name. Run it in a terminal: make openapi SERVICE=<name>.",
    },
    contracts: {
      title: "Generate the clients",
      summary: "Generates the event clients and the Python REST models.",
      what: ["Rewrites generated files in the checkout."],
      duration: "1 to 2 minutes",
      safety: "changes-data",
      rewrites: true,
    },
    "contracts-check": {
      title: "Check the generated clients",
      summary: "Event schemas, generated clients and the public spec.",
      what: ["Regenerates the clients, then compares them."],
      duration: "1 to 3 minutes",
      safety: "changes-data",
      rewrites: true,
      covered_by: "gate:contracts-check",
    },
    hooks: {
      title: "Install the git hooks",
      summary: "Installs the pre-commit and commit-msg hooks.",
      what: ["Changes your git setup."],
      duration: "a few seconds",
      safety: "refused",
      refused: "It changes your git hooks. Run it once in a terminal: make hooks.",
    },
    "ci-lint": {
      title: "Check the CI files",
      summary: "Validates the workflows and the pre-commit config.",
      what: ["Reads files."],
      duration: "under 1 minute",
      safety: "safe",
      covered_by: "gate:ci-lint",
    },
    "migrations-check": {
      title: "Check the migration files",
      summary: "One head per service, names, downgrades.",
      what: ["Reads files."],
      duration: "under 1 minute",
      safety: "safe",
      covered_by: "migrations-check",
    },
    "migrations-catalog": {
      title: "Check row-level security",
      summary: "Tenant tables have forced row-level security.",
      what: ["Reads the database."],
      duration: "under 1 minute",
      safety: "safe",
      covered_by: "migrations-catalog",
      needs: ["docker"],
    },
    "alerts-check": {
      title: "Check the alert rules",
      summary: "promtool: the alert rules and their tests.",
      what: ["Runs promtool in Docker."],
      duration: "under 1 minute",
      safety: "safe",
      covered_by: "gate:alerts-check",
      needs: ["docker"],
    },
    "openapi-check": {
      title: "Check the API specs",
      summary: "Every service with routes commits its spec and a test.",
      what: ["Reads files."],
      duration: "under 1 minute",
      safety: "safe",
    },
    "openapi-compat": {
      title: "Check API compatibility",
      summary: "Committed specs break no client of main.",
      what: ["Compares with main."],
      duration: "1 to 2 minutes",
      safety: "safe",
      covered_by: "gate:openapi-compat",
    },
    sast: {
      title: "Security scan (code)",
      summary: "Semgrep: an ERROR finding fails.",
      what: ["Scans the code and writes semgrep.sarif."],
      duration: "2 to 5 minutes",
      safety: "safe",
      covered_by: "gate:sast",
      needs: ["docker"],
    },
    "deps-scan": {
      title: "Security scan (dependencies)",
      summary: "Trivy: fixable HIGH and CRITICAL findings fail.",
      what: ["Scans the dependencies."],
      duration: "2 to 5 minutes",
      safety: "safe",
      covered_by: "gate:deps-scan",
      needs: ["docker"],
    },
    "ci-gate-check": {
      title: "Check the CI gate job",
      summary: "Every CI job is in the required gate's needs.",
      what: ["Reads files."],
      duration: "a few seconds",
      safety: "safe",
    },
    "data-quality": {
      title: "Check the rulebook's data",
      summary: "Data-quality checks on the local rulebook schema.",
      what: ["Reads the database."],
      duration: "under 1 minute",
      safety: "safe",
      covered_by: "data-quality",
      needs: ["docker"],
    },
    flags: {
      title: "Copy the flag registry",
      summary: "Writes py-common's copy of the flag registry, then checks it.",
      what: ["Rewrites a file in the checkout."],
      duration: "a few seconds",
      safety: "changes-data",
      rewrites: true,
    },
    "flags-check": {
      title: "Check the flag registry",
      summary: "Schema, owners, expiry and safe defaults.",
      what: ["Reads files."],
      duration: "a few seconds",
      safety: "safe",
      covered_by: "flags-check",
    },
    "dev-flags": {
      title: "Start Unleash",
      summary: "Starts Unleash for flags from Unleash.",
      what: ["Starts a container."],
      duration: "about 1 minute",
      safety: "safe",
      covered_by: "dev-flags",
      needs: ["docker"],
    },
    "openapi-public": {
      title: "Build the public API spec",
      summary: "Merges the public operations into public.v1.json.",
      what: ["Rewrites spec and model files in the checkout."],
      duration: "1 to 2 minutes",
      safety: "changes-data",
      rewrites: true,
    },
    "web-dev": {
      title: "Web app dev server",
      summary: "next dev on the web port.",
      what: ["Runs a dev server."],
      duration: "until stopped",
      safety: "refused",
      refused:
        "It runs until it is stopped, in a terminal; this app cannot show it that way. Use Start the web app.",
      covered_by: "web-start",
    },
    "web-stack": {
      title: "Start the services (in memory)",
      summary: "Every service with memory stores, no worker.",
      what: ["Starts ten processes in the background."],
      duration: "about 1 minute",
      safety: "safe",
      covered_by: "ui-start",
    },
    "web-stack-wait": {
      title: "Wait for the services",
      summary: "Waits until every service answers /health.",
      what: ["Waits."],
      duration: "up to 1 minute",
      safety: "safe",
      covered_by: "ui-wait",
    },
    "web-stack-down": {
      title: "Stop the services",
      summary: "Stops the web-stack services by their pid files.",
      what: ["Stops the services."],
      duration: "a few seconds",
      safety: "stops-things",
      covered_by: "ui-stop",
    },
    "extract-backlog": {
      title: "Extract the documents waiting",
      summary: "Starts the rule extraction for the classified documents still waiting.",
      what: [
        "Starts extraction for documents already classified; each one is a model call through the gateway.",
      ],
      duration: "under 1 minute to start",
      safety: "changes-data",
      covered_by: "extract-backlog",
      needs: ["docker"],
      calls_model: true,
    },
    replay: {
      title: "Replay a dead letter",
      summary:
        "Lists a dead-letter topic, or sends one of its messages back to where it came from.",
      what: ["Needs a topic and an event id."],
      duration: "varies",
      safety: "refused",
      refused:
        "Needs a topic and an event id: run it from a terminal, see docs/runbooks/outbox-relay.md.",
    },
    "golden-export": {
      title: "Export draft golden cases",
      summary: "Writes decided rule candidates as draft golden cases.",
      what: ["Needs a date and an output folder."],
      duration: "varies",
      safety: "refused",
      refused:
        "Needs a date and an output folder: run it from a terminal, see the rulebook README.",
    },
    "control-panel": {
      title: "Open this app",
      summary: "Opens the control app in a browser.",
      what: ["Starts another copy."],
      duration: "instant",
      safety: "refused",
      refused: "That is this app; it is already open.",
    },
    "control-panel-app": {
      title: "Rebuild this app",
      summary: "Builds ComplianceWatch.app.",
      what: ["Rebuilds the app you are using."],
      duration: "under 1 minute",
      safety: "refused",
      refused: "It rebuilds this app while it runs. Run it from a terminal.",
    },
    "web-stack-logs": {
      title: "Follow a service's log",
      summary: "Tails a web-stack service's log.",
      what: ["Follows a log."],
      duration: "until stopped",
      safety: "refused",
      refused: "It follows the log until stopped. Use Logs.",
    },
    "web-seed": {
      title: "Seed the services",
      summary: "The demo tenant and a recorded notification.",
      what: ["Adds demo records to the services."],
      duration: "under 1 minute",
      safety: "changes-data",
      covered_by: "load-demo-data",
    },
    "web-e2e-install": {
      title: "Download the test browser",
      summary: "Downloads Chromium for Playwright, once per machine.",
      what: ["Downloads about 150 MB from the internet."],
      duration: "1 to 5 minutes",
      safety: "changes-data",
    },
    "web-e2e": {
      title: "Click through the web app (on your services)",
      summary: "Playwright with accessibility checks, against the services of your own stack.",
      what: ["Builds the web app and runs the browser tests against your own services and data."],
      duration: "5 to 10 minutes",
      safety: "refused",
      refused:
        "On its own it runs the browser tests against your own services (ports 8001 to 8010 unless .env moves them) and leaves every test record in your database. Use Click through the web app, which runs them on a separate test copy.",
      covered_by: "gate:web-e2e",
    },
    "web-screens": {
      title: "Regenerate the screens list",
      summary: "Rewrites docs/web/screens.md from the registry.",
      what: ["Rewrites a file in the checkout."],
      duration: "a few seconds",
      safety: "changes-data",
      rewrites: true,
    },
    "web-screens-check": {
      title: "Check the screens list",
      summary: "docs/web/screens.md matches the registry.",
      what: ["Reads files."],
      duration: "a few seconds",
      safety: "safe",
      covered_by: "gate:web-screens-check",
    },
    "openapi-ts": {
      title: "Generate the TypeScript API types",
      summary: "From packages/contracts/openapi.",
      what: ["Rewrites generated files in the checkout."],
      duration: "under 1 minute",
      safety: "changes-data",
      rewrites: true,
    },
    "openapi-ts-check": {
      title: "Check the TypeScript API types",
      summary: "The generated types match the specs.",
      what: ["Reads files."],
      duration: "under 1 minute",
      safety: "safe",
    },
    product: {
      title: "Start the product (web on 3000)",
      summary: "make dev, migrate, the seed calendar, app, worker, web.",
      what: ["Migrates the shared database and starts the product."],
      duration: "2 to 5 minutes",
      safety: "changes-data",
      covered_by: "product-start",
      migrates: true,
    },
    "product-role": {
      title: "Refresh the product's database role",
      summary: "Creates or refreshes the product's role.",
      what: ["Changes a database role."],
      duration: "a few seconds",
      safety: "changes-data",
      covered_by: "product-role",
      needs: ["docker"],
    },
    "product-wait": {
      title: "Wait for the product",
      summary: "The app, the worker and the web app answer.",
      what: ["Waits."],
      duration: "up to 2 minutes",
      safety: "safe",
      covered_by: "product-wait",
    },
    "product-seed": {
      title: "Fill the product with sample data",
      summary: "Synthetic tenants, a publication, decisions.",
      what: ["Adds sample records to the product."],
      duration: "about 1 minute",
      safety: "changes-data",
      covered_by: "product-seed",
      needs: ["product"],
    },
    "product-check": {
      title: "Check the product works",
      summary: "Proves the running product works, step by step.",
      what: ["Adds test records to the product."],
      duration: "2 to 5 minutes",
      safety: "changes-data",
      covered_by: "product-check",
      needs: ["product"],
    },
    "product-e2e": {
      title: "Click through the product",
      summary: "Playwright against the running product.",
      what: ["Builds the web app and runs browser tests."],
      duration: "5 to 10 minutes",
      safety: "changes-data",
      covered_by: "product-e2e",
      needs: ["product"],
    },
    "product-down": {
      title: "Stop the product",
      summary: "Stops the pids make product recorded, with their children.",
      what: ["Stops the product."],
      duration: "a few seconds",
      safety: "stops-things",
      covered_by: "product-stop",
      takes: ["product"],
    },
    "product-logs": {
      title: "Follow the product's log",
      summary: "Shows a product process's log.",
      what: ["Follows a log."],
      duration: "until stopped",
      safety: "refused",
      refused: "On its own it follows the log until stopped. Use The product's log.",
      covered_by: "product-logs",
    },
    "mvp-image": {
      title: "Build the product's image",
      summary: "Builds compliancewatch-mvp:local.",
      what: ["Builds an image."],
      duration: "3 to 10 minutes",
      safety: "safe",
      covered_by: "mvp-image",
      needs: ["docker"],
    },
    "product-image": {
      title: "Start the product from its image",
      summary: "The image, release, app and worker in containers.",
      what: ["Migrates the shared database and starts containers."],
      duration: "3 to 10 minutes",
      safety: "changes-data",
      covered_by: "product-image",
      migrates: true,
      needs: ["docker"],
    },
    "product-image-down": {
      title: "Stop the product's image",
      summary: "Removes the image product's containers.",
      what: ["Removes containers."],
      duration: "a few seconds",
      safety: "stops-things",
      covered_by: "product-image-down",
      takes: ["product"],
      needs: ["docker"],
    },
    "product-image-logs": {
      title: "Follow the image product's log",
      summary: "Shows a container's log.",
      what: ["Follows a log."],
      duration: "until stopped",
      safety: "refused",
      refused: "On its own it follows the log until stopped. Use The image product's log.",
      covered_by: "product-image-logs",
    },
  },
};
