"""Shared domain kernel: value objects, the predicate algebra, status machines, protocols,
error types and the event envelope. Standard library only."""

from domain_kernel.channels import Channel
from domain_kernel.citations import Citation
from domain_kernel.confidence import CERTAIN, REVIEW_THRESHOLD, ZERO, Confidence
from domain_kernel.decisions import ApplicabilityDecision
from domain_kernel.dedupe import DedupeKey
from domain_kernel.documents import (
    BBox,
    Clause,
    DiscoveredDocument,
    DocumentRef,
    DocumentType,
    ExtractionContext,
    ParsedDocument,
    RawDocument,
    RuleCandidate,
)
from domain_kernel.errors import (
    PROBLEM_TYPE_PREFIX,
    DomainError,
    InvalidAttributeValueError,
    InvalidOperatorError,
    InvalidTransitionError,
    InvariantViolationError,
    OntologyDefinitionError,
    UnknownAttributeError,
    UnknownClosureReasonError,
)
from domain_kernel.events import TOPIC_PATTERN, DomainEvent, utc_now
from domain_kernel.ids import (
    BusinessId,
    CandidateId,
    ClauseId,
    CorrelationId,
    DecisionId,
    DocumentId,
    EntityId,
    EventId,
    ObligationId,
    RuleId,
    RuleVersionId,
    SourceId,
    TenantId,
    UserId,
)
from domain_kernel.llm import CompletionRequest, CompletionResponse
from domain_kernel.notifications import DeliveryReceipt, DeliveryStatus, RenderedMessage
from domain_kernel.ontology import (
    ALLOWED_OPERATORS,
    ATTRIBUTE_KEY_PATTERN,
    ENUM_TYPES,
    NUMERIC_TYPES,
    SEMVER_PATTERN,
    AttributeDefinition,
    AttributeSource,
    AttributeType,
    AttributeValue,
    Ontology,
    PredicateValue,
    Scalar,
)
from domain_kernel.operators import (
    MULTI_VALUE_OPERATORS,
    ORDERED_OPERATORS,
    SET_OPERATORS,
    Operator,
)
from domain_kernel.periods import EffectivePeriod
from domain_kernel.predicates import (
    AllOf,
    AnyOf,
    Applicability,
    LeafEvaluator,
    Not,
    Predicate,
    PredicateKind,
    PredicateResult,
    Specification,
    conjoin,
    disjoin,
    evaluate_predicate,
    negate,
)
from domain_kernel.profiles import ProfileSnapshot
from domain_kernel.protocols import (
    DecisionRepository,
    DocumentParser,
    LLMProvider,
    NotificationChannel,
    PredicateEvaluator,
    RuleExtractor,
    RuleReader,
    SourceAdapter,
    VectorStore,
    WorkflowHandle,
)
from domain_kernel.rules import ObligationTemplate, RuleVersionSnapshot
from domain_kernel.status import (
    OBLIGATION_TRANSITIONS,
    RULE_VERSION_TRANSITIONS,
    ClosureReason,
    ObligationStatus,
    RuleVersionStatus,
    TransitionTable,
    close_obligation,
    closing_status,
    parse_closure_reason,
)
from domain_kernel.vectors import ClauseFilter, EmbeddedClause, ScoredClause, Vector

__version__ = "0.1.0"

__all__ = [
    "ALLOWED_OPERATORS",
    "ATTRIBUTE_KEY_PATTERN",
    "CERTAIN",
    "ENUM_TYPES",
    "MULTI_VALUE_OPERATORS",
    "NUMERIC_TYPES",
    "OBLIGATION_TRANSITIONS",
    "ORDERED_OPERATORS",
    "PROBLEM_TYPE_PREFIX",
    "REVIEW_THRESHOLD",
    "RULE_VERSION_TRANSITIONS",
    "SEMVER_PATTERN",
    "SET_OPERATORS",
    "TOPIC_PATTERN",
    "ZERO",
    "AllOf",
    "AnyOf",
    "Applicability",
    "ApplicabilityDecision",
    "AttributeDefinition",
    "AttributeSource",
    "AttributeType",
    "AttributeValue",
    "BBox",
    "BusinessId",
    "CandidateId",
    "Channel",
    "Citation",
    "Clause",
    "ClauseFilter",
    "ClauseId",
    "ClosureReason",
    "CompletionRequest",
    "CompletionResponse",
    "Confidence",
    "CorrelationId",
    "DecisionId",
    "DecisionRepository",
    "DedupeKey",
    "DeliveryReceipt",
    "DeliveryStatus",
    "DiscoveredDocument",
    "DocumentId",
    "DocumentParser",
    "DocumentRef",
    "DocumentType",
    "DomainError",
    "DomainEvent",
    "EffectivePeriod",
    "EmbeddedClause",
    "EntityId",
    "EventId",
    "ExtractionContext",
    "InvalidAttributeValueError",
    "InvalidOperatorError",
    "InvalidTransitionError",
    "InvariantViolationError",
    "LLMProvider",
    "LeafEvaluator",
    "Not",
    "NotificationChannel",
    "ObligationId",
    "ObligationStatus",
    "ObligationTemplate",
    "Ontology",
    "OntologyDefinitionError",
    "Operator",
    "ParsedDocument",
    "Predicate",
    "PredicateEvaluator",
    "PredicateKind",
    "PredicateResult",
    "PredicateValue",
    "ProfileSnapshot",
    "RawDocument",
    "RenderedMessage",
    "RuleCandidate",
    "RuleExtractor",
    "RuleId",
    "RuleReader",
    "RuleVersionId",
    "RuleVersionSnapshot",
    "RuleVersionStatus",
    "Scalar",
    "ScoredClause",
    "SourceAdapter",
    "SourceId",
    "Specification",
    "TenantId",
    "TransitionTable",
    "UnknownAttributeError",
    "UnknownClosureReasonError",
    "UserId",
    "Vector",
    "VectorStore",
    "WorkflowHandle",
    "close_obligation",
    "closing_status",
    "conjoin",
    "disjoin",
    "evaluate_predicate",
    "negate",
    "parse_closure_reason",
    "utc_now",
]
