"""REST contracts: pydantic models generated from the OpenAPI specs in ``openapi/clients.json``.

``public_v1`` has one model per schema of the public API spec, ``public.v1.json``: the request
bodies a client sends and the responses it reads, errors (``Problem``) included. Its docstring
names the spec version it was generated from. Response models ignore fields they do not know,
so a client keeps working when a minor version adds one; request models refuse unknown fields,
as the services do.

The modules next to this file are generated by ``make contracts``; change the service, run
``make openapi SERVICE=<name>`` and ``make openapi-public`` instead of editing them.
"""
