"""Generated by make contracts from packages/contracts/openapi/public.v1.json (version 0.3.0). Do not edit."""

from __future__ import annotations

from datetime import date
from enum import StrEnum
from typing import Annotated, Any
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, RootModel


class AsOfFy(RootModel[str]):
    root: Annotated[
        str,
        Field(
            description="2025-26; required for an attribute stated per financial year",
            pattern="^[0-9]{4}-[0-9]{2}$",
            title="As Of Fy",
        ),
    ]


class AssigneeIn(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    assignee_id: Annotated[
        UUID | None,
        Field(
            description="The user of the tenant to give the obligation to; null for nobody",
            title="Assignee Id",
        ),
    ]


class AttributeLevel(StrEnum):
    """
    Which node of the business hierarchy holds the value: the legal entity (PAN), one
    registration (GSTIN) or one place of business. Values are inherited downward.
    """

    entity = "entity"
    registration = "registration"
    location = "location"


class AttributeSource(StrEnum):
    """
    Where a profile gets the value from.
    """

    gstin_lookup = "gstin_lookup"
    user_input = "user_input"
    derived = "derived"


class Gstin(RootModel[str]):
    root: Annotated[
        str,
        Field(
            description="GSTIN, any case or spacing. Its PAN makes the business, and the registration is pre-filled from the GSTIN and the GSTIN lookup",
            max_length=17,
            min_length=15,
            title="Gstin",
        ),
    ]


class Pan(RootModel[str]):
    root: Annotated[
        str,
        Field(
            description="PAN, any case or spacing; enough on its own when there is no GSTIN yet",
            max_length=12,
            min_length=10,
            title="Pan",
        ),
    ]


class Name(RootModel[str]):
    root: Annotated[str, Field(description="Rename", max_length=200, min_length=1, title="Name")]


class BusinessSummaryOut(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    gstins: Annotated[list[str], Field(title="Gstins")]
    id: Annotated[UUID, Field(title="Id")]
    name: Annotated[str, Field(title="Name")]
    pan: Annotated[str, Field(title="Pan")]
    updated_at: Annotated[AwareDatetime, Field(title="Updated At")]


class ChangeKind(StrEnum):
    created = "created"
    rescheduled = "rescheduled"
    closed = "closed"
    started = "started"
    assigned = "assigned"
    unassigned = "unassigned"


class CitationOut(BaseModel):
    """
    A verified quote of the clause the obligation comes from.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    citation_id: Annotated[UUID, Field(title="Citation Id")]
    clause_id: Annotated[UUID, Field(title="Clause Id")]
    clause_ref: Annotated[str, Field(title="Clause Ref")]
    document_id: Annotated[UUID, Field(title="Document Id")]
    match_score: Annotated[float | None, Field(title="Match Score")]
    quote: Annotated[str, Field(title="Quote")]
    verified_at: Annotated[AwareDatetime | None, Field(title="Verified At")]


class ClosureReason(StrEnum):
    """
    Why an obligation was closed; decides the closing status.
    """

    profile_changed = "profile_changed"
    rule_withdrawn = "rule_withdrawn"
    rule_superseded = "rule_superseded"
    waived_by_user = "waived_by_user"
    completed = "completed"


class CommentIn(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    body: Annotated[
        str,
        Field(
            description="The comment, 1 to 2000 characters once trimmed",
            max_length=2000,
            min_length=1,
            title="Body",
        ),
    ]


class CommentOut(BaseModel):
    """
    One comment. ``author_id`` is the user who wrote it, null when no token named the caller;
    ``author_label`` the author as the audit log labels them (the user's roles, or
    ``system:obligation``), never a name.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    author_id: Annotated[UUID | None, Field(title="Author Id")]
    author_label: Annotated[str, Field(title="Author Label")]
    body: Annotated[str, Field(title="Body")]
    comment_id: Annotated[UUID, Field(title="Comment Id")]
    created_at: Annotated[AwareDatetime, Field(title="Created At")]
    obligation_id: Annotated[UUID, Field(title="Obligation Id")]


class DeadlineExtensionOut(BaseModel):
    """
    A due date the version moves: the version whose date moves, the period (null when that
    version does not recur) and the new due date.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    new_due_on: Annotated[date | None, Field(title="New Due On")]
    period_label: Annotated[str | None, Field(title="Period Label")]
    rule_version_id: Annotated[UUID, Field(title="Rule Version Id")]


class ItemState(StrEnum):
    """
    Where one question stands: no value yet, an unsure answer, or an answer.
    """

    missing = "missing"
    unsure = "unsure"
    known = "known"
    not_applicable = "not_applicable"


class LookupResultOut(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    business_category: Annotated[
        str,
        Field(
            description="The category the activities map to, empty when none or several do; stored only while profile.gstin_category_prefill is on",
            title="Business Category",
        ),
    ] = ""
    constitution: Annotated[str, Field(title="Constitution")]
    gstin: Annotated[str, Field(title="Gstin")]
    gstin_status: Annotated[str, Field(title="Gstin Status")]
    legal_name: Annotated[str, Field(title="Legal Name")]
    nature_of_business: Annotated[
        list[str] | None,
        Field(
            description="The registry's activities, as it words them",
            title="Nature Of Business",
        ),
    ] = None
    registered_since: Annotated[str | None, Field(title="Registered Since")]
    registration_type: Annotated[str, Field(title="Registration Type")]
    state_code: Annotated[str, Field(title="State Code")]
    trade_name: Annotated[str, Field(title="Trade Name")]


class ObligationStatus(StrEnum):
    open = "open"
    in_progress = "in_progress"
    done = "done"
    waived = "waived"
    closed_not_applicable = "closed_not_applicable"


class OptionOut(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    label: Annotated[str, Field(title="Label")]
    value: Annotated[str, Field(title="Value")]


class PageBusinessSummaryOut(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    items: Annotated[list[BusinessSummaryOut], Field(title="Items")]
    next_cursor: Annotated[
        str | None,
        Field(
            description="Send as cursor to read the next page; null on the last page",
            title="Next Cursor",
        ),
    ]


class PrefillOut(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    applied: Annotated[list[str], Field(title="Applied")]
    looked_up: Annotated[bool, Field(title="Looked Up")]
    node_id: Annotated[UUID, Field(title="Node Id")]
    result: LookupResultOut | None
    review_task: Annotated[UUID | None, Field(title="Review Task")]


class QuestionOut(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    as_of_fy: Annotated[
        str | None,
        Field(description="The financial year a per-year answer is for", title="As Of Fy"),
    ]
    help: Annotated[str, Field(title="Help")]
    key: Annotated[str, Field(title="Key")]
    level: Annotated[str, Field(title="Level")]
    max: Annotated[int | float | None, Field(title="Max")] = None
    min: Annotated[int | float | None, Field(title="Min")] = None
    node_id: Annotated[
        UUID,
        Field(
            description="The entity or registration the answer is stored on",
            title="Node Id",
        ),
    ]
    options: Annotated[
        list[OptionOut],
        Field(description="Allowed values with their labels, in order", title="Options"),
    ]
    per_financial_year: Annotated[bool, Field(title="Per Financial Year")]
    question: Annotated[str, Field(title="Question")]
    state: Annotated[ItemState, Field(description="missing or unsure")]
    type: Annotated[str, Field(title="Type")]


class RegistrationAddIn(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    gstin: Annotated[
        str,
        Field(
            description="GSTIN, any case or spacing; it must carry the business's PAN",
            max_length=17,
            min_length=15,
            title="Gstin",
        ),
    ]
    name: Annotated[
        str,
        Field(
            description="Name of the registration; the business name when empty",
            max_length=200,
            title="Name",
        ),
    ] = ""


class RuleChangeCitationOut(BaseModel):
    """
    A verified quote of the clause the version cites.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    clause_id: Annotated[UUID, Field(title="Clause Id")]
    clause_ref: Annotated[
        str,
        Field(
            description="The clause's reference in its document, such as en.p3",
            title="Clause Ref",
        ),
    ]
    document_id: Annotated[UUID, Field(title="Document Id")]
    quote: Annotated[str, Field(title="Quote")]


class RuleChangeKind(StrEnum):
    published = "published"
    superseded = "superseded"
    withdrawn = "withdrawn"
    deadline_changed = "deadline_changed"


class RuleChangeRelationsOut(BaseModel):
    """
    The versions the version acts on when it is published: those it supersedes, corrects or
    withdraws (each ends when it takes effect), and the due dates it moves.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    corrects: Annotated[list[UUID], Field(title="Corrects")]
    extends_deadline: Annotated[list[DeadlineExtensionOut], Field(title="Extends Deadline")]
    supersedes: Annotated[list[UUID], Field(title="Supersedes")]
    withdraws: Annotated[list[UUID], Field(title="Withdraws")]


class RuleDeadlineOut(BaseModel):
    """
    What a deadline change moved: the period (null when the version does not recur), the new
    due date and the clause that says so.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    evidence_clause_id: Annotated[UUID | None, Field(title="Evidence Clause Id")]
    new_due_on: Annotated[date | None, Field(title="New Due On")]
    period_label: Annotated[str | None, Field(title="Period Label")]


class RuleVersionStatus(StrEnum):
    draft = "draft"
    in_review = "in_review"
    approved = "approved"
    published = "published"
    superseded = "superseded"
    withdrawn = "withdrawn"


class SeedStatus(StrEnum):
    needs_review = "needs_review"
    reviewed = "reviewed"


class StatusAction(StrEnum):
    start = "start"
    complete = "complete"
    waive = "waive"


class StatusIn(BaseModel):
    """
    ``start`` moves an open obligation to in progress; ``complete`` closes it as done;
    ``waive`` closes it as waived and needs a ``reason`` of at least ten characters.
    """

    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    action: StatusAction
    reason: Annotated[
        str,
        Field(
            description="Why, if you say; required for a waiver; kept in the history and the audit",
            max_length=2000,
            title="Reason",
        ),
    ] = ""


class ValidationIssue(BaseModel):
    """
    One failed check on the request. The submitted value is not echoed back.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    loc: Annotated[list[str | int], Field(title="Loc")]
    msg: Annotated[str, Field(title="Msg")]
    type: Annotated[str, Field(title="Type")]


class ValueState(StrEnum):
    known = "known"
    unsure = "unsure"
    not_applicable = "not_applicable"


class AnswerIn(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    as_of_fy: Annotated[
        AsOfFy | None,
        Field(
            description="2025-26; required for an attribute stated per financial year",
            title="As Of Fy",
        ),
    ] = None
    key: Annotated[
        str,
        Field(
            description="Ontology key",
            max_length=64,
            pattern="^[a-z][a-z0-9_]*$",
            title="Key",
        ),
    ]
    state: ValueState = ValueState.known
    value: Annotated[
        Any | None,
        Field(description="The value; absent for unsure or not_applicable", title="Value"),
    ] = None


class AttributeOut(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    as_of_fy: Annotated[str | None, Field(title="As Of Fy")]
    key: Annotated[str, Field(title="Key")]
    source: AttributeSource
    state: ValueState
    updated_at: Annotated[AwareDatetime | None, Field(title="Updated At")]
    value: Annotated[Any | None, Field(title="Value")] = None


class BusinessChangeIn(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    as_of_fy: Annotated[
        AsOfFy | None,
        Field(
            description="2025-26; required for an attribute stated per financial year",
            title="As Of Fy",
        ),
    ] = None
    key: Annotated[
        str,
        Field(
            description="Ontology key",
            max_length=64,
            pattern="^[a-z][a-z0-9_]*$",
            title="Key",
        ),
    ]
    node_id: Annotated[
        UUID | None,
        Field(
            description="The registration or location the answer is for, needed when the business has several; without it the attribute's level picks the node",
            title="Node Id",
        ),
    ] = None
    state: ValueState = ValueState.known
    value: Annotated[
        Any | None,
        Field(description="The value; absent for unsure or not_applicable", title="Value"),
    ] = None


class BusinessIn(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    answers: Annotated[
        list[AnswerIn] | None,
        Field(
            description="First answers, stored with the business",
            max_length=100,
            title="Answers",
        ),
    ] = None
    gstin: Annotated[
        Gstin | None,
        Field(
            description="GSTIN, any case or spacing. Its PAN makes the business, and the registration is pre-filled from the GSTIN and the GSTIN lookup",
            title="Gstin",
        ),
    ] = None
    name: Annotated[
        str,
        Field(
            description="The name the business goes by",
            max_length=200,
            min_length=1,
            title="Name",
        ),
    ]
    pan: Annotated[
        Pan | None,
        Field(
            description="PAN, any case or spacing; enough on its own when there is no GSTIN yet",
            title="Pan",
        ),
    ] = None
    registration_name: Annotated[
        str,
        Field(
            description="Name of the registration; the business name when empty",
            max_length=200,
            title="Registration Name",
        ),
    ] = ""


class BusinessPatchIn(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    changes: Annotated[
        list[BusinessChangeIn] | None,
        Field(
            description="Answers to store; all of them or none are stored",
            max_length=100,
            title="Changes",
        ),
    ] = None
    name: Annotated[Name | None, Field(description="Rename", title="Name")] = None


class ChangeOut(BaseModel):
    """
    One change of the obligation. ``reason`` is the reschedule or closure reason ('' for the
    other kinds) and ``note`` what the person said (a waiver's reason); ``actor`` is the user who
    made the change, null when the system did or no token named the caller. A reschedule names
    both due dates, an assignment both assignees.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    actor: Annotated[UUID | None, Field(title="Actor")]
    caused_by_rule_version_id: Annotated[UUID | None, Field(title="Caused By Rule Version Id")]
    change_id: Annotated[UUID, Field(title="Change Id")]
    kind: ChangeKind
    new_assignee_id: Annotated[UUID | None, Field(title="New Assignee Id")]
    new_due_at: Annotated[AwareDatetime | None, Field(title="New Due At")]
    note: Annotated[str, Field(title="Note")]
    occurred_at: Annotated[AwareDatetime, Field(title="Occurred At")]
    previous_assignee_id: Annotated[UUID | None, Field(title="Previous Assignee Id")]
    previous_due_at: Annotated[AwareDatetime | None, Field(title="Previous Due At")]
    reason: Annotated[str, Field(title="Reason")]
    status_after: ObligationStatus


class NodeOut(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    attributes: Annotated[list[AttributeOut], Field(title="Attributes")]
    created: Annotated[bool, Field(title="Created")] = False
    id: Annotated[UUID, Field(title="Id")]
    key: Annotated[str, Field(title="Key")]
    level: Annotated[str, Field(title="Level")]
    name: Annotated[str, Field(title="Name")]
    parent_id: Annotated[UUID | None, Field(title="Parent Id")]
    version: Annotated[int, Field(title="Version")]


class ObligationOut(BaseModel):
    """
    One obligation: due_at is the end of the due day in India, given in UTC. The period is
    half-open (period_end is the day after its last day), and null for a rule that does not
    recur. profile_version is the profile version of the decision that made it (null for one made
    before it was kept); assignee_id the user it is given to, or null.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    assignee_id: Annotated[UUID | None, Field(title="Assignee Id")]
    business_id: Annotated[UUID, Field(title="Business Id")]
    closed_at: Annotated[AwareDatetime | None, Field(title="Closed At")]
    closed_reason: ClosureReason | None
    decision_id: Annotated[UUID, Field(title="Decision Id")]
    due_at: Annotated[AwareDatetime | None, Field(title="Due At")]
    evidence_type: Annotated[str, Field(title="Evidence Type")]
    obligation_id: Annotated[UUID, Field(title="Obligation Id")]
    period_end: Annotated[date | None, Field(title="Period End")]
    period_label: Annotated[str | None, Field(title="Period Label")]
    period_start: Annotated[date | None, Field(title="Period Start")]
    profile_version: Annotated[int | None, Field(title="Profile Version")]
    rule_version_id: Annotated[UUID, Field(title="Rule Version Id")]
    status: ObligationStatus
    steps: Annotated[list[str], Field(title="Steps")]
    title: Annotated[str, Field(title="Title")]


class OnboardingOut(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    answered: Annotated[int, Field(title="Answered")]
    as_of_fy: Annotated[
        str,
        Field(
            description="The financial year per-year questions are asked for",
            title="As Of Fy",
        ),
    ]
    business_id: Annotated[UUID, Field(title="Business Id")]
    complete: Annotated[bool, Field(title="Complete")]
    next: Annotated[
        QuestionOut | None,
        Field(description="The one question to ask now; null when complete"),
    ]
    total: Annotated[int, Field(title="Total")]


class OntologyAttributeOut(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    definition: Annotated[
        str,
        Field(
            description="What the attribute means; the ontology's own words",
            title="Definition",
        ),
    ]
    example: Annotated[Any | None, Field(title="Example")] = None
    help: Annotated[str, Field(title="Help")]
    key: Annotated[str, Field(title="Key")]
    level: Annotated[
        str,
        Field(
            description="entity, registration or location: the node holding the value",
            title="Level",
        ),
    ]
    max: Annotated[int | float | None, Field(title="Max")] = None
    min: Annotated[int | float | None, Field(title="Min")] = None
    per_financial_year: Annotated[bool, Field(title="Per Financial Year")]
    question: Annotated[
        str,
        Field(
            description="How onboarding asks for it; empty for a derived one",
            title="Question",
        ),
    ]
    source: Annotated[str, Field(description="gstin_lookup, user_input or derived", title="Source")]
    type: Annotated[str, Field(title="Type")]
    values: Annotated[
        list[OptionOut],
        Field(description="Allowed values with their labels, in order", title="Values"),
    ]


class OntologyOut(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    attributes: Annotated[list[OntologyAttributeOut], Field(title="Attributes")]
    language: Annotated[str, Field(title="Language")]
    operators_by_type: Annotated[
        dict[str, list[str]],
        Field(
            description="The operators a rule predicate may use on each attribute type",
            title="Operators By Type",
        ),
    ]
    review_status: Annotated[
        str,
        Field(
            description="needs_review until an analyst has read the wording",
            title="Review Status",
        ),
    ]
    version: Annotated[
        str,
        Field(
            description="The attribute set's version, which rules are written against",
            title="Version",
        ),
    ]
    wording_version: Annotated[str, Field(title="Wording Version")]


class Problem(BaseModel):
    """
    The body of every error response.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    correlation_id: Annotated[str | None, Field(title="Correlation Id")] = None
    detail: Annotated[str | None, Field(title="Detail")] = None
    errors: Annotated[list[ValidationIssue] | None, Field(title="Errors")] = None
    instance: Annotated[str | None, Field(title="Instance")] = None
    status: Annotated[int, Field(title="Status")]
    title: Annotated[str, Field(title="Title")]
    type: Annotated[str, Field(title="Type")]


class RuleChangeOut(BaseModel):
    """
    One published change. ``kind`` says what happened to the version ``rule_version_id``:
    ``published``, ``superseded`` or ``withdrawn``, or ``deadline_changed`` when a published
    version moved its due date (``deadline``). ``caused_by_rule_version_id`` is the version whose
    publication caused it, when one did. ``changed_at`` is when the change was published.

    The rest is the version as it stands: its rule, dates and status now; ``seed_status``
    needs_review while no analyst reviewed it (a synthetic approval reviews nothing), the cue for
    a not-yet-reviewed notice; ``approved_by`` the approvers of the round it was published from
    and ``published_at`` when (empty and null for a version never published); its verified
    citations; and the versions it acts on when published (``relations``).
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    approved_by: Annotated[list[UUID], Field(title="Approved By")]
    caused_by_rule_version_id: Annotated[UUID | None, Field(title="Caused By Rule Version Id")]
    change_id: Annotated[UUID, Field(title="Change Id")]
    changed_at: Annotated[AwareDatetime, Field(title="Changed At")]
    citations: Annotated[list[RuleChangeCitationOut], Field(title="Citations")]
    deadline: RuleDeadlineOut | None
    effective_from: Annotated[date, Field(title="Effective From")]
    effective_to: Annotated[
        date | None,
        Field(description="Exclusive; null while open-ended", title="Effective To"),
    ]
    kind: RuleChangeKind
    level: AttributeLevel
    published_at: Annotated[AwareDatetime | None, Field(title="Published At")]
    regulator: Annotated[str, Field(title="Regulator")]
    relations: RuleChangeRelationsOut
    rule_key: Annotated[str, Field(title="Rule Key")]
    rule_version_id: Annotated[UUID, Field(title="Rule Version Id")]
    seed_status: SeedStatus
    status: RuleVersionStatus
    summary: Annotated[str, Field(title="Summary")]
    title: Annotated[str, Field(title="Title")]
    version: Annotated[int, Field(title="Version")]


class RuleVersionFactsOut(BaseModel):
    """
    What the obligation service keeps of the rule version an obligation comes from.
    ``reviewed`` is false while the seed rule is not reviewed (``seed_status`` needs_review),
    the cue for a not-yet-reviewed notice; ``approved_by`` lists the approvers of the round it
    was published from and ``published_at`` when, the reviewed-by line.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    approved_by: Annotated[list[UUID], Field(title="Approved By")]
    effective_from: Annotated[date, Field(title="Effective From")]
    effective_to: Annotated[date | None, Field(title="Effective To")]
    published_at: Annotated[AwareDatetime | None, Field(title="Published At")]
    reviewed: Annotated[bool, Field(title="Reviewed")]
    rule_key: Annotated[str, Field(title="Rule Key")]
    rule_version_id: Annotated[UUID, Field(title="Rule Version Id")]
    seed_status: Annotated[str, Field(title="Seed Status")]
    status: RuleVersionStatus
    title: Annotated[str, Field(title="Title")]


class BusinessOut(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    attributes: Annotated[
        list[AttributeOut],
        Field(description="Values stored on the legal entity", title="Attributes"),
    ]
    created_at: Annotated[AwareDatetime, Field(title="Created At")]
    id: Annotated[
        UUID,
        Field(description="The business id: the node id of its legal entity", title="Id"),
    ]
    name: Annotated[str, Field(title="Name")]
    pan: Annotated[str, Field(title="Pan")]
    registrations: Annotated[
        list[NodeOut],
        Field(description="Its GSTIN registrations, oldest first", title="Registrations"),
    ]
    updated_at: Annotated[AwareDatetime, Field(title="Updated At")]
    version: Annotated[int, Field(title="Version")]


class ObligationDetailOut(BaseModel):
    """
    One obligation with what its page shows: the facts of its rule version (null when the
    rulebook has no such version), the verified citations of the clause it comes from, its
    history, oldest first, and its comments, oldest first.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    assignee_id: Annotated[UUID | None, Field(title="Assignee Id")]
    business_id: Annotated[UUID, Field(title="Business Id")]
    citations: Annotated[list[CitationOut], Field(title="Citations")]
    closed_at: Annotated[AwareDatetime | None, Field(title="Closed At")]
    closed_reason: ClosureReason | None
    comments: Annotated[list[CommentOut], Field(title="Comments")]
    decision_id: Annotated[UUID, Field(title="Decision Id")]
    due_at: Annotated[AwareDatetime | None, Field(title="Due At")]
    evidence_type: Annotated[str, Field(title="Evidence Type")]
    history: Annotated[list[ChangeOut], Field(title="History")]
    obligation_id: Annotated[UUID, Field(title="Obligation Id")]
    period_end: Annotated[date | None, Field(title="Period End")]
    period_label: Annotated[str | None, Field(title="Period Label")]
    period_start: Annotated[date | None, Field(title="Period Start")]
    profile_version: Annotated[int | None, Field(title="Profile Version")]
    rule_version: RuleVersionFactsOut | None
    rule_version_id: Annotated[UUID, Field(title="Rule Version Id")]
    status: ObligationStatus
    steps: Annotated[list[str], Field(title="Steps")]
    title: Annotated[str, Field(title="Title")]


class PageRuleChangeOut(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    items: Annotated[list[RuleChangeOut], Field(title="Items")]
    next_cursor: Annotated[
        str | None,
        Field(
            description="Send as cursor to read the next page; null on the last page",
            title="Next Cursor",
        ),
    ]


class RegistrationCreatedOut(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    business: BusinessOut
    created: Annotated[
        bool,
        Field(
            description="False when the business already held this GSTIN",
            title="Created",
        ),
    ]
    prefill: PrefillOut
    registration: NodeOut


class BusinessCreatedOut(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    business: BusinessOut
    created: Annotated[
        bool,
        Field(
            description="False when the tenant already had this business",
            title="Created",
        ),
    ]
    onboarding: OnboardingOut
    prefill: Annotated[
        PrefillOut | None,
        Field(description="What the GSTIN filled in; null without one"),
    ]
