"""Generated by make contracts from packages/contracts/openapi/public.v1.json (version 0.1.0). Do not edit."""

from __future__ import annotations

from enum import StrEnum
from typing import Annotated, Any
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, RootModel


class AsOfFy(RootModel[str]):
    root: Annotated[
        str,
        Field(
            description="2025-26; required for an attribute stated per financial year",
            pattern="^[0-9]{4}-[0-9]{2}$",
            title="As Of Fy",
        ),
    ]


class AttributeSource(StrEnum):
    """
    Where a profile gets the value from.
    """

    gstin_lookup = "gstin_lookup"
    user_input = "user_input"
    derived = "derived"


class Gstin(RootModel[str]):
    root: Annotated[
        str,
        Field(
            description="GSTIN, any case or spacing. Its PAN makes the business, and the registration is pre-filled from the GSTIN and the GSTIN lookup",
            max_length=17,
            min_length=15,
            title="Gstin",
        ),
    ]


class Pan(RootModel[str]):
    root: Annotated[
        str,
        Field(
            description="PAN, any case or spacing; enough on its own when there is no GSTIN yet",
            max_length=12,
            min_length=10,
            title="Pan",
        ),
    ]


class Name(RootModel[str]):
    root: Annotated[str, Field(description="Rename", max_length=200, min_length=1, title="Name")]


class BusinessSummaryOut(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    gstins: Annotated[list[str], Field(title="Gstins")]
    id: Annotated[UUID, Field(title="Id")]
    name: Annotated[str, Field(title="Name")]
    pan: Annotated[str, Field(title="Pan")]
    updated_at: Annotated[AwareDatetime, Field(title="Updated At")]


class ItemState(StrEnum):
    """
    Where one question stands: no value yet, an unsure answer, or an answer.
    """

    missing = "missing"
    unsure = "unsure"
    known = "known"
    not_applicable = "not_applicable"


class LookupResultOut(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    business_category: Annotated[
        str,
        Field(
            description="The category the activities map to, empty when none or several do; stored only while profile.gstin_category_prefill is on",
            title="Business Category",
        ),
    ] = ""
    constitution: Annotated[str, Field(title="Constitution")]
    gstin: Annotated[str, Field(title="Gstin")]
    gstin_status: Annotated[str, Field(title="Gstin Status")]
    legal_name: Annotated[str, Field(title="Legal Name")]
    nature_of_business: Annotated[
        list[str] | None,
        Field(
            description="The registry's activities, as it words them",
            title="Nature Of Business",
        ),
    ] = None
    registered_since: Annotated[str | None, Field(title="Registered Since")]
    registration_type: Annotated[str, Field(title="Registration Type")]
    state_code: Annotated[str, Field(title="State Code")]
    trade_name: Annotated[str, Field(title="Trade Name")]


class OptionOut(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    label: Annotated[str, Field(title="Label")]
    value: Annotated[str, Field(title="Value")]


class PageBusinessSummaryOut(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    items: Annotated[list[BusinessSummaryOut], Field(title="Items")]
    next_cursor: Annotated[
        str | None,
        Field(
            description="Send as cursor to read the next page; null on the last page",
            title="Next Cursor",
        ),
    ]


class PrefillOut(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    applied: Annotated[list[str], Field(title="Applied")]
    looked_up: Annotated[bool, Field(title="Looked Up")]
    node_id: Annotated[UUID, Field(title="Node Id")]
    result: LookupResultOut | None
    review_task: Annotated[UUID | None, Field(title="Review Task")]


class QuestionOut(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    as_of_fy: Annotated[
        str | None,
        Field(description="The financial year a per-year answer is for", title="As Of Fy"),
    ]
    help: Annotated[str, Field(title="Help")]
    key: Annotated[str, Field(title="Key")]
    level: Annotated[str, Field(title="Level")]
    max: Annotated[int | float | None, Field(title="Max")] = None
    min: Annotated[int | float | None, Field(title="Min")] = None
    node_id: Annotated[
        UUID,
        Field(
            description="The entity or registration the answer is stored on",
            title="Node Id",
        ),
    ]
    options: Annotated[
        list[OptionOut],
        Field(description="Allowed values with their labels, in order", title="Options"),
    ]
    per_financial_year: Annotated[bool, Field(title="Per Financial Year")]
    question: Annotated[str, Field(title="Question")]
    state: Annotated[ItemState, Field(description="missing or unsure")]
    type: Annotated[str, Field(title="Type")]


class RegistrationAddIn(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    gstin: Annotated[
        str,
        Field(
            description="GSTIN, any case or spacing; it must carry the business's PAN",
            max_length=17,
            min_length=15,
            title="Gstin",
        ),
    ]
    name: Annotated[
        str,
        Field(
            description="Name of the registration; the business name when empty",
            max_length=200,
            title="Name",
        ),
    ] = ""


class ValidationIssue(BaseModel):
    """
    One failed check on the request. The submitted value is not echoed back.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    loc: Annotated[list[str | int], Field(title="Loc")]
    msg: Annotated[str, Field(title="Msg")]
    type: Annotated[str, Field(title="Type")]


class ValueState(StrEnum):
    known = "known"
    unsure = "unsure"
    not_applicable = "not_applicable"


class AnswerIn(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    as_of_fy: Annotated[
        AsOfFy | None,
        Field(
            description="2025-26; required for an attribute stated per financial year",
            title="As Of Fy",
        ),
    ] = None
    key: Annotated[
        str,
        Field(
            description="Ontology key",
            max_length=64,
            pattern="^[a-z][a-z0-9_]*$",
            title="Key",
        ),
    ]
    state: ValueState = ValueState.known
    value: Annotated[
        Any | None,
        Field(description="The value; absent for unsure or not_applicable", title="Value"),
    ] = None


class AttributeOut(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    as_of_fy: Annotated[str | None, Field(title="As Of Fy")]
    key: Annotated[str, Field(title="Key")]
    source: AttributeSource
    state: ValueState
    updated_at: Annotated[AwareDatetime | None, Field(title="Updated At")]
    value: Annotated[Any | None, Field(title="Value")] = None


class BusinessChangeIn(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    as_of_fy: Annotated[
        AsOfFy | None,
        Field(
            description="2025-26; required for an attribute stated per financial year",
            title="As Of Fy",
        ),
    ] = None
    key: Annotated[
        str,
        Field(
            description="Ontology key",
            max_length=64,
            pattern="^[a-z][a-z0-9_]*$",
            title="Key",
        ),
    ]
    node_id: Annotated[
        UUID | None,
        Field(
            description="The registration or location the answer is for, needed when the business has several; without it the attribute's level picks the node",
            title="Node Id",
        ),
    ] = None
    state: ValueState = ValueState.known
    value: Annotated[
        Any | None,
        Field(description="The value; absent for unsure or not_applicable", title="Value"),
    ] = None


class BusinessIn(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    answers: Annotated[
        list[AnswerIn] | None,
        Field(
            description="First answers, stored with the business",
            max_length=100,
            title="Answers",
        ),
    ] = None
    gstin: Annotated[
        Gstin | None,
        Field(
            description="GSTIN, any case or spacing. Its PAN makes the business, and the registration is pre-filled from the GSTIN and the GSTIN lookup",
            title="Gstin",
        ),
    ] = None
    name: Annotated[
        str,
        Field(
            description="The name the business goes by",
            max_length=200,
            min_length=1,
            title="Name",
        ),
    ]
    pan: Annotated[
        Pan | None,
        Field(
            description="PAN, any case or spacing; enough on its own when there is no GSTIN yet",
            title="Pan",
        ),
    ] = None
    registration_name: Annotated[
        str,
        Field(
            description="Name of the registration; the business name when empty",
            max_length=200,
            title="Registration Name",
        ),
    ] = ""


class BusinessPatchIn(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    changes: Annotated[
        list[BusinessChangeIn] | None,
        Field(
            description="Answers to store; all of them or none are stored",
            max_length=100,
            title="Changes",
        ),
    ] = None
    name: Annotated[Name | None, Field(description="Rename", title="Name")] = None


class NodeOut(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    attributes: Annotated[list[AttributeOut], Field(title="Attributes")]
    created: Annotated[bool, Field(title="Created")] = False
    id: Annotated[UUID, Field(title="Id")]
    key: Annotated[str, Field(title="Key")]
    level: Annotated[str, Field(title="Level")]
    name: Annotated[str, Field(title="Name")]
    parent_id: Annotated[UUID | None, Field(title="Parent Id")]
    version: Annotated[int, Field(title="Version")]


class OnboardingOut(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    answered: Annotated[int, Field(title="Answered")]
    as_of_fy: Annotated[
        str,
        Field(
            description="The financial year per-year questions are asked for",
            title="As Of Fy",
        ),
    ]
    business_id: Annotated[UUID, Field(title="Business Id")]
    complete: Annotated[bool, Field(title="Complete")]
    next: Annotated[
        QuestionOut | None,
        Field(description="The one question to ask now; null when complete"),
    ]
    total: Annotated[int, Field(title="Total")]


class OntologyAttributeOut(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    definition: Annotated[
        str,
        Field(
            description="What the attribute means; the ontology's own words",
            title="Definition",
        ),
    ]
    example: Annotated[Any | None, Field(title="Example")] = None
    help: Annotated[str, Field(title="Help")]
    key: Annotated[str, Field(title="Key")]
    level: Annotated[
        str,
        Field(
            description="entity, registration or location: the node holding the value",
            title="Level",
        ),
    ]
    max: Annotated[int | float | None, Field(title="Max")] = None
    min: Annotated[int | float | None, Field(title="Min")] = None
    per_financial_year: Annotated[bool, Field(title="Per Financial Year")]
    question: Annotated[
        str,
        Field(
            description="How onboarding asks for it; empty for a derived one",
            title="Question",
        ),
    ]
    source: Annotated[str, Field(description="gstin_lookup, user_input or derived", title="Source")]
    type: Annotated[str, Field(title="Type")]
    values: Annotated[
        list[OptionOut],
        Field(description="Allowed values with their labels, in order", title="Values"),
    ]


class OntologyOut(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    attributes: Annotated[list[OntologyAttributeOut], Field(title="Attributes")]
    language: Annotated[str, Field(title="Language")]
    operators_by_type: Annotated[
        dict[str, list[str]],
        Field(
            description="The operators a rule predicate may use on each attribute type",
            title="Operators By Type",
        ),
    ]
    review_status: Annotated[
        str,
        Field(
            description="needs_review until an analyst has read the wording",
            title="Review Status",
        ),
    ]
    version: Annotated[
        str,
        Field(
            description="The attribute set's version, which rules are written against",
            title="Version",
        ),
    ]
    wording_version: Annotated[str, Field(title="Wording Version")]


class Problem(BaseModel):
    """
    The body of every error response.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    correlation_id: Annotated[str | None, Field(title="Correlation Id")] = None
    detail: Annotated[str | None, Field(title="Detail")] = None
    errors: Annotated[list[ValidationIssue] | None, Field(title="Errors")] = None
    instance: Annotated[str | None, Field(title="Instance")] = None
    status: Annotated[int, Field(title="Status")]
    title: Annotated[str, Field(title="Title")]
    type: Annotated[str, Field(title="Type")]


class BusinessOut(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    attributes: Annotated[
        list[AttributeOut],
        Field(description="Values stored on the legal entity", title="Attributes"),
    ]
    created_at: Annotated[AwareDatetime, Field(title="Created At")]
    id: Annotated[
        UUID,
        Field(description="The business id: the node id of its legal entity", title="Id"),
    ]
    name: Annotated[str, Field(title="Name")]
    pan: Annotated[str, Field(title="Pan")]
    registrations: Annotated[
        list[NodeOut],
        Field(description="Its GSTIN registrations, oldest first", title="Registrations"),
    ]
    updated_at: Annotated[AwareDatetime, Field(title="Updated At")]
    version: Annotated[int, Field(title="Version")]


class RegistrationCreatedOut(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    business: BusinessOut
    created: Annotated[
        bool,
        Field(
            description="False when the business already held this GSTIN",
            title="Created",
        ),
    ]
    prefill: PrefillOut
    registration: NodeOut


class BusinessCreatedOut(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    business: BusinessOut
    created: Annotated[
        bool,
        Field(
            description="False when the tenant already had this business",
            title="Created",
        ),
    ]
    onboarding: OnboardingOut
    prefill: Annotated[
        PrefillOut | None,
        Field(description="What the GSTIN filled in; null without one"),
    ]
