// Generated by make openapi-ts from packages/contracts/openapi. Do not edit.

export type paths = {
  "/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Health */
    get: operations["health_health_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/ready": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Ready */
    get: operations["ready_ready_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/pipeline/documents": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List every source's documents, the latest fetch first
     * @description Every source's stored documents, a page at a time, the latest first fetch first (then by
     *     id), each with the type the pipeline reads it as, its classification and its extraction by
     *     the current prompt. A date filter leaves undated documents out.
     */
    get: operations["list_every_document_v1_pipeline_documents_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/pipeline/documents/{document_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Read one stored document
     * @description A stored document as its record holds it: where it was listed, what the listing said,
     *     when it was first fetched, its digest, storage key and status; with the type the pipeline
     *     reads it as, its classification, its extraction by the current prompt, and the retries
     *     people asked for.
     */
    get: operations["read_document_v1_pipeline_documents__document_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/pipeline/documents/{document_id}/raw": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * The stored bytes of a document
     * @description The bytes the raw store keeps for the document, served with the content type it was
     *     fetched with once their SHA-256 matches the record's (502 when the stored file is missing or
     *     altered, 503 when the raw store does not answer). The ETag is the digest; the bytes under it
     *     never change. The response is served inline, sandboxed and never sniffed.
     */
    get: operations["read_raw_v1_pipeline_documents__document_id__raw_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/pipeline/documents/{document_id}/retry": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Run a stored document again from a stage
     * @description Start the stored document's ingest again from ``stage``, without a new fetch, under the
     *     workflow ``pipeline-retry-<document>-<attempt>``, and answer 202 with the attempt.
     *
     *     - ``parse``: the whole ingest of the stored bytes (parse, classify, register while knowledge
     *       is on, extract a notification, circular or act amendment while the extraction is on); a
     *       document no parser read is parsed again;
     *     - ``classify``: the same, the detector reading the document again (a person's decision
     *       stands);
     *     - ``extract``: the rule extraction of a document classified on its way to it whose extraction
     *       failed or never started.
     *
     *     A ``doc_type`` reclassifies the document first: relevant, of that type, certain, by retry,
     *     with its status and a document.classified. It beats the detector and is the way back for a
     *     document set aside as irrelevant or whose triage was dismissed. Audited as
     *     pipeline.document.retry. The same request with its Idempotency-Key again answers its attempt
     *     (``Idempotent-Replayed: true``) and starts its ingest only if it did not start; the key with
     *     another body is a 422. 409 while an ingest of the document runs (an earlier retry's, its
     *     crawl's, a task resolution's, its rule extraction's), while a triage task holds it, or when
     *     there is nothing to extract; 422 for an extraction of a type no rule is extracted from; 503
     *     when Temporal does not answer (the attempt stays recorded: send the same request again).
     */
    post: operations["retry_document_v1_pipeline_documents__document_id__retry_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/pipeline/outbox/{event_id}/requeue": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Put a dead outbox row back to pending
     * @description Put the dead row back to pending with its attempts reset, due at once, so the relay sends
     *     it again on its next pass; its last error stays until a send succeeds. Audited as
     *     pipeline.outbox.requeue. A row that is not dead (pending, published) is answered as it
     *     stands, with requeued false and nothing written, so the request is safe to send again. 404
     *     for an id the outbox does not hold.
     */
    post: operations["requeue_event_v1_pipeline_outbox__event_id__requeue_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/pipeline/outbox/dead": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List the outbox's dead rows, the newest dead first
     * @description The pipeline's outbox rows the relay marked dead after its eight sends failed (their
     *     message is on <topic>.dlq), a page at a time, the newest dead first: the topic, key,
     *     attempts, last error, when each went dead, and a summary of the payload without its body.
     */
    get: operations["list_dead_events_v1_pipeline_outbox_dead_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/pipeline/ping": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Ping */
    get: operations["ping_v1_pipeline_ping_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/pipeline/runs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List the crawl runs, the latest first
     * @description Every source's crawl runs, a page at a time, the latest started first (then by id):
     *     when each ran, why (its trigger and workflow; null on runs recorded before they were
     *     kept), what its listing found (listed; stored, duplicates and failed of the new documents)
     *     and how it ended.
     */
    get: operations["list_runs_v1_pipeline_runs_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/pipeline/sources": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List the sources with how each stands
     * @description Every source the pipeline reads, by key: its name, adapter type and parameters, cadence,
     *     switches, status (healthy, fetching, failing, paused), document count, last listing,
     *     freshness against its cadence, last error, watermark and latest crawl.
     */
    get: operations["list_sources_v1_pipeline_sources_get"];
    put?: never;
    /**
     * Add a source
     * @description Add a source of a registry adapter type with that type's parameters, which it checks
     *     (422 for an unknown type or parameters it refuses). 409 when the key is taken. Audited as
     *     pipeline.source.add with the reason. The schedule crawls it at its cadence while crawling is
     *     on, unless it is added disabled or paused.
     */
    post: operations["add_source_v1_pipeline_sources_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/pipeline/sources/{key}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /**
     * Edit a source
     * @description Change a source's name, cadence, enabled or paused switch, or parameters (all of them,
     *     checked by its adapter type again); what is left out stays. Pausing stops the schedule from
     *     crawling it; a crawl that runs finishes. Audited as pipeline.source.edit with the source
     *     before and after, unless nothing changed.
     */
    patch: operations["edit_source_v1_pipeline_sources__key__patch"];
    trace?: never;
  };
  "/v1/pipeline/sources/{key}/documents": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List a source's documents, newest first
     * @description The documents stored from the source, a page at a time: the newest publication first
     *     (undated ones last), then the latest fetch, then the id. 404 for an unknown source.
     */
    get: operations["list_documents_v1_pipeline_sources__key__documents_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/pipeline/sources/{key}/fetch": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Start a crawl of the source now
     * @description Record a crawl run and start its workflow; answers 202 with the run and workflow ids at
     *     once, and the source reads fetching until the crawl ends. A paused or disabled source may be
     *     fetched by hand. 409 while a crawl of the source runs, and for an upload-only source
     *     (pipeline-source-upload-only), which lists nothing; 503 while crawling is off
     *     (CW_PIPELINE_CRAWL_ENABLED) or when Temporal does not answer, in which case the run is
     *     closed as failed with why. Audited as pipeline.source.fetch with the reason.
     */
    post: operations["fetch_source_v1_pipeline_sources__key__fetch_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/pipeline/sources/{key}/uploads": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Upload a document to a source
     * @description Store the file under the source, record it with its document.discovered and start its
     *     ingest, which parses and classifies it. The classification decides whether it is registered
     *     in the rulebook (while knowledge is on): a document that is no regulatory one is set aside,
     *     and one whose text names another type than its source publishes waits for a person's
     *     triage, neither registered; a document_type given here is taken as it is. Answers 202 at
     *     once with the stored document and the ingest's workflow id; a document no parser reads opens
     *     a manual-parse task and a held one a triage task (GET /v1/pipeline/tasks). Bytes stored
     *     before are a duplicate: nothing is recorded again and the ingest runs again. 413 past the
     *     upload limit, 415 for a file that is not a PDF or an HTML page, 404 for an unknown source,
     *     503 when Temporal does not answer (the document stays stored: upload it again). Audited as
     *     pipeline.document.upload with the reason.
     */
    post: operations["upload_document_v1_pipeline_sources__key__uploads_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/pipeline/tasks": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List the pipeline's tasks, oldest first
     * @description The tasks of a status and a kind (both optional), a page at a time, oldest first (then
     *     by id), each with its document: open manual parses are documents no parser reads, waiting
     *     for an analyst's transcript.
     */
    get: operations["list_tasks_v1_pipeline_tasks_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/pipeline/tasks/{task_id}/dismiss": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Dismiss a task with a reason
     * @description Close an open task without the work: the reason says why (a duplicate scan, not a
     *     regulatory document). A dismissed manual parse leaves its document failed and unregistered,
     *     a dismissed triage leaves it held for triage and unregistered. Audited as
     *     pipeline.task.dismiss. 409 for a closed task.
     */
    post: operations["dismiss_task_v1_pipeline_tasks__task_id__dismiss_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/pipeline/tasks/{task_id}/resolve": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Resolve a task: a manual parse with a transcript, a triage with a decision
     * @description Resolve an open task.
     *
     *     A manual parse takes the document typed by hand (``transcript``): headings, numbered
     *     paragraphs and tables in document order, checked first (422 names each problem). The
     *     transcript is kept in the raw store, the task is resolved and audited as
     *     pipeline.task.resolve, and an ingest starts that parses the document from it as manual@1,
     *     classifies it and, unless the classification sets it aside or holds it for a triage,
     *     registers it in the rulebook while knowledge is on; from then on the document is parsed
     *     from its transcript.
     *
     *     A triage takes the analyst's decision (``triage``): relevant with the document's type, or
     *     irrelevant. It is stored on the task's resolution and becomes the document's classification
     *     (certain, by triage), with its status and a document.classified, audited as
     *     pipeline.task.resolve; the stored document's own type is never changed. A relevant document
     *     continues through an ingest (pipeline-triage-<task>) that registers it as that type while
     *     knowledge is on and, for a notification, circular or act amendment, extracts its rule
     *     candidate while the extraction is on; an irrelevant one is set aside and nothing starts.
     *
     *     409 for a closed task (the same transcript or decision again starts the ingest if it did not
     *     start); 422 for a resolution that does not fit the task (a manual parse without a
     *     transcript, a triage without a decision, or either with the other's); 503 when Temporal does
     *     not answer, in which case the task stays resolved and the same request starts the ingest
     *     again.
     */
    post: operations["resolve_task_v1_pipeline_tasks__task_id__resolve_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
};
export type webhooks = Record<string, never>;
export type components = {
  schemas: {
    /** Body_upload_document_v1_pipeline_sources__key__uploads_post */
    Body_upload_document_v1_pipeline_sources__key__uploads_post: {
      /**
       * Actor Id
       * Format: uuid
       * @description The admin taking the step; a signed-in user's token overrides it, and the audit entry names whoever acted
       */
      actor_id: string;
      /** @description What it is; the source's document type when left out */
      document_type?: components["schemas"]["DocumentType"] | null;
      /**
       * External Ref
       * @description Its own reference, such as a notification number or the Act's name
       * @default
       */
      external_ref?: string;
      /**
       * File
       * @description The document: a PDF or an HTML page
       */
      file: string;
      /**
       * Published On
       * @description When it was published
       */
      published_on?: string | null;
      /**
       * Reason
       * @description Why: kept verbatim in the audit entry
       */
      reason: string;
      /**
       * Title
       * @description Its title
       * @default
       */
      title?: string;
    };
    /** ClassificationOut */
    ClassificationOut: {
      /**
       * Classified At
       * Format: date-time
       */
      classified_at: string;
      /**
       * Classifier
       * @description detector@1 for the rule-based detector, triage for a person's triage, retry for the type a person gave on a retry
       */
      classifier: string;
      confidence: components["schemas"]["TypeConfidence"];
      /**
       * Decided By
       * @description The person whose decision it is, if one's
       */
      decided_by: string | null;
      doc_type: components["schemas"]["DocumentType"];
      /** Reasons */
      reasons: string[];
      relevance: components["schemas"]["Relevance"];
      /** @description Where it goes: extract (on to the rule extraction), reference (registered, nothing extracted), irrelevant (set aside), triage (held for a person) */
      route: components["schemas"]["Route"];
      /** Task Id */
      task_id: string | null;
    };
    /** CrawlRunOut */
    CrawlRunOut: {
      /** Duplicates */
      duplicates: number;
      /** Error */
      error: string;
      /** Failed */
      failed: number;
      /** Finished At */
      finished_at: string | null;
      /** Listed */
      listed: number;
      /**
       * Run Id
       * Format: uuid
       */
      run_id: string;
      /**
       * Started At
       * Format: date-time
       */
      started_at: string;
      status: components["schemas"]["CrawlStatus"];
      /** Stored */
      stored: number;
      /** @description Why it ran: the schedule's tick, an admin's fetch, or a backfill; null on a run recorded before the pipeline kept it */
      trigger: components["schemas"]["CrawlTrigger"] | null;
      /**
       * Workflow Id
       * @description The crawl's workflow on Temporal; null on a run recorded before it was kept
       */
      workflow_id: string | null;
    };
    /**
     * CrawlStatus
     * @enum {string}
     */
    CrawlStatus: "running" | "completed" | "failed";
    /**
     * CrawlTrigger
     * @description Why a crawl ran: the schedule's tick, an admin's fetch, or a backfill of history.
     * @enum {string}
     */
    CrawlTrigger: "schedule" | "manual" | "backfill";
    /**
     * DismissIn
     * @description A task dismissed; the reason is why it needs no work.
     */
    DismissIn: {
      /**
       * Actor Id
       * Format: uuid
       * @description The admin taking the step; a signed-in user's token overrides it, and the audit entry names whoever acted
       */
      actor_id: string;
      /**
       * Reason
       * @description Why: kept verbatim in the audit entry
       */
      reason: string;
    };
    /**
     * DocumentDetailOut
     * @description One stored document with how the pipeline reads it and the retries people asked for.
     */
    DocumentDetailOut: {
      /** @description Null before its classify step */
      classification: components["schemas"]["ClassificationOut"] | null;
      /** Content Type */
      content_type: string;
      /** @description The type its uploader gave; null when it is its source's */
      doc_type: components["schemas"]["DocumentType"] | null;
      /**
       * Document Id
       * Format: uuid
       */
      document_id: string;
      /** External Ref */
      external_ref: string;
      /** @description Its rule extraction by the current prompt; null before one is stored */
      extraction: components["schemas"]["ExtractionOut"] | null;
      /**
       * Fetched At
       * Format: date-time
       * @description When the bytes were first fetched
       */
      fetched_at: string;
      /**
       * Parser Version
       * @description The parser of the document's last parse (pdf@1, pdf-tables@1, html@1, html-tables@1, manual@1 for an analyst's transcript); empty before one
       */
      parser_version: string;
      /** Published On */
      published_on: string | null;
      /**
       * Raw Path
       * @description Where the stored bytes are served
       */
      raw_path: string;
      /** @description The type the pipeline reads it as: its classification's, else its uploader's, else its source's; null for a source the code cannot read */
      read_as: components["schemas"]["DocumentType"] | null;
      /**
       * Retries
       * @description Its retries by attempt; empty before one
       */
      retries: components["schemas"]["RetryOut"][];
      /** Sha256 */
      sha256: string;
      /** Size */
      size: number;
      /** Source Key */
      source_key: string;
      /** Source Url */
      source_url: string;
      status: components["schemas"]["DocumentStatus"];
      /** Storage Key */
      storage_key: string;
      /** Title */
      title: string;
    };
    /** DocumentOut */
    DocumentOut: {
      /** Content Type */
      content_type: string;
      /** @description The type its uploader gave; null when it is its source's */
      doc_type: components["schemas"]["DocumentType"] | null;
      /**
       * Document Id
       * Format: uuid
       */
      document_id: string;
      /** External Ref */
      external_ref: string;
      /**
       * Fetched At
       * Format: date-time
       * @description When the bytes were first fetched
       */
      fetched_at: string;
      /**
       * Parser Version
       * @description The parser of the document's last parse (pdf@1, pdf-tables@1, html@1, html-tables@1, manual@1 for an analyst's transcript); empty before one
       */
      parser_version: string;
      /** Published On */
      published_on: string | null;
      /**
       * Raw Path
       * @description Where the stored bytes are served
       */
      raw_path: string;
      /** Sha256 */
      sha256: string;
      /** Size */
      size: number;
      /** Source Key */
      source_key: string;
      /** Source Url */
      source_url: string;
      status: components["schemas"]["DocumentStatus"];
      /** Storage Key */
      storage_key: string;
      /** Title */
      title: string;
    };
    /**
     * DocumentStatus
     * @description Where a stored document stands: just discovered; parsed into clauses; failed to parse
     *     (a manual parse waits); set aside as not a regulatory document (a user manual listed among
     *     notifications); classified and on its way to the rule extraction; held for a person's
     *     triage; kept for reference (a press release, a statute: on its way to be registered, nothing
     *     extracted); or extracted, its extraction stored, a candidate or an unparseable answer. The
     *     statuses a classification sets are its route, not outcomes (``domain.classification``): a
     *     ``reference`` or ``classified`` document is registered only while knowledge is on.
     * @enum {string}
     */
    DocumentStatus:
      | "discovered"
      | "parsed"
      | "failed"
      | "irrelevant"
      | "classified"
      | "triage"
      | "reference"
      | "extracted";
    /**
     * DocumentType
     * @description What a regulator document is. A ``statute`` is an Act or the Rules made under it (the
     *     CGST Act, the CGST Rules): the law the other documents amend and the rules cite. An analyst
     *     uploads it; it is registered and its clauses embedded, but no rule is extracted from it.
     * @enum {string}
     */
    DocumentType: "notification" | "circular" | "press_release" | "act_amendment" | "statute";
    /**
     * ExtractionOut
     * @description The document's rule extraction by the current prompt.
     */
    ExtractionOut: {
      /**
       * Candidate Id
       * Format: uuid
       * @description The candidate its rule.candidate.created names
       */
      candidate_id: string;
      /**
       * Extracted At
       * Format: date-time
       */
      extracted_at: string;
      /** Issue Count */
      issue_count: number;
      /** Model */
      model: string;
      /** Needs Review */
      needs_review: boolean;
      /** @description extracted (a candidate), or unparseable (the model gave none, twice) */
      outcome: components["schemas"]["ExtractionOutcome"];
      /** Prompt Version */
      prompt_version: string;
    };
    /**
     * ExtractionOutcome
     * @enum {string}
     */
    ExtractionOutcome: "extracted" | "unparseable";
    /**
     * FetchIn
     * @description An admin's fetch of the source now.
     */
    FetchIn: {
      /**
       * Actor Id
       * Format: uuid
       * @description The admin taking the step; a signed-in user's token overrides it, and the audit entry names whoever acted
       */
      actor_id: string;
      /**
       * Reason
       * @description Why: kept verbatim in the audit entry
       */
      reason: string;
    };
    /**
     * FetchOut
     * @description The crawl started: its run (``latest_run`` of the source shows it) and its workflow.
     */
    FetchOut: {
      /**
       * Run Id
       * Format: uuid
       */
      run_id: string;
      /** Source Key */
      source_key: string;
      trigger: components["schemas"]["CrawlTrigger"];
      /** Workflow Id */
      workflow_id: string;
    };
    /** FreshnessOut */
    FreshnessOut: {
      /**
       * Age Seconds
       * @description Seconds since a crawl last listed the source
       */
      age_seconds: number | null;
      /** Cadence Seconds */
      cadence_seconds: number;
      /**
       * Cadences
       * @description The age in cadences, two decimals
       */
      cadences: number | null;
      /** @description fresh within one cadence of the last listing, late within two, stale beyond (the SourceStale alert pages then), never before the first */
      state: components["schemas"]["FreshnessState"];
    };
    /**
     * FreshnessState
     * @enum {string}
     */
    FreshnessState: "fresh" | "late" | "stale" | "never";
    /** HeadingIn */
    HeadingIn: {
      /**
       * Page
       * @description The page it is on, from 1
       */
      page?: number | null;
      /** Text */
      text: string;
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "heading";
    };
    /** HealthResponse */
    HealthResponse: {
      /** Service */
      service: string;
      /** Status */
      status: string;
      /** Version */
      version: string;
    };
    /**
     * OutboxEventOut
     * @description An outbox row without its body.
     */
    OutboxEventOut: {
      /**
       * Attempts
       * @description Failed sends since it was written or last requeued
       */
      attempts: number;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Dead At
       * @description When the relay marked it dead
       */
      dead_at: string | null;
      /**
       * Event Id
       * Format: uuid
       */
      event_id: string;
      /**
       * Key
       * @description The Kafka message key (the event's source)
       */
      key: string;
      /** Last Error */
      last_error: string;
      /**
       * Occurred At
       * Format: date-time
       */
      occurred_at: string;
      /** Payload Bytes */
      payload_bytes: number;
      /** Published At */
      published_at: string | null;
      /** Schema Version */
      schema_version: string;
      status: components["schemas"]["OutboxStatus"];
      /**
       * Summary
       * @description What the event is about, from its payload: the document, source, candidate, type or outcome it names; never the body
       */
      summary: {
        [key: string]: unknown;
      };
      /** Topic */
      topic: string;
    };
    /**
     * OutboxStatus
     * @enum {string}
     */
    OutboxStatus: "pending" | "published" | "dead";
    /** Page[DocumentOut] */
    Page_DocumentOut_: {
      /** Items */
      items: components["schemas"]["DocumentOut"][];
      /**
       * Next Cursor
       * @description Send as cursor to read the next page; null on the last page
       */
      next_cursor: string | null;
    };
    /** Page[OutboxEventOut] */
    Page_OutboxEventOut_: {
      /** Items */
      items: components["schemas"]["OutboxEventOut"][];
      /**
       * Next Cursor
       * @description Send as cursor to read the next page; null on the last page
       */
      next_cursor: string | null;
    };
    /** Page[PipelineDocumentOut] */
    Page_PipelineDocumentOut_: {
      /** Items */
      items: components["schemas"]["PipelineDocumentOut"][];
      /**
       * Next Cursor
       * @description Send as cursor to read the next page; null on the last page
       */
      next_cursor: string | null;
    };
    /** Page[RunOut] */
    Page_RunOut_: {
      /** Items */
      items: components["schemas"]["RunOut"][];
      /**
       * Next Cursor
       * @description Send as cursor to read the next page; null on the last page
       */
      next_cursor: string | null;
    };
    /** Page[TaskOut] */
    Page_TaskOut_: {
      /** Items */
      items: components["schemas"]["TaskOut"][];
      /**
       * Next Cursor
       * @description Send as cursor to read the next page; null on the last page
       */
      next_cursor: string | null;
    };
    /** ParagraphIn */
    ParagraphIn: {
      /**
       * Number
       * @description The paragraph's numbering as printed: 1., (2), (a)
       * @default
       */
      number?: string;
      /**
       * Page
       * @description The page it is on, from 1
       */
      page?: number | null;
      /** Text */
      text: string;
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "paragraph";
    };
    /**
     * PipelineDocumentOut
     * @description A stored document with how the pipeline reads it.
     */
    PipelineDocumentOut: {
      /** @description Null before its classify step */
      classification: components["schemas"]["ClassificationOut"] | null;
      /** Content Type */
      content_type: string;
      /** @description The type its uploader gave; null when it is its source's */
      doc_type: components["schemas"]["DocumentType"] | null;
      /**
       * Document Id
       * Format: uuid
       */
      document_id: string;
      /** External Ref */
      external_ref: string;
      /** @description Its rule extraction by the current prompt; null before one is stored */
      extraction: components["schemas"]["ExtractionOut"] | null;
      /**
       * Fetched At
       * Format: date-time
       * @description When the bytes were first fetched
       */
      fetched_at: string;
      /**
       * Parser Version
       * @description The parser of the document's last parse (pdf@1, pdf-tables@1, html@1, html-tables@1, manual@1 for an analyst's transcript); empty before one
       */
      parser_version: string;
      /** Published On */
      published_on: string | null;
      /**
       * Raw Path
       * @description Where the stored bytes are served
       */
      raw_path: string;
      /** @description The type the pipeline reads it as: its classification's, else its uploader's, else its source's; null for a source the code cannot read */
      read_as: components["schemas"]["DocumentType"] | null;
      /** Sha256 */
      sha256: string;
      /** Size */
      size: number;
      /** Source Key */
      source_key: string;
      /** Source Url */
      source_url: string;
      status: components["schemas"]["DocumentStatus"];
      /** Storage Key */
      storage_key: string;
      /** Title */
      title: string;
    };
    /**
     * Problem
     * @description The body of every error response.
     */
    Problem: {
      /**
       * Correlation Id
       * @default null
       */
      correlation_id?: string | null;
      /**
       * Detail
       * @default null
       */
      detail?: string | null;
      /**
       * Errors
       * @default null
       */
      errors?: components["schemas"]["ValidationIssue"][] | null;
      /**
       * Instance
       * @default null
       */
      instance?: string | null;
      /** Status */
      status: number;
      /** Title */
      title: string;
      /** Type */
      type: string;
    };
    /** ReadyResponse */
    ReadyResponse: {
      /** Checks */
      checks: {
        [key: string]: boolean;
      };
      /** Status */
      status: string;
    };
    /**
     * Relevance
     * @enum {string}
     */
    Relevance: "relevant" | "irrelevant";
    /**
     * RequeueIn
     * @description A dead outbox row put back to pending, so the relay sends it again.
     */
    RequeueIn: {
      /**
       * Actor Id
       * Format: uuid
       * @description The admin taking the step; a signed-in user's token overrides it, and the audit entry names whoever acted
       */
      actor_id: string;
      /**
       * Reason
       * @description Why: kept verbatim in the audit entry
       */
      reason: string;
    };
    /**
     * RequeueOut
     * @description The row as it stands now: ``requeued`` is false for a row that was not dead (pending, or
     *     published), which nothing changed.
     */
    RequeueOut: {
      event: components["schemas"]["OutboxEventOut"];
      /** Requeued */
      requeued: boolean;
    };
    /**
     * ResolutionOut
     * @description The resolved task and the ingest it starts (a manual parse's parses the transcript, a
     *     relevant triage's continues the document as its type): ``started`` is false when it was
     *     started before (it runs, or it is done). An irrelevant triage starts none, and
     *     ``workflow_id`` is empty.
     */
    ResolutionOut: {
      /** Started */
      started: boolean;
      task: components["schemas"]["TaskOut"];
      /**
       * Workflow Id
       * @description pipeline-manual-parse-<task> or pipeline-triage-<task>; empty for an irrelevant triage
       */
      workflow_id: string;
    };
    /**
     * ResolveIn
     * @description The resolution of a task: a manual parse takes the analyst's transcript, a triage the
     *     analyst's decision.
     */
    ResolveIn: {
      /**
       * Actor Id
       * Format: uuid
       * @description The admin taking the step; a signed-in user's token overrides it, and the audit entry names whoever acted
       */
      actor_id: string;
      /**
       * Reason
       * @description Why: kept verbatim in the audit entry
       */
      reason: string;
      transcript?: components["schemas"]["TranscriptIn"] | null;
      triage?: components["schemas"]["TriageIn"] | null;
    };
    /**
     * RetryAcceptedOut
     * @description The retry and its ingest: ``started`` is false when the ingest was started before (a
     *     request sent again under its Idempotency-Key, whose answer is replayed).
     */
    RetryAcceptedOut: {
      document: components["schemas"]["DocumentDetailOut"];
      /**
       * Reclassified
       * @description Whether the person's type reclassified the document
       */
      reclassified: boolean;
      retry: components["schemas"]["RetryOut"];
      /** Started */
      started: boolean;
      /** Workflow Id */
      workflow_id: string;
    };
    /**
     * RetryIn
     * @description A retry of a stored document: the stage its ingest starts again from, and, to reclassify
     *     it, the type a person gives it.
     */
    RetryIn: {
      /**
       * Actor Id
       * Format: uuid
       * @description The admin taking the step; a signed-in user's token overrides it, and the audit entry names whoever acted
       */
      actor_id: string;
      /** @description The document's type, as a person reads it: it reclassifies the document (relevant, certain, by retry), beats the detector, and brings back a document set aside as irrelevant or whose triage was dismissed */
      doc_type?: components["schemas"]["DocumentType"] | null;
      /**
       * Reason
       * @description Why: kept verbatim in the audit entry
       */
      reason: string;
      /** @description parse: the stored document's whole ingest again (parse, classify, register, extract); classify: the same with the detector's classification read again; extract: the rule extraction of a document classified on its way to it */
      stage: components["schemas"]["RetryStage"];
    };
    /**
     * RetryOut
     * @description One retry of a document: its attempt, stage, the type a person gave, why, by whom and
     *     when, and its ingest's workflow.
     */
    RetryOut: {
      /** Attempt */
      attempt: number;
      /** @description The type the person gave the document; null when its classification stood */
      doc_type: components["schemas"]["DocumentType"] | null;
      /** Reason */
      reason: string;
      /**
       * Requested At
       * Format: date-time
       */
      requested_at: string;
      /**
       * Requested By
       * @description Who asked, when a person's token or id named one
       */
      requested_by: string | null;
      stage: components["schemas"]["RetryStage"];
      /**
       * Workflow Id
       * @description pipeline-retry-<document>-<attempt>
       */
      workflow_id: string;
    };
    /**
     * RetryStage
     * @description Where a retry starts the stored document's ingest again: its parse, its classification
     *     (read again by the detector), or its rule extraction.
     * @enum {string}
     */
    RetryStage: "parse" | "classify" | "extract";
    /**
     * Route
     * @description Where a classified document goes: on to the rule extraction, kept for reference, set
     *     aside as irrelevant, or held for a person's triage.
     * @enum {string}
     */
    Route: "extract" | "reference" | "irrelevant" | "triage";
    /**
     * RunOut
     * @description A crawl run with its source.
     */
    RunOut: {
      /** Duplicates */
      duplicates: number;
      /** Error */
      error: string;
      /** Failed */
      failed: number;
      /** Finished At */
      finished_at: string | null;
      /** Listed */
      listed: number;
      /**
       * Run Id
       * Format: uuid
       */
      run_id: string;
      /** Source Key */
      source_key: string;
      /**
       * Started At
       * Format: date-time
       */
      started_at: string;
      status: components["schemas"]["CrawlStatus"];
      /** Stored */
      stored: number;
      /** @description Why it ran: the schedule's tick, an admin's fetch, or a backfill; null on a run recorded before the pipeline kept it */
      trigger: components["schemas"]["CrawlTrigger"] | null;
      /**
       * Workflow Id
       * @description The crawl's workflow on Temporal; null on a run recorded before it was kept
       */
      workflow_id: string | null;
    };
    /**
     * SourceEditIn
     * @description What to change; a field left out stays as it is.
     */
    SourceEditIn: {
      /**
       * Actor Id
       * Format: uuid
       * @description The admin taking the step; a signed-in user's token overrides it, and the audit entry names whoever acted
       */
      actor_id: string;
      /** Cadence Seconds */
      cadence_seconds?: number | null;
      /** Enabled */
      enabled?: boolean | null;
      /** Name */
      name?: string | null;
      /**
       * Parameters
       * @description All of the adapter type's parameters, checked again
       */
      parameters?: {
        [key: string]: unknown;
      } | null;
      /** Paused */
      paused?: boolean | null;
      /**
       * Reason
       * @description Why: kept verbatim in the audit entry
       */
      reason: string;
    };
    /**
     * SourceIn
     * @description A source to add: its key, name, adapter type with the type's parameters, and cadence.
     */
    SourceIn: {
      /**
       * Actor Id
       * Format: uuid
       * @description The admin taking the step; a signed-in user's token overrides it, and the audit entry names whoever acted
       */
      actor_id: string;
      /**
       * Adapter Type
       * @description An adapter type of the registry: cbic, gstcouncil, gstn, mahagst, or upload for a source whose documents are uploaded
       * @example cbic
       */
      adapter_type: string;
      /** Cadence Seconds */
      cadence_seconds: number;
      /**
       * Enabled
       * @default true
       */
      enabled?: boolean;
      /**
       * Key
       * @example cbic_notifications
       */
      key: string;
      /** Name */
      name: string;
      /**
       * Parameters
       * @description The adapter type's parameters, which it checks: cbic takes listing (notifications or circulars) and category (one with a recorded listing); upload takes document_type (statute by default) and regulator (CBIC by default); the others take none
       * @example {
       *       "category": "Central Tax",
       *       "listing": "notifications"
       *     }
       */
      parameters?: {
        [key: string]: unknown;
      };
      /**
       * Paused
       * @default false
       */
      paused?: boolean;
      /**
       * Reason
       * @description Why: kept verbatim in the audit entry
       */
      reason: string;
    };
    /** SourceOut */
    SourceOut: {
      /** Adapter Type */
      adapter_type: string;
      /** Cadence Seconds */
      cadence_seconds: number;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      doc_type: components["schemas"]["DocumentType"] | null;
      /** Document Count */
      document_count: number;
      /** Enabled */
      enabled: boolean;
      freshness: components["schemas"]["FreshnessOut"];
      /** Key */
      key: string;
      /** Last Error */
      last_error: string;
      /**
       * Last Fetch At
       * @description When a crawl last listed the source
       */
      last_fetch_at: string | null;
      latest_run: components["schemas"]["CrawlRunOut"] | null;
      /**
       * Listable
       * @description Whether the source lists documents, so the schedule crawls it; an upload-only source (the statutes) does not, and its documents are uploaded
       */
      listable: boolean;
      /**
       * Name
       * @description The source's name, or its key when it has none
       */
      name: string;
      /** Parameters */
      parameters: {
        [key: string]: unknown;
      };
      /** Paused */
      paused: boolean;
      /**
       * Regulator
       * @description From the adapter type; null when the code cannot read the source's type
       */
      regulator: string | null;
      /** Site */
      site: string | null;
      /** @description fetching while a crawl runs, else paused while paused or disabled, failing when the last crawl recorded an error, healthy otherwise */
      status: components["schemas"]["SourceStatus"];
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
      /**
       * Watermark
       * @description The newest publication date up to which every listed document is stored
       */
      watermark: string | null;
    };
    /** SourcesOut */
    SourcesOut: {
      /**
       * Items
       * @description Every source, by key
       */
      items: components["schemas"]["SourceOut"][];
    };
    /**
     * SourceStatus
     * @enum {string}
     */
    SourceStatus: "healthy" | "fetching" | "failing" | "paused";
    /** TableIn */
    TableIn: {
      /**
       * Header
       * @description The header row, if the table has one
       */
      header?: string[] | null;
      /**
       * Page
       * @description The page it is on, from 1
       */
      page?: number | null;
      /** Rows */
      rows: string[][];
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "table";
    };
    /**
     * TaskKind
     * @enum {string}
     */
    TaskKind: "manual_parse" | "triage";
    /** TaskOut */
    TaskOut: {
      /** Claimed By */
      claimed_by: string | null;
      document: components["schemas"]["DocumentOut"];
      /**
       * Document Id
       * Format: uuid
       */
      document_id: string;
      /** @description manual_parse (no parser reads the document) or triage (the classify step found another type in the text than its source publishes) */
      kind: components["schemas"]["TaskKind"];
      /**
       * Note
       * @description The resolver's or dismisser's reason
       */
      note: string;
      /**
       * Opened At
       * Format: date-time
       */
      opened_at: string;
      /**
       * Reason
       * @description Why it opened: each parser's reason, for a manual parse; the classifier's, for a triage
       */
      reason: string;
      /**
       * Resolution
       * @description What the resolution did: for a manual parse, the transcript's storage key and digest, the parser (manual@1) and the clause count; for a triage, the relevance, the type and the route it gave the document (extract, reference or irrelevant)
       */
      resolution: {
        [key: string]: unknown;
      } | null;
      /** Resolved At */
      resolved_at: string | null;
      /**
       * Resolved By
       * @description Who resolved or dismissed it; null for one the pipeline closed itself
       */
      resolved_by: string | null;
      /** Source Key */
      source_key: string;
      status: components["schemas"]["TaskStatus"];
      /**
       * Task Id
       * Format: uuid
       */
      task_id: string;
    };
    /**
     * TaskStatus
     * @enum {string}
     */
    TaskStatus: "open" | "resolved" | "dismissed";
    /**
     * TranscriptIn
     * @description A document typed by hand in the shape of the parsers' blocks: headings, numbered
     *     paragraphs and tables in document order. Each heading and paragraph becomes a clause, each
     *     table row one (its cells joined by ' | '), numbered en.p1, hi.p1, ... per language.
     */
    TranscriptIn: {
      /** Blocks */
      blocks: (
        | components["schemas"]["HeadingIn"]
        | components["schemas"]["ParagraphIn"]
        | components["schemas"]["TableIn"]
      )[];
      /**
       * Title
       * @default
       */
      title?: string;
    };
    /**
     * TriageIn
     * @description A triage's decision: the document is relevant and of a type, or irrelevant (its type
     *     left as the classifier read it). The reason is the request's own.
     */
    TriageIn: {
      /** @description Its type, for a relevant document: a notification, circular or act amendment goes on to the rule extraction; a press release or a statute is kept for reference */
      doc_type?: components["schemas"]["DocumentType"] | null;
      /** @description relevant: a regulator's document, of doc_type; irrelevant: set it aside */
      relevance: components["schemas"]["Relevance"];
    };
    /**
     * TypeConfidence
     * @description How sure the classifier is of the type: the text names it (``certain``), nothing in the
     *     text names one and the source's is taken (``default``), or the text names another type than
     *     its source publishes (``conflict``).
     * @enum {string}
     */
    TypeConfidence: "certain" | "default" | "conflict";
    /**
     * UploadOut
     * @description The uploaded document as stored, and the ingest that parses it. For bytes stored before,
     *     ``duplicate`` is true and ``document`` is the record stored first (it may be another
     *     source's).
     */
    UploadOut: {
      document: components["schemas"]["DocumentOut"];
      /** Duplicate */
      duplicate: boolean;
      /**
       * Workflow Id
       * @description The ingest started for it, pipeline-upload-<key>-<id>
       */
      workflow_id: string;
    };
    /**
     * ValidationIssue
     * @description One failed check on the request. The submitted value is not echoed back.
     */
    ValidationIssue: {
      /** Loc */
      loc: (string | number)[];
      /** Msg */
      msg: string;
      /** Type */
      type: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
};
export type $defs = Record<string, never>;
export interface operations {
  health_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HealthResponse"];
        };
      };
    };
  };
  ready_ready_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ReadyResponse"];
        };
      };
      /** @description Service Unavailable */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ReadyResponse"];
        };
      };
    };
  };
  list_every_document_v1_pipeline_documents_get: {
    parameters: {
      query?: {
        /** @description The next_cursor of the previous page; absent for the first page */
        cursor?: string | null;
        /** @description Only documents the pipeline reads as this type: its classification's, else its uploader's, else its source's */
        doc_type?: components["schemas"]["DocumentType"] | null;
        /** @description Items per page, 1 to 200 */
        limit?: number;
        /** @description Only documents published on or after this day */
        published_from?: string | null;
        /** @description Only documents published on or before this day */
        published_to?: string | null;
        /** @description Only this source's */
        source_key?: string | null;
        /** @description Only documents of this status: discovered, parsed, failed (no parser reads it), irrelevant (set aside), classified (waiting for its extraction), triage, reference, extracted */
        status?: components["schemas"]["DocumentStatus"] | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Page_PipelineDocumentOut_"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  read_document_v1_pipeline_documents__document_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        document_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DocumentDetailOut"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  read_raw_v1_pipeline_documents__document_id__raw_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        document_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The bytes, with their content type */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/octet-stream": string;
          "application/pdf": string;
          "text/html": string;
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Bad Gateway */
      502: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Service Unavailable */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  retry_document_v1_pipeline_documents__document_id__retry_post: {
    parameters: {
      query?: never;
      header: {
        /** @description A new value for each new request, such as a UUID; a retry sends the same value and gets the first response back for 24 hours */
        "Idempotency-Key": string;
        /** @description The shared write token (CW_RULEBOOK_WRITE_TOKEN), accepted when CW_AUTH_MODE is header or dual and the request carries no bearer token; a bearer needs the admin role */
        "x-cw-write-token"?: string | null;
      };
      path: {
        document_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RetryIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RetryAcceptedOut"];
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Precondition Required */
      428: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Service Unavailable */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  requeue_event_v1_pipeline_outbox__event_id__requeue_post: {
    parameters: {
      query?: never;
      header?: {
        /** @description The shared write token (CW_RULEBOOK_WRITE_TOKEN), accepted when CW_AUTH_MODE is header or dual and the request carries no bearer token; a bearer needs the admin role */
        "x-cw-write-token"?: string | null;
      };
      path: {
        event_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RequeueIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RequeueOut"];
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Service Unavailable */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  list_dead_events_v1_pipeline_outbox_dead_get: {
    parameters: {
      query?: {
        /** @description The next_cursor of the previous page; absent for the first page */
        cursor?: string | null;
        /** @description Items per page, 1 to 200 */
        limit?: number;
        /** @description Only rows of this topic, such as document.parsed */
        topic?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Page_OutboxEventOut_"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  ping_v1_pipeline_ping_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: string;
          };
        };
      };
    };
  };
  list_runs_v1_pipeline_runs_get: {
    parameters: {
      query?: {
        /** @description The next_cursor of the previous page; absent for the first page */
        cursor?: string | null;
        /** @description Items per page, 1 to 200 */
        limit?: number;
        /** @description Only this source's */
        source_key?: string | null;
        /** @description Only runs that are running, completed or failed */
        status?: components["schemas"]["CrawlStatus"] | null;
        /** @description Only runs the schedule's tick, an admin's fetch or a backfill started */
        trigger?: components["schemas"]["CrawlTrigger"] | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Page_RunOut_"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  list_sources_v1_pipeline_sources_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SourcesOut"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  add_source_v1_pipeline_sources_post: {
    parameters: {
      query?: never;
      header?: {
        /** @description The shared write token (CW_RULEBOOK_WRITE_TOKEN), accepted when CW_AUTH_MODE is header or dual and the request carries no bearer token; a bearer needs the admin role */
        "x-cw-write-token"?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SourceIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SourceOut"];
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Service Unavailable */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  edit_source_v1_pipeline_sources__key__patch: {
    parameters: {
      query?: never;
      header?: {
        /** @description The shared write token (CW_RULEBOOK_WRITE_TOKEN), accepted when CW_AUTH_MODE is header or dual and the request carries no bearer token; a bearer needs the admin role */
        "x-cw-write-token"?: string | null;
      };
      path: {
        /** @description The source's key */
        key: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SourceEditIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SourceOut"];
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Service Unavailable */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  list_documents_v1_pipeline_sources__key__documents_get: {
    parameters: {
      query?: {
        /** @description The next_cursor of the previous page; absent for the first page */
        cursor?: string | null;
        /** @description Items per page, 1 to 200 */
        limit?: number;
      };
      header?: never;
      path: {
        /** @description The source's key */
        key: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Page_DocumentOut_"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  fetch_source_v1_pipeline_sources__key__fetch_post: {
    parameters: {
      query?: never;
      header?: {
        /** @description The shared write token (CW_RULEBOOK_WRITE_TOKEN), accepted when CW_AUTH_MODE is header or dual and the request carries no bearer token; a bearer needs the admin role */
        "x-cw-write-token"?: string | null;
      };
      path: {
        /** @description The source's key */
        key: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["FetchIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FetchOut"];
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Service Unavailable */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  upload_document_v1_pipeline_sources__key__uploads_post: {
    parameters: {
      query?: never;
      header?: {
        /** @description The shared write token (CW_RULEBOOK_WRITE_TOKEN), accepted when CW_AUTH_MODE is header or dual and the request carries no bearer token; a bearer needs the admin role */
        "x-cw-write-token"?: string | null;
      };
      path: {
        /** @description The source's key */
        key: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "multipart/form-data": components["schemas"]["Body_upload_document_v1_pipeline_sources__key__uploads_post"];
      };
    };
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UploadOut"];
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Request Entity Too Large */
      413: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Unsupported Media Type */
      415: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Service Unavailable */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  list_tasks_v1_pipeline_tasks_get: {
    parameters: {
      query?: {
        /** @description The next_cursor of the previous page; absent for the first page */
        cursor?: string | null;
        /** @description Only tasks of this kind */
        kind?: components["schemas"]["TaskKind"] | null;
        /** @description Items per page, 1 to 200 */
        limit?: number;
        /** @description Only tasks of this status */
        status?: components["schemas"]["TaskStatus"] | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Page_TaskOut_"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  dismiss_task_v1_pipeline_tasks__task_id__dismiss_post: {
    parameters: {
      query?: never;
      header?: {
        /** @description The shared write token (CW_RULEBOOK_WRITE_TOKEN), accepted when CW_AUTH_MODE is header or dual and the request carries no bearer token; a bearer needs the admin role */
        "x-cw-write-token"?: string | null;
      };
      path: {
        task_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["DismissIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TaskOut"];
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Service Unavailable */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  resolve_task_v1_pipeline_tasks__task_id__resolve_post: {
    parameters: {
      query?: never;
      header?: {
        /** @description The shared write token (CW_RULEBOOK_WRITE_TOKEN), accepted when CW_AUTH_MODE is header or dual and the request carries no bearer token; a bearer needs the admin role */
        "x-cw-write-token"?: string | null;
      };
      path: {
        task_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ResolveIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ResolutionOut"];
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Service Unavailable */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
}
