// Generated by make openapi-ts from packages/contracts/openapi. Do not edit.

export type paths = {
  "/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Health */
    get: operations["health_health_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/ready": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Ready */
    get: operations["ready_ready_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/pipeline/documents/{document_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Read one stored document
     * @description A stored document as its record holds it: where it was listed, what the listing said,
     *     when it was first fetched, its digest, storage key and status.
     */
    get: operations["read_document_v1_pipeline_documents__document_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/pipeline/documents/{document_id}/raw": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * The stored bytes of a document
     * @description The bytes the raw store keeps for the document, served with the content type it was
     *     fetched with once their SHA-256 matches the record's (502 when the stored file is missing or
     *     altered, 503 when the raw store does not answer). The ETag is the digest; the bytes under it
     *     never change. The response is served inline, sandboxed and never sniffed.
     */
    get: operations["read_raw_v1_pipeline_documents__document_id__raw_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/pipeline/ping": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Ping */
    get: operations["ping_v1_pipeline_ping_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/pipeline/sources": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List the sources with how each stands
     * @description Every source the pipeline reads, by key: its name, adapter type and parameters, cadence,
     *     switches, status (healthy, fetching, failing, paused), document count, last listing,
     *     freshness against its cadence, last error, watermark and latest crawl.
     */
    get: operations["list_sources_v1_pipeline_sources_get"];
    put?: never;
    /**
     * Add a source
     * @description Add a source of a registry adapter type with that type's parameters, which it checks
     *     (422 for an unknown type or parameters it refuses). 409 when the key is taken. Audited as
     *     pipeline.source.add with the reason. The schedule crawls it at its cadence while crawling is
     *     on, unless it is added disabled or paused.
     */
    post: operations["add_source_v1_pipeline_sources_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/pipeline/sources/{key}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /**
     * Edit a source
     * @description Change a source's name, cadence, enabled or paused switch, or parameters (all of them,
     *     checked by its adapter type again); what is left out stays. Pausing stops the schedule from
     *     crawling it; a crawl that runs finishes. Audited as pipeline.source.edit with the source
     *     before and after, unless nothing changed.
     */
    patch: operations["edit_source_v1_pipeline_sources__key__patch"];
    trace?: never;
  };
  "/v1/pipeline/sources/{key}/documents": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List a source's documents, newest first
     * @description The documents stored from the source, a page at a time: the newest publication first
     *     (undated ones last), then the latest fetch, then the id. 404 for an unknown source.
     */
    get: operations["list_documents_v1_pipeline_sources__key__documents_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/pipeline/sources/{key}/fetch": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Start a crawl of the source now
     * @description Record a crawl run and start its workflow; answers 202 with the run and workflow ids at
     *     once, and the source reads fetching until the crawl ends. A paused or disabled source may be
     *     fetched by hand. 409 while a crawl of the source runs, and for an upload-only source
     *     (pipeline-source-upload-only), which lists nothing; 503 while crawling is off
     *     (CW_PIPELINE_CRAWL_ENABLED) or when Temporal does not answer, in which case the run is
     *     closed as failed with why. Audited as pipeline.source.fetch with the reason.
     */
    post: operations["fetch_source_v1_pipeline_sources__key__fetch_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/pipeline/sources/{key}/uploads": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Upload a document to a source
     * @description Store the file under the source, record it with its document.discovered and start its
     *     ingest, which parses it and, while knowledge is on, registers it in the rulebook. Answers
     *     202 at once with the stored document and the ingest's workflow id; a document no parser
     *     reads opens a manual-parse task (GET /v1/pipeline/tasks). Bytes stored before are a
     *     duplicate: nothing is recorded again and the ingest runs again. 413 past the upload limit,
     *     415 for a file that is not a PDF or an HTML page, 404 for an unknown source, 503 when
     *     Temporal does not answer (the document stays stored: upload it again). Audited as
     *     pipeline.document.upload with the reason.
     */
    post: operations["upload_document_v1_pipeline_sources__key__uploads_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/pipeline/tasks": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List the pipeline's tasks, oldest first
     * @description The tasks of a status and a kind (both optional), a page at a time, oldest first (then
     *     by id), each with its document: open manual parses are documents no parser reads, waiting
     *     for an analyst's transcript.
     */
    get: operations["list_tasks_v1_pipeline_tasks_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/pipeline/tasks/{task_id}/dismiss": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Dismiss a task with a reason
     * @description Close an open task without the work: the reason says why (a duplicate scan, not a
     *     regulatory document). A dismissed manual parse leaves its document failed and unregistered.
     *     Audited as pipeline.task.dismiss. 409 for a closed task.
     */
    post: operations["dismiss_task_v1_pipeline_tasks__task_id__dismiss_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/pipeline/tasks/{task_id}/resolve": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Resolve a task: a manual parse with the analyst's transcript
     * @description Resolve an open manual-parse task with the document typed by hand: headings, numbered
     *     paragraphs and tables in document order, checked first (422 names each problem). The
     *     transcript is kept in the raw store, the task is resolved and audited as
     *     pipeline.task.resolve, and an ingest starts that parses the document from it as manual@1
     *     and, while knowledge is on, registers it in the rulebook; from then on the document is
     *     parsed from its transcript. 409 for a closed task (the same transcript again starts the
     *     ingest if it did not start); 422 for a resolution that does not fit the task (a manual parse
     *     without a transcript, a triage task, which its own step resolves); 503 when Temporal does
     *     not answer, in which case the task stays resolved and the same request starts the ingest
     *     again.
     */
    post: operations["resolve_task_v1_pipeline_tasks__task_id__resolve_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
};
export type webhooks = Record<string, never>;
export type components = {
  schemas: {
    /** Body_upload_document_v1_pipeline_sources__key__uploads_post */
    Body_upload_document_v1_pipeline_sources__key__uploads_post: {
      /**
       * Actor Id
       * Format: uuid
       * @description The admin taking the step; a signed-in user's token overrides it, and the audit entry names whoever acted
       */
      actor_id: string;
      /** @description What it is; the source's document type when left out */
      document_type?: components["schemas"]["DocumentType"] | null;
      /**
       * External Ref
       * @description Its own reference, such as a notification number or the Act's name
       * @default
       */
      external_ref?: string;
      /**
       * File
       * @description The document: a PDF or an HTML page
       */
      file: string;
      /**
       * Published On
       * @description When it was published
       */
      published_on?: string | null;
      /**
       * Reason
       * @description Why: kept verbatim in the audit entry
       */
      reason: string;
      /**
       * Title
       * @description Its title
       * @default
       */
      title?: string;
    };
    /** CrawlRunOut */
    CrawlRunOut: {
      /** Duplicates */
      duplicates: number;
      /** Error */
      error: string;
      /** Failed */
      failed: number;
      /** Finished At */
      finished_at: string | null;
      /** Listed */
      listed: number;
      /**
       * Run Id
       * Format: uuid
       */
      run_id: string;
      /**
       * Started At
       * Format: date-time
       */
      started_at: string;
      status: components["schemas"]["CrawlStatus"];
      /** Stored */
      stored: number;
    };
    /**
     * CrawlStatus
     * @enum {string}
     */
    CrawlStatus: "running" | "completed" | "failed";
    /**
     * CrawlTrigger
     * @description Why a crawl ran: the schedule's tick, or an admin's fetch.
     * @enum {string}
     */
    CrawlTrigger: "schedule" | "manual";
    /**
     * DismissIn
     * @description A task dismissed; the reason is why it needs no work.
     */
    DismissIn: {
      /**
       * Actor Id
       * Format: uuid
       * @description The admin taking the step; a signed-in user's token overrides it, and the audit entry names whoever acted
       */
      actor_id: string;
      /**
       * Reason
       * @description Why: kept verbatim in the audit entry
       */
      reason: string;
    };
    /** DocumentOut */
    DocumentOut: {
      /** Content Type */
      content_type: string;
      /** @description The type its uploader gave; null when it is its source's */
      doc_type: components["schemas"]["DocumentType"] | null;
      /**
       * Document Id
       * Format: uuid
       */
      document_id: string;
      /** External Ref */
      external_ref: string;
      /**
       * Fetched At
       * Format: date-time
       * @description When the bytes were first fetched
       */
      fetched_at: string;
      /**
       * Parser Version
       * @description The parser of the document's last parse (pdf@1, pdf-tables@1, html@1, html-tables@1, manual@1 for an analyst's transcript); empty before one
       */
      parser_version: string;
      /** Published On */
      published_on: string | null;
      /**
       * Raw Path
       * @description Where the stored bytes are served
       */
      raw_path: string;
      /** Sha256 */
      sha256: string;
      /** Size */
      size: number;
      /** Source Key */
      source_key: string;
      /** Source Url */
      source_url: string;
      status: components["schemas"]["DocumentStatus"];
      /** Storage Key */
      storage_key: string;
      /** Title */
      title: string;
    };
    /**
     * DocumentStatus
     * @description Where a stored document stands: just discovered, parsed into clauses, failed to parse,
     *     or set aside as not a regulatory document (a user manual listed among notifications).
     * @enum {string}
     */
    DocumentStatus: "discovered" | "parsed" | "failed" | "irrelevant";
    /**
     * DocumentType
     * @description What a regulator document is. A ``statute`` is an Act or the Rules made under it (the
     *     CGST Act, the CGST Rules): the law the other documents amend and the rules cite. An analyst
     *     uploads it; it is registered and its clauses embedded, but no rule is extracted from it.
     * @enum {string}
     */
    DocumentType: "notification" | "circular" | "press_release" | "act_amendment" | "statute";
    /**
     * FetchIn
     * @description An admin's fetch of the source now.
     */
    FetchIn: {
      /**
       * Actor Id
       * Format: uuid
       * @description The admin taking the step; a signed-in user's token overrides it, and the audit entry names whoever acted
       */
      actor_id: string;
      /**
       * Reason
       * @description Why: kept verbatim in the audit entry
       */
      reason: string;
    };
    /**
     * FetchOut
     * @description The crawl started: its run (``latest_run`` of the source shows it) and its workflow.
     */
    FetchOut: {
      /**
       * Run Id
       * Format: uuid
       */
      run_id: string;
      /** Source Key */
      source_key: string;
      trigger: components["schemas"]["CrawlTrigger"];
      /** Workflow Id */
      workflow_id: string;
    };
    /** FreshnessOut */
    FreshnessOut: {
      /**
       * Age Seconds
       * @description Seconds since a crawl last listed the source
       */
      age_seconds: number | null;
      /** Cadence Seconds */
      cadence_seconds: number;
      /**
       * Cadences
       * @description The age in cadences, two decimals
       */
      cadences: number | null;
      /** @description fresh within one cadence of the last listing, late within two, stale beyond (the SourceStale alert pages then), never before the first */
      state: components["schemas"]["FreshnessState"];
    };
    /**
     * FreshnessState
     * @enum {string}
     */
    FreshnessState: "fresh" | "late" | "stale" | "never";
    /** HeadingIn */
    HeadingIn: {
      /**
       * Page
       * @description The page it is on, from 1
       */
      page?: number | null;
      /** Text */
      text: string;
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "heading";
    };
    /** HealthResponse */
    HealthResponse: {
      /** Service */
      service: string;
      /** Status */
      status: string;
      /** Version */
      version: string;
    };
    /** Page[DocumentOut] */
    Page_DocumentOut_: {
      /** Items */
      items: components["schemas"]["DocumentOut"][];
      /**
       * Next Cursor
       * @description Send as cursor to read the next page; null on the last page
       */
      next_cursor: string | null;
    };
    /** Page[TaskOut] */
    Page_TaskOut_: {
      /** Items */
      items: components["schemas"]["TaskOut"][];
      /**
       * Next Cursor
       * @description Send as cursor to read the next page; null on the last page
       */
      next_cursor: string | null;
    };
    /** ParagraphIn */
    ParagraphIn: {
      /**
       * Number
       * @description The paragraph's numbering as printed: 1., (2), (a)
       * @default
       */
      number?: string;
      /**
       * Page
       * @description The page it is on, from 1
       */
      page?: number | null;
      /** Text */
      text: string;
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "paragraph";
    };
    /**
     * Problem
     * @description The body of every error response.
     */
    Problem: {
      /**
       * Correlation Id
       * @default null
       */
      correlation_id?: string | null;
      /**
       * Detail
       * @default null
       */
      detail?: string | null;
      /**
       * Errors
       * @default null
       */
      errors?: components["schemas"]["ValidationIssue"][] | null;
      /**
       * Instance
       * @default null
       */
      instance?: string | null;
      /** Status */
      status: number;
      /** Title */
      title: string;
      /** Type */
      type: string;
    };
    /** ReadyResponse */
    ReadyResponse: {
      /** Checks */
      checks: {
        [key: string]: boolean;
      };
      /** Status */
      status: string;
    };
    /**
     * ResolutionOut
     * @description The resolved task and the ingest that parses its transcript: ``started`` is false when it
     *     was started before (it runs, or it is done).
     */
    ResolutionOut: {
      /** Started */
      started: boolean;
      task: components["schemas"]["TaskOut"];
      /** Workflow Id */
      workflow_id: string;
    };
    /**
     * ResolveIn
     * @description The resolution of a task: a manual parse takes the analyst's transcript.
     */
    ResolveIn: {
      /**
       * Actor Id
       * Format: uuid
       * @description The admin taking the step; a signed-in user's token overrides it, and the audit entry names whoever acted
       */
      actor_id: string;
      /**
       * Reason
       * @description Why: kept verbatim in the audit entry
       */
      reason: string;
      transcript?: components["schemas"]["TranscriptIn"] | null;
    };
    /**
     * SourceEditIn
     * @description What to change; a field left out stays as it is.
     */
    SourceEditIn: {
      /**
       * Actor Id
       * Format: uuid
       * @description The admin taking the step; a signed-in user's token overrides it, and the audit entry names whoever acted
       */
      actor_id: string;
      /** Cadence Seconds */
      cadence_seconds?: number | null;
      /** Enabled */
      enabled?: boolean | null;
      /** Name */
      name?: string | null;
      /**
       * Parameters
       * @description All of the adapter type's parameters, checked again
       */
      parameters?: {
        [key: string]: unknown;
      } | null;
      /** Paused */
      paused?: boolean | null;
      /**
       * Reason
       * @description Why: kept verbatim in the audit entry
       */
      reason: string;
    };
    /**
     * SourceIn
     * @description A source to add: its key, name, adapter type with the type's parameters, and cadence.
     */
    SourceIn: {
      /**
       * Actor Id
       * Format: uuid
       * @description The admin taking the step; a signed-in user's token overrides it, and the audit entry names whoever acted
       */
      actor_id: string;
      /**
       * Adapter Type
       * @description An adapter type of the registry: cbic, gstcouncil, gstn, mahagst, or upload for a source whose documents are uploaded
       * @example cbic
       */
      adapter_type: string;
      /** Cadence Seconds */
      cadence_seconds: number;
      /**
       * Enabled
       * @default true
       */
      enabled?: boolean;
      /**
       * Key
       * @example cbic_notifications
       */
      key: string;
      /** Name */
      name: string;
      /**
       * Parameters
       * @description The adapter type's parameters, which it checks: cbic takes listing (notifications or circulars) and category (one with a recorded listing); upload takes document_type (statute by default) and regulator (CBIC by default); the others take none
       * @example {
       *       "category": "Central Tax",
       *       "listing": "notifications"
       *     }
       */
      parameters?: {
        [key: string]: unknown;
      };
      /**
       * Paused
       * @default false
       */
      paused?: boolean;
      /**
       * Reason
       * @description Why: kept verbatim in the audit entry
       */
      reason: string;
    };
    /** SourceOut */
    SourceOut: {
      /** Adapter Type */
      adapter_type: string;
      /** Cadence Seconds */
      cadence_seconds: number;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      doc_type: components["schemas"]["DocumentType"] | null;
      /** Document Count */
      document_count: number;
      /** Enabled */
      enabled: boolean;
      freshness: components["schemas"]["FreshnessOut"];
      /** Key */
      key: string;
      /** Last Error */
      last_error: string;
      /**
       * Last Fetch At
       * @description When a crawl last listed the source
       */
      last_fetch_at: string | null;
      latest_run: components["schemas"]["CrawlRunOut"] | null;
      /**
       * Listable
       * @description Whether the source lists documents, so the schedule crawls it; an upload-only source (the statutes) does not, and its documents are uploaded
       */
      listable: boolean;
      /**
       * Name
       * @description The source's name, or its key when it has none
       */
      name: string;
      /** Parameters */
      parameters: {
        [key: string]: unknown;
      };
      /** Paused */
      paused: boolean;
      /**
       * Regulator
       * @description From the adapter type; null when the code cannot read the source's type
       */
      regulator: string | null;
      /** Site */
      site: string | null;
      /** @description fetching while a crawl runs, else paused while paused or disabled, failing when the last crawl recorded an error, healthy otherwise */
      status: components["schemas"]["SourceStatus"];
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
      /**
       * Watermark
       * @description The newest publication date up to which every listed document is stored
       */
      watermark: string | null;
    };
    /** SourcesOut */
    SourcesOut: {
      /**
       * Items
       * @description Every source, by key
       */
      items: components["schemas"]["SourceOut"][];
    };
    /**
     * SourceStatus
     * @enum {string}
     */
    SourceStatus: "healthy" | "fetching" | "failing" | "paused";
    /** TableIn */
    TableIn: {
      /**
       * Header
       * @description The header row, if the table has one
       */
      header?: string[] | null;
      /**
       * Page
       * @description The page it is on, from 1
       */
      page?: number | null;
      /** Rows */
      rows: string[][];
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "table";
    };
    /**
     * TaskKind
     * @enum {string}
     */
    TaskKind: "manual_parse" | "triage";
    /** TaskOut */
    TaskOut: {
      /** Claimed By */
      claimed_by: string | null;
      document: components["schemas"]["DocumentOut"];
      /**
       * Document Id
       * Format: uuid
       */
      document_id: string;
      /** @description manual_parse (no parser reads the document) or triage */
      kind: components["schemas"]["TaskKind"];
      /**
       * Note
       * @description The resolver's or dismisser's reason
       */
      note: string;
      /**
       * Opened At
       * Format: date-time
       */
      opened_at: string;
      /**
       * Reason
       * @description Why it opened: each parser's reason, for a manual parse
       */
      reason: string;
      /**
       * Resolution
       * @description What the resolution did: for a manual parse, the transcript's storage key and digest, the parser (manual@1) and the clause count
       */
      resolution: {
        [key: string]: unknown;
      } | null;
      /** Resolved At */
      resolved_at: string | null;
      /**
       * Resolved By
       * @description Who resolved or dismissed it; null for one the pipeline closed itself
       */
      resolved_by: string | null;
      /** Source Key */
      source_key: string;
      status: components["schemas"]["TaskStatus"];
      /**
       * Task Id
       * Format: uuid
       */
      task_id: string;
    };
    /**
     * TaskStatus
     * @enum {string}
     */
    TaskStatus: "open" | "resolved" | "dismissed";
    /**
     * TranscriptIn
     * @description A document typed by hand in the shape of the parsers' blocks: headings, numbered
     *     paragraphs and tables in document order. Each heading and paragraph becomes a clause, each
     *     table row one (its cells joined by ' | '), numbered en.p1, hi.p1, ... per language.
     */
    TranscriptIn: {
      /** Blocks */
      blocks: (
        | components["schemas"]["HeadingIn"]
        | components["schemas"]["ParagraphIn"]
        | components["schemas"]["TableIn"]
      )[];
      /**
       * Title
       * @default
       */
      title?: string;
    };
    /**
     * UploadOut
     * @description The uploaded document as stored, and the ingest that parses it. For bytes stored before,
     *     ``duplicate`` is true and ``document`` is the record stored first (it may be another
     *     source's).
     */
    UploadOut: {
      document: components["schemas"]["DocumentOut"];
      /** Duplicate */
      duplicate: boolean;
      /**
       * Workflow Id
       * @description The ingest started for it, pipeline-upload-<key>-<id>
       */
      workflow_id: string;
    };
    /**
     * ValidationIssue
     * @description One failed check on the request. The submitted value is not echoed back.
     */
    ValidationIssue: {
      /** Loc */
      loc: (string | number)[];
      /** Msg */
      msg: string;
      /** Type */
      type: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
};
export type $defs = Record<string, never>;
export interface operations {
  health_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HealthResponse"];
        };
      };
    };
  };
  ready_ready_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ReadyResponse"];
        };
      };
      /** @description Service Unavailable */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ReadyResponse"];
        };
      };
    };
  };
  read_document_v1_pipeline_documents__document_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        document_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DocumentOut"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  read_raw_v1_pipeline_documents__document_id__raw_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        document_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The bytes, with their content type */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/octet-stream": string;
          "application/pdf": string;
          "text/html": string;
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Bad Gateway */
      502: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Service Unavailable */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  ping_v1_pipeline_ping_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: string;
          };
        };
      };
    };
  };
  list_sources_v1_pipeline_sources_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SourcesOut"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  add_source_v1_pipeline_sources_post: {
    parameters: {
      query?: never;
      header?: {
        /** @description The shared write token (CW_RULEBOOK_WRITE_TOKEN), accepted when CW_AUTH_MODE is header or dual and the request carries no bearer token; a bearer needs the admin role */
        "x-cw-write-token"?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SourceIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SourceOut"];
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Service Unavailable */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  edit_source_v1_pipeline_sources__key__patch: {
    parameters: {
      query?: never;
      header?: {
        /** @description The shared write token (CW_RULEBOOK_WRITE_TOKEN), accepted when CW_AUTH_MODE is header or dual and the request carries no bearer token; a bearer needs the admin role */
        "x-cw-write-token"?: string | null;
      };
      path: {
        /** @description The source's key */
        key: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SourceEditIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SourceOut"];
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Service Unavailable */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  list_documents_v1_pipeline_sources__key__documents_get: {
    parameters: {
      query?: {
        /** @description The next_cursor of the previous page; absent for the first page */
        cursor?: string | null;
        /** @description Items per page, 1 to 200 */
        limit?: number;
      };
      header?: never;
      path: {
        /** @description The source's key */
        key: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Page_DocumentOut_"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  fetch_source_v1_pipeline_sources__key__fetch_post: {
    parameters: {
      query?: never;
      header?: {
        /** @description The shared write token (CW_RULEBOOK_WRITE_TOKEN), accepted when CW_AUTH_MODE is header or dual and the request carries no bearer token; a bearer needs the admin role */
        "x-cw-write-token"?: string | null;
      };
      path: {
        /** @description The source's key */
        key: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["FetchIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FetchOut"];
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Service Unavailable */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  upload_document_v1_pipeline_sources__key__uploads_post: {
    parameters: {
      query?: never;
      header?: {
        /** @description The shared write token (CW_RULEBOOK_WRITE_TOKEN), accepted when CW_AUTH_MODE is header or dual and the request carries no bearer token; a bearer needs the admin role */
        "x-cw-write-token"?: string | null;
      };
      path: {
        /** @description The source's key */
        key: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "multipart/form-data": components["schemas"]["Body_upload_document_v1_pipeline_sources__key__uploads_post"];
      };
    };
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UploadOut"];
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Request Entity Too Large */
      413: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Unsupported Media Type */
      415: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Service Unavailable */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  list_tasks_v1_pipeline_tasks_get: {
    parameters: {
      query?: {
        /** @description The next_cursor of the previous page; absent for the first page */
        cursor?: string | null;
        /** @description Only tasks of this kind */
        kind?: components["schemas"]["TaskKind"] | null;
        /** @description Items per page, 1 to 200 */
        limit?: number;
        /** @description Only tasks of this status */
        status?: components["schemas"]["TaskStatus"] | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Page_TaskOut_"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  dismiss_task_v1_pipeline_tasks__task_id__dismiss_post: {
    parameters: {
      query?: never;
      header?: {
        /** @description The shared write token (CW_RULEBOOK_WRITE_TOKEN), accepted when CW_AUTH_MODE is header or dual and the request carries no bearer token; a bearer needs the admin role */
        "x-cw-write-token"?: string | null;
      };
      path: {
        task_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["DismissIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TaskOut"];
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Service Unavailable */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  resolve_task_v1_pipeline_tasks__task_id__resolve_post: {
    parameters: {
      query?: never;
      header?: {
        /** @description The shared write token (CW_RULEBOOK_WRITE_TOKEN), accepted when CW_AUTH_MODE is header or dual and the request carries no bearer token; a bearer needs the admin role */
        "x-cw-write-token"?: string | null;
      };
      path: {
        task_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ResolveIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ResolutionOut"];
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Service Unavailable */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
}
