// Generated by make openapi-ts from packages/contracts/openapi. Do not edit.

export type paths = {
  "/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Health */
    get: operations["health_health_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/ready": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Ready */
    get: operations["ready_ready_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/profile/entities": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Register a legal entity by PAN */
    post: operations["create_entity_v1_profile_entities_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/profile/financial-year-confirmations": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Open a confirm_financial_year review task per entity and missing per-year value
     * @description Idempotent: a task still open for the same entity, attribute and year is not opened
     *     again, so a rerun, or the April run after a manual one, opens nothing.
     */
    post: operations["confirm_financial_year_v1_profile_financial_year_confirmations_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/profile/locations": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Register a place of business under a registration */
    post: operations["create_location_v1_profile_locations_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/profile/nodes/{node_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** One node with its stored attribute values */
    get: operations["get_node_v1_profile_nodes__node_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/profile/nodes/{node_id}/attributes": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Store attribute values, unsure answers and does-not-apply answers */
    put: operations["set_attributes_v1_profile_nodes__node_id__attributes_put"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/profile/nodes/{node_id}/next-question": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** One attribute to ask for next, or none when the level is complete */
    get: operations["next_question_v1_profile_nodes__node_id__next_question_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/profile/nodes/{node_id}/review-tasks": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Open review tasks of a node */
    get: operations["review_tasks_v1_profile_nodes__node_id__review_tasks_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/profile/nodes/{node_id}/snapshot": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** The attributes the engine evaluates: inherited down the lineage, for one year */
    get: operations["snapshot_v1_profile_nodes__node_id__snapshot_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/profile/ping": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Router liveness */
    get: operations["ping_v1_profile_ping_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/profile/registrations": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Register a GSTIN; its PAN finds or creates the entity */
    post: operations["create_registration_v1_profile_registrations_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/profile/registrations/{node_id}/prefill": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Pre-fill a registration from the GSTIN lookup, or open a verify_registration task */
    post: operations["prefill_v1_profile_registrations__node_id__prefill_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
};
export type webhooks = Record<string, never>;
export type components = {
  schemas: {
    /** AttributeChangeIn */
    AttributeChangeIn: {
      /**
       * As Of Fy
       * @description 2025-26
       */
      as_of_fy?: string | null;
      /** Key */
      key: string;
      /** @default user_input */
      source?: components["schemas"]["AttributeSource"];
      /** @default known */
      state?: components["schemas"]["ValueState"];
      /** Value */
      value?: unknown;
    };
    /** AttributeOut */
    AttributeOut: {
      /** As Of Fy */
      as_of_fy: string | null;
      /** Key */
      key: string;
      source: components["schemas"]["AttributeSource"];
      state: components["schemas"]["ValueState"];
      /** Updated At */
      updated_at: string | null;
      /** Value */
      value?: unknown;
    };
    /** AttributesIn */
    AttributesIn: {
      /** Changed By */
      changed_by?: string | null;
      /** Changes */
      changes: components["schemas"]["AttributeChangeIn"][];
      /**
       * Source
       * @default user_input
       * @enum {string}
       */
      source?: "user_input" | "gstin_lookup" | "partner_api" | "import";
    };
    /**
     * AttributeSource
     * @description Where a profile gets the value from.
     * @enum {string}
     */
    AttributeSource: "gstin_lookup" | "user_input" | "derived";
    /** EntityIn */
    EntityIn: {
      /** Name */
      name: string;
      /**
       * Pan
       * @description PAN, any case or spacing
       */
      pan: string;
    };
    /** FinancialYearConfirmationIn */
    FinancialYearConfirmationIn: {
      /**
       * Fy
       * @description 2026-27; empty means the financial year of today's date in IST
       */
      fy?: string | null;
    };
    /** FinancialYearConfirmationOut */
    FinancialYearConfirmationOut: {
      /** Fy */
      fy: string;
      /**
       * Opened
       * @description The review tasks opened now; empty on a rerun
       */
      opened: string[];
    };
    /** HealthResponse */
    HealthResponse: {
      /** Service */
      service: string;
      /** Status */
      status: string;
      /** Version */
      version: string;
    };
    /** LocationIn */
    LocationIn: {
      /**
       * Label
       * @description Stable label such as a branch code
       */
      label: string;
      /** Name */
      name: string;
      /**
       * Registration Id
       * Format: uuid
       */
      registration_id: string;
    };
    /** LookupResultOut */
    LookupResultOut: {
      /** Constitution */
      constitution: string;
      /** Gstin */
      gstin: string;
      /** Gstin Status */
      gstin_status: string;
      /** Legal Name */
      legal_name: string;
      /** Registered Since */
      registered_since: string | null;
      /** Registration Type */
      registration_type: string;
      /** State Code */
      state_code: string;
      /** Trade Name */
      trade_name: string;
    };
    /** NextQuestionOut */
    NextQuestionOut: {
      /** Allowed Values */
      allowed_values: string[];
      /** As Of Fy */
      as_of_fy: string;
      /** Attribute */
      attribute: string | null;
      /** Definition */
      definition: string | null;
      /**
       * Node Id
       * Format: uuid
       */
      node_id: string;
      /** Type */
      type: string | null;
    };
    /** NodeOut */
    NodeOut: {
      /** Attributes */
      attributes: components["schemas"]["AttributeOut"][];
      /**
       * Created
       * @default false
       */
      created?: boolean;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Key */
      key: string;
      /** Level */
      level: string;
      /** Name */
      name: string;
      /** Parent Id */
      parent_id: string | null;
      /** Version */
      version: number;
    };
    /** PrefillIn */
    PrefillIn: {
      /** Changed By */
      changed_by?: string | null;
    };
    /** PrefillOut */
    PrefillOut: {
      /** Applied */
      applied: string[];
      /** Looked Up */
      looked_up: boolean;
      /**
       * Node Id
       * Format: uuid
       */
      node_id: string;
      result: components["schemas"]["LookupResultOut"] | null;
      /** Review Task */
      review_task: string | null;
    };
    /**
     * Problem
     * @description The body of every error response.
     */
    Problem: {
      /**
       * Correlation Id
       * @default null
       */
      correlation_id?: string | null;
      /**
       * Detail
       * @default null
       */
      detail?: string | null;
      /**
       * Errors
       * @default null
       */
      errors?: components["schemas"]["ValidationIssue"][] | null;
      /**
       * Instance
       * @default null
       */
      instance?: string | null;
      /** Status */
      status: number;
      /** Title */
      title: string;
      /** Type */
      type: string;
    };
    /** ReadyResponse */
    ReadyResponse: {
      /** Checks */
      checks: {
        [key: string]: boolean;
      };
      /** Status */
      status: string;
    };
    /** RegistrationIn */
    RegistrationIn: {
      /**
       * Entity Name
       * @description Used when the entity is new
       * @default
       */
      entity_name?: string;
      /**
       * Gstin
       * @description GSTIN, any case or spacing
       */
      gstin: string;
      /** Name */
      name: string;
    };
    /** ReviewTaskOut */
    ReviewTaskOut: {
      /** As Of Fy */
      as_of_fy: string | null;
      /** Attribute Key */
      attribute_key: string;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Node Id
       * Format: uuid
       */
      node_id: string;
      /** Open */
      open: boolean;
      /** Reason */
      reason: string;
    };
    /** SetResultOut */
    SetResultOut: {
      /** Changed */
      changed: string[];
      node: components["schemas"]["NodeOut"];
      /** Review Tasks */
      review_tasks: string[];
    };
    /** SnapshotOut */
    SnapshotOut: {
      /** As Of Fy */
      as_of_fy: string | null;
      /** Attributes */
      attributes: {
        [key: string]: unknown;
      };
      /**
       * Business Id
       * Format: uuid
       */
      business_id: string;
      /** Level */
      level: string | null;
      /** Lineage */
      lineage: string[];
      /**
       * Tenant Id
       * Format: uuid
       */
      tenant_id: string;
      /** Version */
      version: number;
    };
    /**
     * ValidationIssue
     * @description One failed check on the request. The submitted value is not echoed back.
     */
    ValidationIssue: {
      /** Loc */
      loc: (string | number)[];
      /** Msg */
      msg: string;
      /** Type */
      type: string;
    };
    /**
     * ValueState
     * @enum {string}
     */
    ValueState: "known" | "unsure" | "not_applicable";
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
};
export type $defs = Record<string, never>;
export interface operations {
  health_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HealthResponse"];
        };
      };
    };
  };
  ready_ready_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ReadyResponse"];
        };
      };
      /** @description Service Unavailable */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ReadyResponse"];
        };
      };
    };
  };
  create_entity_v1_profile_entities_post: {
    parameters: {
      query?: never;
      header?: {
        /** @description Tenant UUID; required until the identity service issues tokens */
        "x-tenant-id"?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["EntityIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["NodeOut"];
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  confirm_financial_year_v1_profile_financial_year_confirmations_post: {
    parameters: {
      query?: never;
      header?: {
        /** @description Tenant UUID; required until the identity service issues tokens */
        "x-tenant-id"?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["FinancialYearConfirmationIn"] | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FinancialYearConfirmationOut"];
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  create_location_v1_profile_locations_post: {
    parameters: {
      query?: never;
      header?: {
        /** @description Tenant UUID; required until the identity service issues tokens */
        "x-tenant-id"?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LocationIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["NodeOut"];
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  get_node_v1_profile_nodes__node_id__get: {
    parameters: {
      query?: never;
      header?: {
        /** @description Tenant UUID; required until the identity service issues tokens */
        "x-tenant-id"?: string | null;
      };
      path: {
        node_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["NodeOut"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  set_attributes_v1_profile_nodes__node_id__attributes_put: {
    parameters: {
      query?: never;
      header?: {
        /** @description Tenant UUID; required until the identity service issues tokens */
        "x-tenant-id"?: string | null;
      };
      path: {
        node_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AttributesIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SetResultOut"];
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  next_question_v1_profile_nodes__node_id__next_question_get: {
    parameters: {
      query: {
        /** @description 2025-26 */
        fy: string;
      };
      header?: {
        /** @description Tenant UUID; required until the identity service issues tokens */
        "x-tenant-id"?: string | null;
      };
      path: {
        node_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["NextQuestionOut"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  review_tasks_v1_profile_nodes__node_id__review_tasks_get: {
    parameters: {
      query?: never;
      header?: {
        /** @description Tenant UUID; required until the identity service issues tokens */
        "x-tenant-id"?: string | null;
      };
      path: {
        node_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ReviewTaskOut"][];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  snapshot_v1_profile_nodes__node_id__snapshot_get: {
    parameters: {
      query?: {
        /** @description 2025-26; empty means no per-year values */
        fy?: string | null;
      };
      header?: {
        /** @description Tenant UUID; required until the identity service issues tokens */
        "x-tenant-id"?: string | null;
      };
      path: {
        node_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SnapshotOut"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  ping_v1_profile_ping_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: string;
          };
        };
      };
    };
  };
  create_registration_v1_profile_registrations_post: {
    parameters: {
      query?: never;
      header?: {
        /** @description Tenant UUID; required until the identity service issues tokens */
        "x-tenant-id"?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RegistrationIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["NodeOut"];
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  prefill_v1_profile_registrations__node_id__prefill_post: {
    parameters: {
      query?: never;
      header?: {
        /** @description Tenant UUID; required until the identity service issues tokens */
        "x-tenant-id"?: string | null;
      };
      path: {
        node_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PrefillIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PrefillOut"];
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
}
