// Generated by make openapi-ts from packages/contracts/openapi. Do not edit.

export type paths = {
  "/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Health */
    get: operations["health_health_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/ready": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Ready */
    get: operations["ready_ready_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/rulebook/clauses/{clause_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** A clause with its document's regulator, type, reference, title and date */
    get: operations["read_clause_v1_rulebook_clauses__clause_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/rulebook/clauses/embeddings": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Store clause embeddings from one model; a clause's first embedding stays */
    put: operations["store_embeddings_v1_rulebook_clauses_embeddings_put"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/rulebook/clauses/unembedded": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Clauses with no embedding from a model yet, in clause id order */
    get: operations["list_unembedded_v1_rulebook_clauses_unembedded_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/rulebook/documents/{document_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** A stored document with its clauses in order */
    get: operations["read_document_v1_rulebook_documents__document_id__get"];
    /** Register a parsed regulator document; idempotent for the same clauses */
    put: operations["register_document_v1_rulebook_documents__document_id__put"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/rulebook/documents/{document_id}/mentions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Align the entity mentions found in a document; the unresolved go to review */
    put: operations["submit_mentions_v1_rulebook_documents__document_id__mentions_put"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/rulebook/documents/{document_id}/relation-candidates": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Stage the relations proposed for a document; idempotent per proposal */
    put: operations["submit_relations_v1_rulebook_documents__document_id__relation_candidates_put"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/rulebook/entities/{entity_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** A canonical entity with its aliases */
    get: operations["read_entity_v1_rulebook_entities__entity_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/rulebook/entities/{entity_id}/clauses": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Clauses that mention an entity, newest document first */
    get: operations["list_entity_clauses_v1_rulebook_entities__entity_id__clauses_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/rulebook/entities/resolve": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Resolve a name to a canonical entity; always 200, with a status */
    get: operations["resolve_entity_v1_rulebook_entities_resolve_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/rulebook/maintenance/transitions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Move replaced versions whose replacement has taken effect (the daily sweep) */
    post: operations["apply_transitions_v1_rulebook_maintenance_transitions_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/rulebook/ping": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Ping */
    get: operations["ping_v1_rulebook_ping_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/rulebook/relations": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Rule relations from a version, to a version or to an entity; name at least one */
    get: operations["list_relations_v1_rulebook_relations_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/rulebook/review/entities": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Open entity review groups: one per (entity type, proposed name) */
    get: operations["list_entity_groups_v1_rulebook_review_entities_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/rulebook/review/entities/decisions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Create the entity, add the name to one, or reject every open mention of a group */
    post: operations["decide_entity_group_v1_rulebook_review_entities_decisions_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/rulebook/review/entities/items": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Every open mention of one group, with the review ids a decision can name */
    get: operations["list_group_items_v1_rulebook_review_entities_items_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/rulebook/review/relations": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Relation candidates, open ones by default, in id order */
    get: operations["list_relation_candidates_v1_rulebook_review_relations_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/rulebook/review/relations/{candidate_id}/approve": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Approve a candidate into a rule relation from a draft rule version */
    post: operations["approve_relation_v1_rulebook_review_relations__candidate_id__approve_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/rulebook/review/relations/{candidate_id}/reject": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Reject a candidate with a reason */
    post: operations["reject_relation_v1_rulebook_review_relations__candidate_id__reject_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/rulebook/rule-versions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Rule versions in force on a date: published or superseded, as_of in their period */
    get: operations["list_rule_versions_v1_rulebook_rule_versions_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/rulebook/rule-versions/{rule_version_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** One rule version in any status, with its citations */
    get: operations["read_rule_version_v1_rulebook_rule_versions__rule_version_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/rulebook/rule-versions/{rule_version_id}/approve": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Approve a version under review; high-impact versions need two different approvers */
    post: operations["approve_v1_rulebook_rule_versions__rule_version_id__approve_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/rulebook/rule-versions/{rule_version_id}/citations": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** The clauses a rule version cites, with the quotes and their verification */
    get: operations["list_citations_v1_rulebook_rule_versions__rule_version_id__citations_get"];
    /** Cite clauses for a draft version; every quote must be in its clause */
    put: operations["add_citations_v1_rulebook_rule_versions__rule_version_id__citations_put"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/rulebook/rule-versions/{rule_version_id}/publish": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Publish an approved version, apply its relations and write the rule events */
    post: operations["publish_v1_rulebook_rule_versions__rule_version_id__publish_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/rulebook/rule-versions/{rule_version_id}/return": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Send a version under review or approved back to draft; starts a new round */
    post: operations["return_to_draft_v1_rulebook_rule_versions__rule_version_id__return_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/rulebook/rule-versions/{rule_version_id}/submit": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Submit a draft for review; starts a new approval round */
    post: operations["submit_v1_rulebook_rule_versions__rule_version_id__submit_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/rulebook/rule-versions/{rule_version_id}/withdraw": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Withdraw a published version with rule.withdrawn, effective today */
    post: operations["withdraw_v1_rulebook_rule_versions__rule_version_id__withdraw_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/rulebook/rules": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Rules by key with their latest title */
    get: operations["list_rules_v1_rulebook_rules_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/rulebook/search": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Hybrid clause search: full text and vectors fused by reciprocal rank */
    post: operations["search_v1_rulebook_search_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
};
export type webhooks = Record<string, never>;
export type components = {
  schemas: {
    /** ActorIn */
    ActorIn: {
      /**
       * Actor Id
       * Format: uuid
       * @description The analyst taking the step; a signed-in user's token overrides it
       */
      actor_id: string;
      /**
       * Note
       * @default
       */
      note?: string;
    };
    /** AlignmentOut */
    AlignmentOut: {
      /** Aligned */
      aligned: number;
      /** Queued */
      queued: number;
      /** Unchanged */
      unchanged: number;
    };
    /** ApprovalOut */
    ApprovalOut: {
      /**
       * Candidate Id
       * Format: uuid
       */
      candidate_id: string;
      /**
       * Rule Relation Id
       * Format: uuid
       */
      rule_relation_id: string;
    };
    /** ApproveIn */
    ApproveIn: {
      /**
       * Decided By
       * @description Who decided; a signed-in user's token overrides it with that user's id
       */
      decided_by: string;
      /**
       * From Rule Version Id
       * Format: uuid
       * @description The new version the relation starts from
       */
      from_rule_version_id: string;
      /**
       * Note
       * @default
       */
      note?: string;
      /**
       * Target Rule Version Id
       * @description The affected version, for relations that target one
       */
      target_rule_version_id?: string | null;
    };
    /**
     * AttributeLevel
     * @description Which node of the business hierarchy holds the value: the legal entity (PAN), one
     *     registration (GSTIN) or one place of business. Values are inherited downward.
     * @enum {string}
     */
    AttributeLevel: "entity" | "registration" | "location";
    /** CandidateIn */
    CandidateIn: {
      /** Confidence */
      confidence: number;
      /** Evidence Clause Ref */
      evidence_clause_ref: string;
      /** Evidence Quote */
      evidence_quote: string;
      /** Issues */
      issues?: components["schemas"]["IssueIn"][];
      /** Needs Review */
      needs_review: boolean;
      /** New Due On */
      new_due_on?: string | null;
      /** Period Label */
      period_label?: string | null;
      /** Quote Score */
      quote_score: number;
      relation: components["schemas"]["RelationKind"];
      /** Rule Key */
      rule_key?: string | null;
      /** Target Clause Ref */
      target_clause_ref: string;
      /** Target Name */
      target_name: string;
      /** Target Span End */
      target_span_end: number;
      /** Target Span Start */
      target_span_start: number;
      target_type: components["schemas"]["EntityType"];
    };
    /**
     * CandidateRejectReason
     * @enum {string}
     */
    CandidateRejectReason:
      "wrong_kind" | "wrong_target" | "not_in_text" | "duplicate" | "out_of_scope";
    /**
     * CandidateStatus
     * @enum {string}
     */
    CandidateStatus: "open" | "approved" | "rejected";
    /** CitationIn */
    CitationIn: {
      /**
       * Clause Id
       * Format: uuid
       */
      clause_id: string;
      /**
       * Quote
       * @description Verbatim text of the clause the rule rests on
       */
      quote: string;
    };
    /** CitationOut */
    CitationOut: {
      /**
       * Citation Id
       * Format: uuid
       */
      citation_id: string;
      /**
       * Clause Id
       * Format: uuid
       */
      clause_id: string;
      /** Clause Ref */
      clause_ref: string;
      /**
       * Document Id
       * Format: uuid
       */
      document_id: string;
      /** Match Score */
      match_score: number | null;
      /** Quote */
      quote: string;
      /**
       * Rule Version Id
       * Format: uuid
       */
      rule_version_id: string;
      /** Verified */
      verified: boolean;
      /** Verified At */
      verified_at: string | null;
    };
    /**
     * CitationsIn
     * @description Clauses the version cites. Every quote must be in its clause or nothing is stored.
     */
    CitationsIn: {
      /** Citations */
      citations: components["schemas"]["CitationIn"][];
    };
    /** CitationsOut */
    CitationsOut: {
      /** Added */
      added: number;
      /**
       * Citations
       * @description Every citation of the version now
       */
      citations: components["schemas"]["CitationOut"][];
      /** Unchanged */
      unchanged: number;
    };
    /** ClauseDetailOut */
    ClauseDetailOut: {
      /**
       * Clause Id
       * Format: uuid
       */
      clause_id: string;
      /** Clause Ref */
      clause_ref: string;
      doc_type: components["schemas"]["DocumentType"];
      /**
       * Document Id
       * Format: uuid
       */
      document_id: string;
      /** External Ref */
      external_ref: string;
      /** Language */
      language: string;
      /** Ordinal */
      ordinal: number;
      /** Page */
      page: number | null;
      /** Published At */
      published_at: string | null;
      /** Regulator */
      regulator: string;
      /** Text */
      text: string;
      /** Title */
      title: string;
      /** Url */
      url: string;
    };
    /** ClauseIn */
    ClauseIn: {
      /**
       * Clause Ref
       * @example en.p3
       */
      clause_ref: string;
      /** Page */
      page?: number | null;
      /** Text */
      text: string;
    };
    /** ClauseOut */
    ClauseOut: {
      /**
       * Clause Id
       * Format: uuid
       */
      clause_id: string;
      /** Clause Ref */
      clause_ref: string;
      /** Ordinal */
      ordinal: number;
      /** Page */
      page: number | null;
      /** Text */
      text: string;
    };
    /** DeadlineChangeOut */
    DeadlineChangeOut: {
      /**
       * Evidence Clause Id
       * Format: uuid
       */
      evidence_clause_id: string;
      /**
       * New Due On
       * Format: date
       */
      new_due_on: string;
      /** Period Label */
      period_label: string | null;
      /**
       * Rule Version Id
       * Format: uuid
       */
      rule_version_id: string;
    };
    /**
     * DecisionIn
     * @description Decide every open mention of one (entity type, proposed name).
     */
    DecisionIn: {
      /**
       * Decided By
       * @description Who decided; a signed-in user's token overrides it with that user's id
       */
      decided_by: string;
      decision: components["schemas"]["MentionDecision"];
      /**
       * Entity Id
       * @description The entity to add the name to
       */
      entity_id?: string | null;
      entity_type: components["schemas"]["EntityType"];
      /**
       * Note
       * @default
       */
      note?: string;
      /** Proposed Name */
      proposed_name: string;
      reject_reason?: components["schemas"]["EntityRejectReason"] | null;
      /**
       * Review Ids
       * @description The mentions this decision covers. Required for a name that does not name one entity across documents (empty, or a section or rule without its statute)
       */
      review_ids?: string[] | null;
    };
    /**
     * DocumentIn
     * @description A parsed regulator document. The id in the path must be the first half of ``sha256``.
     */
    DocumentIn: {
      /** Clauses */
      clauses: components["schemas"]["ClauseIn"][];
      doc_type: components["schemas"]["DocumentType"];
      /**
       * External Ref
       * @default
       * @example 01/2026-Central Tax
       */
      external_ref?: string;
      /**
       * Fetched At
       * Format: date-time
       */
      fetched_at: string;
      /**
       * Language
       * @example en
       */
      language: string;
      /**
       * Media Type
       * @example application/pdf
       */
      media_type: string;
      /**
       * Parser Version
       * @example pdf@1
       */
      parser_version: string;
      /** Published At */
      published_at?: string | null;
      /** Raw Uri */
      raw_uri?: string | null;
      /**
       * Regulator
       * @example CBIC
       */
      regulator: string;
      /** Sha256 */
      sha256: string;
      /**
       * Source Id
       * Format: uuid
       */
      source_id: string;
      /**
       * Title
       * @default
       */
      title?: string;
      /** Url */
      url: string;
    };
    /** DocumentOut */
    DocumentOut: {
      /** Clauses */
      clauses: components["schemas"]["ClauseOut"][];
      doc_type: components["schemas"]["DocumentType"];
      /**
       * Document Id
       * Format: uuid
       */
      document_id: string;
      /** External Ref */
      external_ref: string;
      /** Language */
      language: string;
      /** Media Type */
      media_type: string;
      /** Parser Version */
      parser_version: string;
      /** Published At */
      published_at: string | null;
      /** Regulator */
      regulator: string;
      /** Sha256 */
      sha256: string;
      /**
       * Source Id
       * Format: uuid
       */
      source_id: string;
      /** Title */
      title: string;
      /** Url */
      url: string;
    };
    /**
     * DocumentType
     * @enum {string}
     */
    DocumentType: "notification" | "circular" | "press_release" | "act_amendment";
    /** EmbeddingIn */
    EmbeddingIn: {
      /**
       * Clause Id
       * Format: uuid
       */
      clause_id: string;
      /** Vector */
      vector: number[];
    };
    /**
     * EmbeddingsIn
     * @description Clause vectors from one model. ``dims`` must be the rulebook's 512: a model that serves
     *     another size is refused, because its vectors would not compare with the stored ones.
     */
    EmbeddingsIn: {
      /**
       * Dims
       * @example 512
       */
      dims: number;
      /** Items */
      items: components["schemas"]["EmbeddingIn"][];
      /**
       * Model
       * @example voyage/voyage-3.5-lite
       */
      model: string;
    };
    /** EmbeddingsStoredOut */
    EmbeddingsStoredOut: {
      /**
       * Stored
       * @description Embeddings stored now
       */
      stored: number;
      /**
       * Unchanged
       * @description Clauses that had an embedding from this model already
       */
      unchanged: number;
    };
    /** EntityOut */
    EntityOut: {
      /** Aliases */
      aliases: string[];
      /** Canonical Name */
      canonical_name: string;
      /**
       * Entity Id
       * Format: uuid
       */
      entity_id: string;
      entity_type: components["schemas"]["EntityType"];
    };
    /**
     * EntityRejectReason
     * @enum {string}
     */
    EntityRejectReason: "not_an_entity" | "wrong_type" | "text_artifact" | "out_of_scope";
    /** EntityResolutionOut */
    EntityResolutionOut: {
      /** Candidates */
      candidates: components["schemas"]["EntityOut"][];
      entity: components["schemas"]["EntityOut"] | null;
      entity_type: components["schemas"]["EntityType"];
      /** Name */
      name: string;
      /** Normalised */
      normalised: string;
      /** @description resolved: entity is set. ambiguous: the name is an alias of every entity in candidates. not_found: nothing has the name. unqualified: a section or rule without its statute (39@cgst-act). empty: nothing left after normalising */
      status: components["schemas"]["ResolutionStatus"];
    };
    /**
     * EntityType
     * @description The ten kinds of entity the knowledge tables hold. Values match the ``type`` column.
     * @enum {string}
     */
    EntityType:
      | "notification"
      | "circular"
      | "section"
      | "rule"
      | "form"
      | "hsn_code"
      | "sac_code"
      | "tax_rate"
      | "threshold"
      | "state";
    /** EventOut */
    EventOut: {
      /** Causation Id */
      causation_id: string | null;
      /**
       * Correlation Id
       * Format: uuid
       */
      correlation_id: string;
      /**
       * Event Id
       * Format: uuid
       */
      event_id: string;
      /** Topic */
      topic: string;
    };
    /** GroupDecisionOut */
    GroupDecisionOut: {
      /** Entity Id */
      entity_id: string | null;
      /** Items Closed */
      items_closed: number;
      /** Relation Targets Updated */
      relation_targets_updated: number;
      /** Resolution */
      resolution: string | null;
      /** Status */
      status: string;
    };
    /** HealthResponse */
    HealthResponse: {
      /** Service */
      service: string;
      /** Status */
      status: string;
      /** Version */
      version: string;
    };
    /** IssueIn */
    IssueIn: {
      /** Code */
      code: string;
      /**
       * Detail
       * @default
       */
      detail?: string;
    };
    /** LifecycleOut */
    LifecycleOut: {
      /**
       * Approved By
       * @description Approvers of the current review round
       */
      approved_by: string[];
      /**
       * Effective From
       * Format: date
       */
      effective_from: string;
      /** Effective To */
      effective_to: string | null;
      /**
       * Events
       * @description Events this step wrote to the outbox
       */
      events: components["schemas"]["EventOut"][];
      /** High Impact */
      high_impact: boolean;
      /** Published At */
      published_at: string | null;
      /** Required Approvals */
      required_approvals: number;
      /**
       * Rule Id
       * Format: uuid
       */
      rule_id: string;
      /**
       * Rule Version Id
       * Format: uuid
       */
      rule_version_id: string;
      seed_status: components["schemas"]["SeedStatus"];
      status: components["schemas"]["RuleVersionStatus"];
      /**
       * Submitted At
       * @description Start of the current review round
       */
      submitted_at: string | null;
      /** Version */
      version: number;
    };
    /**
     * MentionDecision
     * @enum {string}
     */
    MentionDecision: "create_entity" | "add_alias" | "reject";
    /** MentionedClauseOut */
    MentionedClauseOut: {
      /**
       * Clause Id
       * Format: uuid
       */
      clause_id: string;
      /** Clause Ref */
      clause_ref: string;
      doc_type: components["schemas"]["DocumentType"];
      /**
       * Document Id
       * Format: uuid
       */
      document_id: string;
      /** External Ref */
      external_ref: string;
      /** Language */
      language: string;
      /** Mentions */
      mentions: components["schemas"]["MentionOut"][];
      /** Ordinal */
      ordinal: number;
      /**
       * Out Of Force
       * @description The clause is cited with a verified quote by a published, superseded or withdrawn version and none of them is in force on as_of; false without as_of or a citation
       */
      out_of_force: boolean;
      /** Page */
      page: number | null;
      /** Published At */
      published_at: string | null;
      /** Regulator */
      regulator: string;
      /** Text */
      text: string;
      /** Title */
      title: string;
      /** Url */
      url: string;
    };
    /** MentionGroupOut */
    MentionGroupOut: {
      entity_type: components["schemas"]["EntityType"];
      /** Examples */
      examples: components["schemas"]["ReviewItemOut"][];
      /** Open Count */
      open_count: number;
      /** Proposed Name */
      proposed_name: string;
    };
    /** MentionIn */
    MentionIn: {
      /** Clause Ref */
      clause_ref: string;
      entity_type: components["schemas"]["EntityType"];
      /**
       * Proposed Name
       * @default
       */
      proposed_name?: string;
      /** Span End */
      span_end: number;
      /** Span Start */
      span_start: number;
      /** Text */
      text: string;
    };
    /** MentionOut */
    MentionOut: {
      /** Span End */
      span_end: number;
      /** Span Start */
      span_start: number;
      /** Text */
      text: string;
    };
    /**
     * MentionsIn
     * @description The mentions an extractor found in one document; the extractor names itself.
     */
    MentionsIn: {
      /**
       * Extractor
       * @example grammar@1
       */
      extractor: string;
      /** Mentions */
      mentions: components["schemas"]["MentionIn"][];
    };
    /**
     * Problem
     * @description The body of every error response.
     */
    Problem: {
      /**
       * Correlation Id
       * @default null
       */
      correlation_id?: string | null;
      /**
       * Detail
       * @default null
       */
      detail?: string | null;
      /**
       * Errors
       * @default null
       */
      errors?: components["schemas"]["ValidationIssue"][] | null;
      /**
       * Instance
       * @default null
       */
      instance?: string | null;
      /** Status */
      status: number;
      /** Title */
      title: string;
      /** Type */
      type: string;
    };
    /** PublicationOut */
    PublicationOut: {
      /**
       * Approved By
       * @description Approvers of the current review round
       */
      approved_by: string[];
      /** Attribute Keys */
      attribute_keys: string[];
      /**
       * Correlation Id
       * Format: uuid
       */
      correlation_id: string;
      /** Deadline Changes */
      deadline_changes: components["schemas"]["DeadlineChangeOut"][];
      /**
       * Effective From
       * Format: date
       */
      effective_from: string;
      /** Effective To */
      effective_to: string | null;
      /**
       * Events
       * @description Events this step wrote to the outbox
       */
      events: components["schemas"]["EventOut"][];
      /** High Impact */
      high_impact: boolean;
      /** Published At */
      published_at: string | null;
      /** Replacements */
      replacements: components["schemas"]["ReplacementOut"][];
      /** Required Approvals */
      required_approvals: number;
      /**
       * Rule Id
       * Format: uuid
       */
      rule_id: string;
      /**
       * Rule Version Id
       * Format: uuid
       */
      rule_version_id: string;
      seed_status: components["schemas"]["SeedStatus"];
      status: components["schemas"]["RuleVersionStatus"];
      /**
       * Submitted At
       * @description Start of the current review round
       */
      submitted_at: string | null;
      /** Version */
      version: number;
    };
    /** ReadyResponse */
    ReadyResponse: {
      /** Checks */
      checks: {
        [key: string]: boolean;
      };
      /** Status */
      status: string;
    };
    /** RegisteredOut */
    RegisteredOut: {
      /**
       * Clause Ids
       * @description Clause ref to the id every service derives
       */
      clause_ids: {
        [key: string]: string;
      };
      /** Created */
      created: boolean;
      /**
       * Document Id
       * Format: uuid
       */
      document_id: string;
      /**
       * Metadata Differs
       * @description Fields whose submitted value differs from the stored one; the stored wins
       */
      metadata_differs: string[];
    };
    /** RejectIn */
    RejectIn: {
      /**
       * Decided By
       * @description Who decided; a signed-in user's token overrides it with that user's id
       */
      decided_by: string;
      /**
       * Note
       * @default
       */
      note?: string;
      reason: components["schemas"]["CandidateRejectReason"];
    };
    /** RelationCandidateOut */
    RelationCandidateOut: {
      /**
       * Candidate Id
       * Format: uuid
       */
      candidate_id: string;
      /** Confidence */
      confidence: number;
      /** Decided By */
      decided_by: string;
      /**
       * Document Id
       * Format: uuid
       */
      document_id: string;
      /**
       * Evidence Clause Id
       * Format: uuid
       */
      evidence_clause_id: string;
      /** Evidence Quote */
      evidence_quote: string;
      /** Issues */
      issues: components["schemas"]["IssueIn"][];
      /** Model */
      model: string;
      /** Needs Review */
      needs_review: boolean;
      /** New Due On */
      new_due_on: string | null;
      /** Period Label */
      period_label: string | null;
      /** Prompt Version */
      prompt_version: string;
      /** Quote Score */
      quote_score: number;
      /** Reject Reason */
      reject_reason: string | null;
      relation: components["schemas"]["RelationKind"];
      /** Status */
      status: string;
      /** Target Entity Id */
      target_entity_id: string | null;
      /** Target Name */
      target_name: string;
      /** Target Rule Key */
      target_rule_key: string | null;
      target_type: components["schemas"]["EntityType"];
    };
    /**
     * RelationKind
     * @description How a rule version relates to another rule version or to an entity.
     *
     *     ``supersedes`` replaces a version from an effective date; ``amends`` changes part of it;
     *     ``refers_to`` cites it or an entity; ``exempts`` carves something out of it;
     *     ``extends_deadline`` moves the due date of a period; ``corrects`` replaces what an earlier
     *     version said (a corrigendum); ``withdraws`` rescinds it.
     * @enum {string}
     */
    RelationKind:
      | "supersedes"
      | "amends"
      | "refers_to"
      | "exempts"
      | "extends_deadline"
      | "corrects"
      | "withdraws";
    /** RelationOut */
    RelationOut: {
      /** Candidate Id */
      candidate_id: string | null;
      /**
       * Evidence Clause Id
       * Format: uuid
       */
      evidence_clause_id: string;
      /** Evidence Clause Ref */
      evidence_clause_ref: string;
      /**
       * Evidence Document Id
       * Format: uuid
       */
      evidence_document_id: string;
      /**
       * From Rule Version Id
       * Format: uuid
       */
      from_rule_version_id: string;
      /** New Due On */
      new_due_on: string | null;
      /** Period Label */
      period_label: string | null;
      relation: components["schemas"]["RelationKind"];
      /**
       * Relation Id
       * Format: uuid
       */
      relation_id: string;
      /** To Entity Id */
      to_entity_id: string | null;
      /**
       * To Kind
       * @description rule_version or an entity type
       */
      to_kind: string;
      /**
       * To Ref
       * @description The target version's id or the entity's canonical name
       */
      to_ref: string;
      /** To Rule Version Id */
      to_rule_version_id: string | null;
    };
    /**
     * RelationsIn
     * @description What one run of the relation stage produced for a document, including the run's own
     *     issues and any model output it could not turn into a candidate.
     */
    RelationsIn: {
      /** Candidates */
      candidates?: components["schemas"]["CandidateIn"][];
      /**
       * Extractor
       * @example extraction.rule_relations@1
       */
      extractor: string;
      /**
       * Model
       * @default
       */
      model?: string;
      /**
       * Outcome
       * @enum {string}
       */
      outcome: "ok" | "needs_review" | "no_targets" | "unparseable" | "failed";
      /** Run Issues */
      run_issues?: components["schemas"]["IssueIn"][];
    };
    /** ReplacementOut */
    ReplacementOut: {
      /**
       * Effective To
       * @description The replaced version's end after the cut
       */
      effective_to: string | null;
      moves_to: components["schemas"]["RuleVersionStatus"];
      /**
       * Pending
       * @description True until the published version takes effect; the daily sweep moves it
       */
      pending: boolean;
      relation: components["schemas"]["RelationKind"];
      /**
       * Rule Version Id
       * Format: uuid
       */
      rule_version_id: string;
      /** @description Its status now */
      status: components["schemas"]["RuleVersionStatus"];
    };
    /**
     * ResolutionStatus
     * @enum {string}
     */
    ResolutionStatus: "resolved" | "ambiguous" | "not_found" | "unqualified" | "empty";
    /** ReviewItemOut */
    ReviewItemOut: {
      /**
       * Clause Id
       * Format: uuid
       */
      clause_id: string;
      /**
       * Document Id
       * Format: uuid
       */
      document_id: string;
      /** Mention Text */
      mention_text: string;
      /** Reason */
      reason: string;
      /**
       * Review Id
       * Format: uuid
       */
      review_id: string;
      /** Span End */
      span_end: number;
      /** Span Start */
      span_start: number;
    };
    /** RuleOut */
    RuleOut: {
      /** Regulator */
      regulator: string;
      /**
       * Rule Id
       * Format: uuid
       */
      rule_id: string;
      /** Rule Key */
      rule_key: string;
      /** Title */
      title: string;
    };
    /** RuleVersionDetailOut */
    RuleVersionDetailOut: {
      /** Citations */
      citations: components["schemas"]["CitationOut"][];
      /**
       * Effective From
       * Format: date
       */
      effective_from: string;
      /**
       * Effective To
       * @description Exclusive; null while open-ended
       */
      effective_to: string | null;
      /**
       * High Impact
       * @description Publishing needs two different approvers (ADR-006)
       */
      high_impact: boolean;
      level: components["schemas"]["AttributeLevel"];
      /** Obligation Template */
      obligation_template: {
        [key: string]: unknown;
      };
      /** Published At */
      published_at: string | null;
      /** Recurrence */
      recurrence: {
        [key: string]: unknown;
      } | null;
      /** Regulator */
      regulator: string;
      /**
       * Rule Id
       * Format: uuid
       */
      rule_id: string;
      /** Rule Key */
      rule_key: string;
      /**
       * Rule Version Id
       * Format: uuid
       */
      rule_version_id: string;
      seed_status: components["schemas"]["SeedStatus"];
      /** Source */
      source: {
        [key: string]: unknown;
      };
      /**
       * Specification
       * @description The kernel's predicate tree mapping
       */
      specification: {
        [key: string]: unknown;
      };
      status: components["schemas"]["RuleVersionStatus"];
      /** Summary */
      summary: string;
      /** Title */
      title: string;
      /** Todo */
      todo: string[];
      /** Version */
      version: number;
    };
    /** RuleVersionOut */
    RuleVersionOut: {
      /**
       * Effective From
       * Format: date
       */
      effective_from: string;
      /**
       * Effective To
       * @description Exclusive; null while open-ended
       */
      effective_to: string | null;
      /**
       * High Impact
       * @description Publishing needs two different approvers (ADR-006)
       */
      high_impact: boolean;
      level: components["schemas"]["AttributeLevel"];
      /** Obligation Template */
      obligation_template: {
        [key: string]: unknown;
      };
      /** Published At */
      published_at: string | null;
      /** Recurrence */
      recurrence: {
        [key: string]: unknown;
      } | null;
      /** Regulator */
      regulator: string;
      /**
       * Rule Id
       * Format: uuid
       */
      rule_id: string;
      /** Rule Key */
      rule_key: string;
      /**
       * Rule Version Id
       * Format: uuid
       */
      rule_version_id: string;
      seed_status: components["schemas"]["SeedStatus"];
      /** Source */
      source: {
        [key: string]: unknown;
      };
      /**
       * Specification
       * @description The kernel's predicate tree mapping
       */
      specification: {
        [key: string]: unknown;
      };
      status: components["schemas"]["RuleVersionStatus"];
      /** Summary */
      summary: string;
      /** Title */
      title: string;
      /** Todo */
      todo: string[];
      /** Version */
      version: number;
    };
    /**
     * RuleVersionStatus
     * @enum {string}
     */
    RuleVersionStatus:
      "draft" | "in_review" | "approved" | "published" | "superseded" | "withdrawn";
    /** SearchHitOut */
    SearchHitOut: {
      /**
       * Cited By
       * @description Published or superseded rule versions citing the clause with a verified quote, in force on as_of when it is given
       */
      cited_by: string[];
      /**
       * Clause Id
       * Format: uuid
       */
      clause_id: string;
      /** Clause Ref */
      clause_ref: string;
      doc_type: components["schemas"]["DocumentType"];
      /**
       * Document Id
       * Format: uuid
       */
      document_id: string;
      /**
       * External Ref
       * @description The document's number, such as 01/2026-Central Tax
       */
      external_ref: string;
      /**
       * Lexical Rank
       * @description 1-based rank in the lexical leg, if in it
       */
      lexical_rank: number | null;
      /**
       * Out Of Force
       * @description The clause is cited with a verified quote by a published, superseded or withdrawn version and none of them is in force on as_of; false without as_of or a citation
       */
      out_of_force: boolean;
      /** Published At */
      published_at: string | null;
      /** Regulator */
      regulator: string;
      /**
       * Score
       * @description Reciprocal rank fusion over the two legs
       */
      score: number;
      /** Text */
      text: string;
      /** Title */
      title: string;
      /**
       * Vector Rank
       * @description 1-based rank in the vector leg, if in it
       */
      vector_rank: number | null;
    };
    /**
     * SearchIn
     * @description A hybrid search. ``text`` feeds the lexical leg; ``vector``, the text's embedding from
     *     ``model``, feeds the vector leg. ``as_of`` keeps documents published on or before it.
     */
    SearchIn: {
      /** As Of */
      as_of?: string | null;
      /** Doc Types */
      doc_types?: components["schemas"]["DocumentType"][];
      /**
       * K
       * @default 8
       */
      k?: number;
      /**
       * Model
       * @description Required with a vector
       */
      model?: string | null;
      /** Regulator */
      regulator?: string | null;
      /** Text */
      text: string;
      /** Vector */
      vector?: number[] | null;
    };
    /**
     * SeedStatus
     * @enum {string}
     */
    SeedStatus: "needs_review" | "reviewed";
    /** StagingOut */
    StagingOut: {
      /** Candidate Ids */
      candidate_ids: string[];
      /** Created */
      created: number;
      /** Unchanged */
      unchanged: number;
    };
    /** SubmitIn */
    SubmitIn: {
      /**
       * Actor Id
       * Format: uuid
       * @description The analyst taking the step; a signed-in user's token overrides it
       */
      actor_id: string;
      /**
       * High Impact
       * @description Needs two different approvers; once set, a later submission keeps it
       * @default false
       */
      high_impact?: boolean;
      /**
       * Note
       * @default
       */
      note?: string;
    };
    /** TransitionOut */
    TransitionOut: {
      /**
       * Caused By Rule Version Id
       * Format: uuid
       */
      caused_by_rule_version_id: string;
      /**
       * Effective From
       * Format: date
       */
      effective_from: string;
      /**
       * Rule Id
       * Format: uuid
       */
      rule_id: string;
      /**
       * Rule Version Id
       * Format: uuid
       */
      rule_version_id: string;
      status: components["schemas"]["RuleVersionStatus"];
    };
    /** TransitionsIn */
    TransitionsIn: {
      /**
       * As Of
       * @description Day to sweep up to; today in India when empty, never later
       */
      as_of?: string | null;
    };
    /** TransitionsOut */
    TransitionsOut: {
      /**
       * As Of
       * Format: date
       */
      as_of: string;
      /** Events */
      events: components["schemas"]["EventOut"][];
      /** Transitions */
      transitions: components["schemas"]["TransitionOut"][];
    };
    /**
     * ValidationIssue
     * @description One failed check on the request. The submitted value is not echoed back.
     */
    ValidationIssue: {
      /** Loc */
      loc: (string | number)[];
      /** Msg */
      msg: string;
      /** Type */
      type: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
};
export type $defs = Record<string, never>;
export interface operations {
  health_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HealthResponse"];
        };
      };
    };
  };
  ready_ready_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ReadyResponse"];
        };
      };
      /** @description Service Unavailable */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ReadyResponse"];
        };
      };
    };
  };
  read_clause_v1_rulebook_clauses__clause_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        clause_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ClauseDetailOut"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  store_embeddings_v1_rulebook_clauses_embeddings_put: {
    parameters: {
      query?: never;
      header?: {
        /** @description Shared secret for writes (CW_RULEBOOK_WRITE_TOKEN), accepted when CW_AUTH_MODE is header or dual and the request carries no bearer token; a service token needs rulebook:write */
        "x-cw-write-token"?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["EmbeddingsIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EmbeddingsStoredOut"];
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Service Unavailable */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  list_unembedded_v1_rulebook_clauses_unembedded_get: {
    parameters: {
      query: {
        /** @description Continue after this clause id */
        after?: string | null;
        document_id?: string | null;
        limit?: number;
        model: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ClauseDetailOut"][];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  read_document_v1_rulebook_documents__document_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        document_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DocumentOut"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  register_document_v1_rulebook_documents__document_id__put: {
    parameters: {
      query?: never;
      header?: {
        /** @description Shared secret for writes (CW_RULEBOOK_WRITE_TOKEN), accepted when CW_AUTH_MODE is header or dual and the request carries no bearer token; a service token needs rulebook:write */
        "x-cw-write-token"?: string | null;
      };
      path: {
        document_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["DocumentIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RegisteredOut"];
        };
      };
      /** @description Stored now */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RegisteredOut"];
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Service Unavailable */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  submit_mentions_v1_rulebook_documents__document_id__mentions_put: {
    parameters: {
      query?: never;
      header?: {
        /** @description Shared secret for writes (CW_RULEBOOK_WRITE_TOKEN), accepted when CW_AUTH_MODE is header or dual and the request carries no bearer token; a service token needs rulebook:write */
        "x-cw-write-token"?: string | null;
      };
      path: {
        document_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["MentionsIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AlignmentOut"];
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Service Unavailable */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  submit_relations_v1_rulebook_documents__document_id__relation_candidates_put: {
    parameters: {
      query?: never;
      header?: {
        /** @description Shared secret for writes (CW_RULEBOOK_WRITE_TOKEN), accepted when CW_AUTH_MODE is header or dual and the request carries no bearer token; a service token needs rulebook:write */
        "x-cw-write-token"?: string | null;
      };
      path: {
        document_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RelationsIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StagingOut"];
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Service Unavailable */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  read_entity_v1_rulebook_entities__entity_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        entity_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EntityOut"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  list_entity_clauses_v1_rulebook_entities__entity_id__clauses_get: {
    parameters: {
      query?: {
        /** @description Only documents published on or before this date; each clause says whether its rule is out of force then */
        as_of?: string | null;
        limit?: number;
      };
      header?: never;
      path: {
        entity_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MentionedClauseOut"][];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  resolve_entity_v1_rulebook_entities_resolve_get: {
    parameters: {
      query: {
        name: string;
        type: components["schemas"]["EntityType"];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EntityResolutionOut"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  apply_transitions_v1_rulebook_maintenance_transitions_post: {
    parameters: {
      query?: never;
      header?: {
        /** @description Shared secret for analyst actions (CW_RULEBOOK_REVIEW_TOKEN), accepted when CW_AUTH_MODE is header or dual and the request carries no bearer token */
        "x-cw-review-token"?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["TransitionsIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TransitionsOut"];
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Service Unavailable */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  ping_v1_rulebook_ping_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: string;
          };
        };
      };
    };
  };
  list_relations_v1_rulebook_relations_get: {
    parameters: {
      query?: {
        from_rule_version_id?: string | null;
        limit?: number;
        /** @description Only relations from versions that have been published */
        published_only?: boolean;
        relation?: components["schemas"]["RelationKind"] | null;
        to_entity_id?: string | null;
        to_rule_version_id?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RelationOut"][];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  list_entity_groups_v1_rulebook_review_entities_get: {
    parameters: {
      query?: {
        after_name?: string | null;
        after_type?: components["schemas"]["EntityType"] | null;
        entity_type?: components["schemas"]["EntityType"] | null;
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MentionGroupOut"][];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  decide_entity_group_v1_rulebook_review_entities_decisions_post: {
    parameters: {
      query?: never;
      header?: {
        /** @description Shared secret for analyst actions (CW_RULEBOOK_REVIEW_TOKEN), accepted when CW_AUTH_MODE is header or dual and the request carries no bearer token */
        "x-cw-review-token"?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["DecisionIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GroupDecisionOut"];
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Service Unavailable */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  list_group_items_v1_rulebook_review_entities_items_get: {
    parameters: {
      query: {
        entity_type: components["schemas"]["EntityType"];
        proposed_name?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ReviewItemOut"][];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  list_relation_candidates_v1_rulebook_review_relations_get: {
    parameters: {
      query?: {
        after?: string | null;
        document_id?: string | null;
        limit?: number;
        status?: components["schemas"]["CandidateStatus"] | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RelationCandidateOut"][];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  approve_relation_v1_rulebook_review_relations__candidate_id__approve_post: {
    parameters: {
      query?: never;
      header?: {
        /** @description Shared secret for analyst actions (CW_RULEBOOK_REVIEW_TOKEN), accepted when CW_AUTH_MODE is header or dual and the request carries no bearer token */
        "x-cw-review-token"?: string | null;
      };
      path: {
        candidate_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ApproveIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApprovalOut"];
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Service Unavailable */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  reject_relation_v1_rulebook_review_relations__candidate_id__reject_post: {
    parameters: {
      query?: never;
      header?: {
        /** @description Shared secret for analyst actions (CW_RULEBOOK_REVIEW_TOKEN), accepted when CW_AUTH_MODE is header or dual and the request carries no bearer token */
        "x-cw-review-token"?: string | null;
      };
      path: {
        candidate_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RejectIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RelationCandidateOut"];
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Service Unavailable */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  list_rule_versions_v1_rulebook_rule_versions_get: {
    parameters: {
      query: {
        /** @description Continue after this rule key */
        after?: string | null;
        as_of: string;
        limit?: number;
        regulator?: string | null;
        rule_key?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RuleVersionOut"][];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  read_rule_version_v1_rulebook_rule_versions__rule_version_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        rule_version_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RuleVersionDetailOut"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  approve_v1_rulebook_rule_versions__rule_version_id__approve_post: {
    parameters: {
      query?: never;
      header?: {
        /** @description Shared secret for analyst actions (CW_RULEBOOK_REVIEW_TOKEN), accepted when CW_AUTH_MODE is header or dual and the request carries no bearer token */
        "x-cw-review-token"?: string | null;
      };
      path: {
        rule_version_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ActorIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LifecycleOut"];
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Service Unavailable */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  list_citations_v1_rulebook_rule_versions__rule_version_id__citations_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        rule_version_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CitationOut"][];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  add_citations_v1_rulebook_rule_versions__rule_version_id__citations_put: {
    parameters: {
      query?: never;
      header?: {
        /** @description Shared secret for analyst actions (CW_RULEBOOK_REVIEW_TOKEN), accepted when CW_AUTH_MODE is header or dual and the request carries no bearer token */
        "x-cw-review-token"?: string | null;
      };
      path: {
        rule_version_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CitationsIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CitationsOut"];
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Service Unavailable */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  publish_v1_rulebook_rule_versions__rule_version_id__publish_post: {
    parameters: {
      query?: never;
      header?: {
        /** @description Shared secret for analyst actions (CW_RULEBOOK_REVIEW_TOKEN), accepted when CW_AUTH_MODE is header or dual and the request carries no bearer token */
        "x-cw-review-token"?: string | null;
      };
      path: {
        rule_version_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ActorIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PublicationOut"];
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Service Unavailable */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  return_to_draft_v1_rulebook_rule_versions__rule_version_id__return_post: {
    parameters: {
      query?: never;
      header?: {
        /** @description Shared secret for analyst actions (CW_RULEBOOK_REVIEW_TOKEN), accepted when CW_AUTH_MODE is header or dual and the request carries no bearer token */
        "x-cw-review-token"?: string | null;
      };
      path: {
        rule_version_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ActorIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LifecycleOut"];
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Service Unavailable */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  submit_v1_rulebook_rule_versions__rule_version_id__submit_post: {
    parameters: {
      query?: never;
      header?: {
        /** @description Shared secret for analyst actions (CW_RULEBOOK_REVIEW_TOKEN), accepted when CW_AUTH_MODE is header or dual and the request carries no bearer token */
        "x-cw-review-token"?: string | null;
      };
      path: {
        rule_version_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SubmitIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LifecycleOut"];
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Service Unavailable */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  withdraw_v1_rulebook_rule_versions__rule_version_id__withdraw_post: {
    parameters: {
      query?: never;
      header?: {
        /** @description Shared secret for analyst actions (CW_RULEBOOK_REVIEW_TOKEN), accepted when CW_AUTH_MODE is header or dual and the request carries no bearer token */
        "x-cw-review-token"?: string | null;
      };
      path: {
        rule_version_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ActorIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LifecycleOut"];
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Service Unavailable */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  list_rules_v1_rulebook_rules_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RuleOut"][];
        };
      };
    };
  };
  search_v1_rulebook_search_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SearchIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SearchHitOut"][];
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
}
